### PR TITLE
fix(app): edit paused step item copy

### LINKED ISSUE #10338: 6.0 Feedback:  Cancelling during a delay shows up as "user paused protocol"
### Overview

If you cancel a protocol in the middle of a long delay, the Opentrons App will temporarily, incorrectly, say you've *paused the protocol.*

### Current Behavior

Shortly after hitting the "Cancel" button, the run log looks like this:

Screen Shot 2022-05-18 at 5 37 43 PM

This is unexpected because I never paused the protocol.

After the robot completes the post-cancellation drop-tip and home, the run log changes to this, which is more reasonable:

Screen Shot 2022-05-18 at 5 38 51 PM

### Expected Behavior

The app shouldn't say I paused the protocol.

### Steps To Reproduce

Upload and run this protocol:

```python
metadata = {"apiLevel": "2.12"}

def run(protocol):
    tip_rack = protocol.load_labware("opentrons_96_tiprack_300ul", 1)
    pipette = protocol.load_instrument("p300_multi_gen2", mount="left", tip_racks=[tip_rack])
    pipette.pick_up_tip()
    protocol.delay(minutes=10)
    pipette.return_tip()
```

Cancel the protocol during the 10-minute delay.

### Operating system

Mac

### Robot setup or anything else?

_No response_

### PR DESCRIPTION
**Pull request by vabruzzo**
# Overview
Remove paused copy in step item component when run is stopped during a delay.
Closes #10338

# Changelog
- Edited paused copy in `StepItem` from "User paused protocol for xx:xx:xx" to "Protocol paused for xx:xx:xx"
- Adjusted `StepItem` memoization to remain in sync with run header status

# Review requests
Cancel a run during a long delay to confirm paused copy no longer renders in `StepItem`

# Risk assessment
Low

### CODE REVIEW

File: app/src/organisms/Devices/ProtocolRun/StepItem.tsx [hunk 1]
```diff
@@ -182,7 +183,9 @@ export function StepItemComponent(props: StepItemProps): JSX.Element | null {
                   runCommand={runCommandSummary}
                   runId={runId}
                 />
-                {runPausedAt != null && isMostRecentCommand ? (
+                {runPausedAt != null &&
```
Comment (vabruzzo) [inline app/src/organisms/Devices/ProtocolRun/StepItem.tsx]: When the `CancelConfirmModal` is opened, the run is paused. When the cancel is confirmed and stop run is executed, the run is never unpaused, presumably because it should just be stopped from that paused state. The `runPausedAt` state lingers (most of the time) leading to the buggy display at issue. Checking if the stop run has been requested seems to be an extra layer of determining if we should render the paused copy here. But that action seems to be inconsistently firing, or there is a race condition somewhere that I've yet to track down. My question here is, is there a simpler approach here that can avoid this strange inconsistent behavior? I've been digging into the code to figure out why it is inconsistent but have come up empty so far, it might be at the API level but I haven't checked that yet.

The other edit in the `ConfirmCancelModal` itself seems to have helped make the behavior more consistent, but it isn't fully consistent. Every few times I test this the runStatus never updates to `RUN_STATUS_STOP_REQUESTED` or the `runPausedAt` is never set back to null. Sometimes one or both of these things do happen and the bug does not appear.

File: app/src/organisms/RunDetails/ConfirmCancelModal.tsx [hunk 2]
```diff
@@ -19,11 +19,11 @@ export function ConfirmCancelModal(
   props: ConfirmCancelModalProps
 ): JSX.Element {
   const { onClose, runId } = props
-  const { stopRun } = useStopRunMutation()
+  const { stop } = useRunControls(runId)
```
Comment (vabruzzo) [inline app/src/organisms/RunDetails/ConfirmCancelModal.tsx]: This is the only place in the app that we were using one of the play, pause, or stop mutation hooks directly. Everywhere else we use `useRunControls`. I changed this to be consistent with what we use elsewhere throughout the app and it seems to have made the correct behavior occur more consistently, but it still isn't 100%.

I'm not sure if this is the emulator being inconsistent, or a race condition in the back end, or some async react hook weirdness on the front-end. Hopefully someone has encountered something like this before in the app or might have some guidance before I start digging deeper into one of this more tricky possible causes of the bug.

File: app/src/organisms/Devices/ProtocolRun/StepItem.tsx (hunk 1 above)
Comment (vabruzzo) [reply app/src/organisms/Devices/ProtocolRun/StepItem.tsx]: Another potential fix here is to change the copy. The issue is that when a user brings up the cancel confirm modal, the run is paused, but technically the user didn't pause the run. Perhaps if the copy in the step item read "Protocol paused for: xx:xx" instead of "User paused protocol for xx:xx" it would be less confusing?

Comment (koji) [reply app/src/organisms/Devices/ProtocolRun/StepItem.tsx]: @ecormany  what do you think 👆

Comment (ecormany) [reply app/src/organisms/Devices/ProtocolRun/StepItem.tsx]: Cody's designs already have "Protocol paused for xx:xx:xx", so if we adopt that now we won't have to change it again in the near future.

Comment (vabruzzo) [reply app/src/organisms/Devices/ProtocolRun/StepItem.tsx]: Great. @emilywools, the proposed change is: from "User paused protocol for xx:xx:xx" to "Protocol paused for xx:xx:xx" as seen here in Figma: https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=1297%3A101653

Comment (emilywools) [reply app/src/organisms/Devices/ProtocolRun/StepItem.tsx]: sounds good to me :)

**Review by b-cooper — APPROVED** [review]
©️ 🪙
