### PR TITLE
fix(app): protocol Run Record protocolName no longer renders runId

### LINKED ISSUE #10658: 6.0 Feedback: device detail page loading process
### Overview

Much of the information on the device detail page changes as it is loaded for the first time (or when reloading the page). It flashes warnings that can be distracting or concerning to users. Some information remains inaccurate even after everything is loaded.

### Current Behavior

These sections show incorrect information as they load:

1. Pipettes
     - [ ] Pipette images do not show initially (going be addressed in a follow up ticket: https://github.com/Opentrons/opentrons/issues/10847) 
     - [x] "Pipette Offset calibration missing. Calibrate deck first." warning shows very briefly
     - [x] "Pipette Offset calibration needed. Calibrate now" shows slightly longer
2. Protocol runs
    - [x] Entries in the Protocol column initially appear as hex identifiers, and only later update to display names.

These sections show incorrect information even after load:
- [ ] Protocol run status shows as "Canceled" for all runs prior to 6.0.0-alpha1
- [ ] Protocol run duration shows as time between protocol timestamp and present time, instead of between protocol start and end (this will be addressed in this ticket: https://github.com/Opentrons/opentrons/issues/10738) 

https://user-images.githubusercontent.com/1958332/172464999-46c2bf77-3cd4-4817-86d1-04f94f5a19d5.mov

### Expected Behavior

- Pipette images should display at same time as pipette names
- Pipette warnings should never show in a state when they are not needed
- Protocol hex identifiers should never be shown instead of names
- Run durations should be accurate

### Steps To Reproduce

Connect to a robot and navigate to its page under Devices. The above behavior happens on first load or when manually triggering a reload from the View menu.

### Operating system

Mac

### Robot setup or anything else?

_No response_

### LINKED ISSUE #10899: 6.0 Feedback: Protocol record id shown as protocol name when 2nd app is connected
### Overview

_No response_

### Current Behavior

When Opentrons app is opened on another device, and a user navigates to device details page the protocol name displays as protocol record id for about ~1 min

Screen Shot 2022-06-23 at 11 46 33 AM

We should never display the protocol record id to the user 

### Expected Behavior

Protocol name shows in protocol column 

We have a few ways we can do this: 

1. Not show anything in that column until the protocol name is loaded
2. Show a spinner until protocol name is loaded 

### Steps To Reproduce

_No response_

### Operating system

Mac

### Robot setup or anything else?

_No response_

### PR DESCRIPTION
**Pull request by jerader**
closes #10899 closes #10658

# Overview

This fixes the bug where the `runid` renders in the protocol name section. Now, if `protocolName` and protocol file are still rendering, `Loading...` will be in place

# Changelog

- change `RecentProtocolRun` and test
- remove unnecessary fetching that I previously added because I thought it fixed this bug

# Review requests

- run a few protocols to get a protocol run record. Refresh the app, the protocol name should say "Loading..." instead of `runId`

# Risk assessment

low

### CODE REVIEW

File: app/src/organisms/Devices/RecentProtocolRuns.tsx [hunk 1]
```diff
@@ -33,25 +27,14 @@ interface RecentProtocolRunsProps {
 export function RecentProtocolRuns({
   robotName,
 }: RecentProtocolRunsProps): JSX.Element | null {
-  const { t } = useTranslation('device_details')
+  const { t } = useTranslation(['device_details', 'shared'])
   const isRobotViewable = useIsRobotViewable(robotName)
-  const [dispatchRequest, requestIds] = useDispatchApiRequest()
```
Comment (jerader) [inline app/src/organisms/Devices/RecentProtocolRuns.tsx:38]: I previously added this `useDispatchApiRequest` to fetch protocols when I initially tackled ticket 10658. I thought it fixed the bug but it didn't. So deleting it now.

**Review by vabruzzo — APPROVED** [review]
code changes lgtm :+1:
