### PR TITLE
fix(app): fix devices landing page text wrapping

### LINKED ISSUE #10886: 6.0 Feedback: [Design QA] Devices Landing page - don't wrap text in pipette mount  labeled values
This came from #10809
#10809 will be closed when this issue is closed by a PR.

(5) Can these columns not go onto 2 lines unless the screen size is very small? There's space on the card still for it to be on one line

175107211-f6e3e541-3170-496f-a55b-96beec000100

### PR DESCRIPTION
**Pull request by koji**
# Overview
This will fix #10886.

The current implementation is based on 👇
IMG_0379

Screen Shot 2022-07-12 at 4 22 59 PM

https://user-images.githubusercontent.com/474225/178589606-e2c4e3dc-ef11-4543-b2bd-6a9ad2de6e73.mov

# Changelog
- Switch to grid from flex box for pipettes and modules

# Review requests
- The app never wraps the pipettes name 
- When pipettes and modules are aligned vertically, the order is LEFT`, `RIGHT`, `MODULES`

# Risk assessment
low

### CODE REVIEW

File: app/src/organisms/ProtocolsLanding/ProtocolCard.tsx [hunk 1]
```diff
@@ -147,7 +147,7 @@ function AnalysisInfo(props: AnalysisInfoProps): JSX.Element {
         height="auto"
         justifyContent={JUSTIFY_CENTER}
         alignItems={
-          getElementProperty('height') <= 880 ? ALIGN_START : ALIGN_CENTER
+          getElementProperty('width') <= 800 ? ALIGN_START : ALIGN_CENTER
```
Comment (koji) [inline app/src/organisms/ProtocolsLanding/ProtocolCard.tsx]: This should be `width` instead of `height`.

File: app/src/organisms/Devices/RobotCard.tsx [hunk 2]
```diff
@@ -45,6 +46,8 @@ const ROBOT_CARD_STYLE = css`
   }
 `
 
+const ROBOT_CARD_WRAP_SIZE = 650
```
Comment (koji) [inline app/src/organisms/Devices/RobotCard.tsx:49]: I requested Mel to check this value is reasonable to wrap elements and got confirmed.

File: app/src/organisms/Devices/RobotCard.tsx [hunk 3]
```diff
@@ -156,23 +181,30 @@ function AttachedModules(props: { robotName: string }): JSX.Element | null {
...
   return (
-    <Flex flexDirection={DIRECTION_ROW} width="100%">
-      <Flex
-        flex="1"
-        flexDirection={DIRECTION_COLUMN}
-        paddingRight={SPACING.spacing4}
-        width="100%"
-      >
+    <Box
+      // ref={pipetteRef}
```
Comment (jerader) [inline app/src/organisms/Devices/RobotCard.tsx]: I think this is a stray`ref`

File: app/src/organisms/Devices/RobotCard.tsx [hunk 4]
```diff
@@ -54,6 +57,21 @@ export function RobotCard(props: RobotCardProps): JSX.Element | null {
...
+  const [robotCardWidth, setRobotCardWidth] = React.useState<number>(
+    getElementProperty('width')
+  )
+
+  React.useEffect(() => {
+    const handleResize = (): void => {
+      setRobotCardWidth(getElementProperty('width'))
+    }
+    window.addEventListener('resize', handleResize)
+  })
```
Comment (jerader) [inline app/src/organisms/Devices/RobotCard.tsx]: This is cool and works as expected. I've never used this approach before.

**Review by jerader — APPROVED** [review]
lgtm and works as expected

File: app/src/organisms/Devices/RobotCard.tsx (hunk 3 above)
Comment (koji) [reply app/src/organisms/Devices/RobotCard.tsx]: Thanks, I forgot to push the latest code.

**Comment by koji** [comment]
- [x] fix a bug
1. Device details page
2. Clicking Device
The device card layout is different from the previous layout

**Review by brenthagen — APPROVED** [review]
i feel like we should revisit our grid/breakpoint approach eventually, but as long as we're careful about use of useEffect and clean up event listeners, i think this is ok
