### PR TITLE
fix(app): Address labware landing page design feedback

### LINKED ISSUE #10905: 6.0 Feedback: [Design QA] T1 Labware Page
### Overview

**This is not a complete design QA for T1 Labware Page. Due to time constraints, this is top-level, must be done for 6.0 feedback.**

### Current Behavior

_No response_

### Expected Behavior

[Link to annotated frame in figma ](https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=14699%3A291257)

- [x] (1) Remove the white fill on the secondary button component 
- [x] (2) Fix placement of the open menu. Should be 4px below and aligned to the right of the button that opened it
- [x] (3) Fix the states on this button. Currently the enabled is showing as hover. 
- [ ] (4) Increase the width of this input field. No two lines when it's on 'Aluminum block'!
- [x] (5) **This is super important. Align the icon with the text, currently the icon is a few pixels high
- [x] (6) Remove upper case, should be "Custom Definition" and "Opentrons Definition". Make sure they're both the right colour, needs to be grey 
- [x] (7) Missing hover state on this icon
- [ ] (8) **Super important. Fix the placement of this icon. Needs to be 4px from top and right. Check out our other designs for reference. 
- [x] (9) ** super important. Need hover state on the card 
- [x] (10) Push onto 1 line, no wrapping here
- [x] (11) Menu overflow button stays active after the user closes the menu. [Loom video](https://www.loom.com/share/7ab0659f042445afa106de7615683154)
- [ ] (12) Wrap this text when the app gets resized. Keep padding too at the bottom (see arrow) 
- [x] (13) update the blue icon (Got confirmation from Mel)
- [x]  (14) update the icon on protocol slideout
- [ ] (15) Re-organize Flex

Screen Shot 2022-06-24 at 11 44 02 AM

### Steps To Reproduce

_No response_

### Operating system

_No response_

### Robot setup or anything else?

_No response_

### PR DESCRIPTION
**Pull request by koji**
# Overview
This will fix #10905 
I added one more col to the Design System Responsive breakdown since custom labware needs `overflowMenu button` and added date and their positions are a little bit different from the rest of the contents.

https://www.figma.com/file/l7BAJAGICr10ELsSqQD0Sr?node-id=1974:81641#219999570

# Changelog
- update the icon (opentrons definition)
- update labware card styling
- update labware page's component style
  - DropdwonMenu
  - sortBy menu state

# Review requests
- [ ] when resizing the app window(width 600px), the app shows svg and category name(no-wrap) and wrapping api name
- [ ] sortBy menu state aligns with the Design system (Design system - Button Icons)
- [ ] the blue optrons definition icon is updated

# Risk assessment
low

### CODE REVIEW

File: app/src/organisms/LabwareCard/index.tsx [hunk 1]
```diff
@@ -42,29 +66,38 @@ export function LabwareCard(props: LabwareCardProps): JSX.Element {
     await navigator.clipboard.writeText(apiName)
   }
 
+  console.log(
```
Comment (vabruzzo) [inline app/src/organisms/LabwareCard/index.tsx]: Probably forgot to remove?

Comment (koji) [reply app/src/organisms/LabwareCard/index.tsx]: thank you!

File: components/src/ui-style-constants/borders.ts [hunk 2]
```diff
@@ -19,6 +19,9 @@ export const cardOutlineBorder = css`
   border-width: ${spacingXXS};
   border-color: ${medGrey};
   border-radius: ${radiusSoftCorners};
+  &:hover {
+    border: 1px solid ${medGreyHover};
```
Comment (brenthagen) [inline components/src/ui-style-constants/borders.ts]: this can just be `border-color`, the other properties stay the same

File: app/src/pages/Labware/index.tsx [hunk 3]
```diff
@@ -81,6 +94,9 @@ export function Labware(): JSX.Element {
     currentLabwareDef,
     setCurrentLabwareDef,
   ] = React.useState<null | LabwareDefAndDate>(null)
+  const sortOverflowWrapperRef = useOnClickOutside({
+    onClickOutside: () => setShowSortByMenu(false),
+  }) as React.RefObject<HTMLDivElement>
```
Comment (brenthagen) [inline app/src/pages/Labware/index.tsx]: better to use a generic than a type assertion:

```  
const sortOverflowWrapperRef = useOnClickOutside<HTMLDivElement>({
  onClickOutside: () => setShowSortByMenu(false),
})
```

File: app/src/atoms/MenuList/DropdownMenu.tsx [hunk 4]
```diff
@@ -41,11 +41,12 @@ export function DropdownMenu(props: DropdownMenuProps): JSX.Element {
...
         alignItems={ALIGN_CENTER}
         justifyContent={JUSTIFY_SPACE_BETWEEN}
-        width="8rem"
+        width="9.125rem"
         onClick={toggleSetShowDropdownMenu}
         border={BORDERS.lineBorder}
         borderRadius={BORDERS.radiusRoundEdge}
-        padding={SPACING.spacing3}
+        padding={`
+          ${SPACING.spacing3} ${SPACING.spacing3} ${SPACING.spacing3} 0.75rem`} // temp
```
Comment (jerader) [inline app/src/atoms/MenuList/DropdownMenu.tsx]: this `temp` comment is vague?

**Review by jerader — APPROVED** [review]
Lgtm. just noticed something about the Category overflow menu: 

https://user-images.githubusercontent.com/66035149/177397621-b254ed99-16ac-4d5a-af9e-7ee6b3742241.mov

File: app/src/atoms/MenuList/DropdownMenu.tsx (hunk 4 above)
Comment (koji) [reply app/src/atoms/MenuList/DropdownMenu.tsx]: Thank you. 
I asked about this to Mel last week. Seems that I forgot to update this.
This padding should be 8px (`{SPACING.spacing3}`)

File: app/src/organisms/LabwareCard/index.tsx [hunk 5]
```diff
@@ -13,17 +15,39 @@ import {
...
+  position: ${POSITION_RELATIVE};
+  top: ${SPACING.spacing1};
+  left: ${SPACING.spacing2};
+
+  &:hover {
+    color: ${COLORS.black};
+  }
+`
+
+const LabwareInfoWrapper = styled.div`
```
Comment (brenthagen) [inline app/src/organisms/LabwareCard/index.tsx]: probably don't need this as a separate styled component - `gridTemplateColumns` can be a primitive style prop on a `Box`

File: app/src/organisms/LabwareCard/index.tsx [hunk 6]
```diff
@@ -108,35 +145,54 @@ export function LabwareCard(props: LabwareCardProps): JSX.Element {
                 onClick={handleCopyClick}
                 role="button"
               >
-                <Flex alignItems={ALIGN_CENTER}>
-                  {apiName}{' '}
+                <Box css={{ 'overflow-wrap': 'anywhere' }}>
```
Comment (brenthagen) [inline app/src/organisms/LabwareCard/index.tsx]: could add `overflowWrap` as a primitive style prop

File: app/src/organisms/LabwareCard/CustomLabwareOverflowMenu.tsx [hunk 7]
```diff
@@ -96,7 +104,7 @@ export function CustomLabwareOverflowMenu(
       {showOverflowMenu && (
         <Flex
           ref={overflowMenuRef}
-          width="10rem"
+          width="11rem"
```
Comment (brenthagen) [inline app/src/organisms/LabwareCard/CustomLabwareOverflowMenu.tsx]: is `whiteSpace: nowrap` a good option here instead of a fixed width?

File: app/src/organisms/LabwareCard/CustomLabwareOverflowMenu.tsx [hunk 8]
```diff
@@ -16,37 +16,41 @@ import {
...
   props: CustomLabwareOverflowMenuProps
 ): JSX.Element {
-  const { filename, onDelete } = props
+  const { filename, onDelete, ...styleProps } = props
   const { t } = useTranslation(['labware_landing', 'shared'])
   const dispatch = useDispatch<Dispatch>()
   const [showOverflowMenu, setShowOverflowMenu] = React.useState<boolean>(false)
-  const overflowMenuRef = React.useRef(null)
-  useCloseOnOutsideClick(overflowMenuRef, () => setShowOverflowMenu(false))
+  const overflowMenuRef = useOnClickOutside({
```
Comment (brenthagen) [inline app/src/organisms/LabwareCard/CustomLabwareOverflowMenu.tsx]: same as previous comment, `useOnClickOutside<HTMLDivElement>`

File: app/src/organisms/LabwareCard/CustomLabwareOverflowMenu.tsx [hunk 9]
```diff
@@ -16,37 +16,41 @@ import {
...
   openCustomLabwareDirectory,
 } from '../../redux/custom-labware'
+
+import type { StyleProps } from '@opentrons/components'
 import type { Dispatch } from '../../redux/types'
 
 const LABWARE_CREATOR_HREF = 'https://labware.opentrons.com/create/'
 
-interface CustomLabwareOverflowMenuProps {
+interface CustomLabwareOverflowMenuProps extends StyleProps {
```
Comment (brenthagen) [inline app/src/organisms/LabwareCard/CustomLabwareOverflowMenu.tsx]: why extend style props for this component?

**Review by brenthagen — COMMENTED** [review]
also, "Open Labware Creator" could use font weight 600 and spacing before the icon
Screen Shot 2022-07-05 at 3 17 33 PM
:

File: app/src/organisms/LabwareCard/CustomLabwareOverflowMenu.tsx (hunk 9 above)
Comment (koji) [reply app/src/organisms/LabwareCard/CustomLabwareOverflowMenu.tsx]: I think at some point I passed style props but I could find another implementation and forgot to remove this.

**Comment by koji** [comment]
https://user-images.githubusercontent.com/474225/177414007-fa85e702-ff95-423f-bbda-6b74ad10cd1c.mov


Screen Shot 2022-07-05 at 4 04 23 PM

**Comment by koji** [comment]
- [x] sort by text should not be clickable
- [x] add `cursor: pointer` to the sort by button

File: components/src/primitives/style-props.ts [hunk 10]
```diff
@@ -55,6 +55,7 @@ const FLEXBOX_PROPS = [
   'flexDirection',
   'flexWrap',
   'alignSelf',
+  'whiteSpace',
```
Comment (brenthagen) [inline components/src/primitives/style-props.ts:58]: `whiteSpace` already exists in line 81 (does need to be added to types)

File: app/src/organisms/LabwareCard/CustomLabwareOverflowMenu.tsx [hunk 11]
```diff
@@ -41,12 +43,13 @@ interface CustomLabwareOverflowMenuProps {
 export function CustomLabwareOverflowMenu(
   props: CustomLabwareOverflowMenuProps
 ): JSX.Element {
-  const { filename, onDelete } = props
+  const { filename, onDelete, ...styleProps } = props
```
Comment (brenthagen) [inline app/src/organisms/LabwareCard/CustomLabwareOverflowMenu.tsx]: `styleProps` should be removed

File: app/src/organisms/LabwareCard/CustomLabwareOverflowMenu.tsx [hunk 12]
```diff
@@ -87,7 +90,11 @@ export function CustomLabwareOverflowMenu(
   }
 
   return (
-    <Flex flexDirection={DIRECTION_COLUMN} position={POSITION_RELATIVE}>
+    <Flex
+      flexDirection={DIRECTION_COLUMN}
+      position={POSITION_RELATIVE}
+      {...styleProps}
```
Comment (brenthagen) [inline app/src/organisms/LabwareCard/CustomLabwareOverflowMenu.tsx]: `styleProps` should be removed

**Review by brenthagen — APPROVED** [review]
✨

File: components/src/primitives/style-props.ts (hunk 10 above)
Comment (koji) [reply components/src/primitives/style-props.ts:58]: needed to remove type errors on vs code.
