### PR TITLE
fix(app): fix toast display issue on RobotSettings Advanced tab

### LINKED ISSUE #10624: bug: RobotSettings Advanced download logs Toast shows up over and over
# Overview
Download logs Toast on RobotSettings Advanced shows up over and over

# Steps to reproduce

# Current behavior
The toast shows up over and over

# Expected behavior
The toast shows up only once and stick until finish the download

### PR DESCRIPTION
**Pull request by koji**
# Overview
This PR fixes the following.
1. The Downloading logs Toast display issue
Currently, the toast shows up over and over since this toast passes the wrong prop value to the Toast component
2.  `requiredTimeout` issue
`requiredTimeout` is to deactivate default `setTimeout` but the current implementation would make devs confused.
Because `requiredTimeout={true}` deactivate setTimeout and the prop name is inappropriate.

Close #10624

https://user-images.githubusercontent.com/474225/172207790-7e61ac71-1fde-48ce-b471-158d3f74ddf9.mov

# Changelog
- Chage Toast `requiredTimeout` to `disableTimeout`
- Update passed value of the RobotSettings Advanced tab
- Update DownloadRunLogToast prop name
- Update Toast test cases (add an explicit, `disabledTimeout={false}`)

# Review requests
- Downloading Toast stays until the end of downloading logs
Step1. Click `Devises` Tab
Step2. Click the overflow menu on a device and click `RobotSettings`
Step3. Click `Advanced` Tab
Step4. Click `Download logs` button

# Risk assessment
low

### CODE REVIEW

File: app/src/atoms/Toast/index.tsx [hunk 1]
```diff
@@ -71,9 +71,9 @@ const toastStyleByType: {
 }
 
 export function Toast(props: ToastProps): JSX.Element {
-  const { message, type, icon, closeButton, onClose, requiredTimeout } = props
+  const { message, type, icon, closeButton, onClose, disableTimeout } = props
 
-  if (!(requiredTimeout ?? false)) {
+  if (!disableTimeout || disableTimeout == null) {
```
Comment (koji) [inline app/src/atoms/Toast/index.tsx]: disabledTimeout: true -> no setTimeout (This option is for downloading a log)
disabledTimeout: false | undefined | null -> Toast will disappear automatically

Comment (vabruzzo) [reply app/src/atoms/Toast/index.tsx]: small comment/question, for cases like this rather than checking for undefined/null, would it be clearer if we set the default argument to false? I don't think we'd ever actually pass null, and if we pass nothing it will default to false so we wouldn't need to check for undefined. i'm not sure if that is consistent with our practices elsewhere but default arguments often make intent clearer in my experience

**Review by vabruzzo — APPROVED** [review]
looks good to me, left a small style question/comment

File: app/src/atoms/Toast/index.tsx (hunk 1 above)
Comment (koji) [reply app/src/atoms/Toast/index.tsx]: Sounds good! Thank you for your suggestion!
