### PR TITLE
fix(app): fix ProtocolRunningContent remounting issue

### LINKED ISSUE #10956: ProtocolRunningContent component remounts every few seconds
The `ProtocolRunningContent` inside the `ProtocolRunHeader` keeps remounting every few seconds. This causes the cancel run button to be unresponsive about 1 out of every 3 or 4 clicks. It may be causing other UI/performance issues. This is happening on `edge` and `release_6.0.0`

To reproduce create a run. This video shows the component log each time it mounts or unmounts:

https://images.zenhubusercontent.com/38644841/5cc40699-21da-499d-af80-cff211c8e3a2/screen_recording_2022_06_30_at_9_16_45_am.mov

### PR DESCRIPTION
**Pull request by vabruzzo**
# Overview
We were creating a new child component inside ProtocolRunHeader on each render of ProtocolRunHeader, we don't want to do that since that nested component will mount and unmount on every render of the parent component. Instead, if we want to break up the JSX we should either create an entirely new component outside of the component that we are refactoring or if we want to assign something to a variable from inside the parent component, it should be a `ReactNode`, which is the type that the render function returns, so it can be null, some JSX, a string, etc. 

Edit: I 'm used to defaulting to React.Node but we use JSX.Element so im sticking with that. the important thing is that we arent creating Components that return this type.

Closes #10956

# Changelog
- `ProtocolRunHeader` no longer creates new components on every render, it creates some `ReactNode`'s. This fixes the mounting/unmounting bug.

# Review requests
Check that the UI in the ProtocolRunHeader is no longer remounting over and over.

# Risk assessment
Low

### CODE REVIEW

File: app/src/organisms/Devices/ProtocolRun/ProtocolRunHeader.tsx [hunk 1]
```diff
@@ -370,31 +370,33 @@ export function ProtocolRunHeader({
...
-      case RUN_STATUS_SUCCEEDED: {
-        return (
-          <Banner type="success" onCloseClick={handleClearClick}>
-            <Flex justifyContent={JUSTIFY_SPACE_BETWEEN} width="100%">
-              {`${t('run_completed')}.`}
-            </Flex>
-          </Banner>
-        )
-      }
+  let ClearProtocolBanner: React.ReactNode
```
Comment (vabruzzo) [inline app/src/organisms/Devices/ProtocolRun/ProtocolRunHeader.tsx]: i think we can keep the type here as `JSX.Element | null`. what we dont want is to return a function that returns one of those things

Comment (brenthagen) [inline app/src/organisms/Devices/ProtocolRun/ProtocolRunHeader.tsx]: should the nodes still be capitalized?

**Review by brenthagen — APPROVED** [review]
thanks for finding this - another example of this remounting behavior is in `RobotStatusBanner`

File: app/src/organisms/Devices/ProtocolRun/ProtocolRunHeader.tsx (hunk 1 above)
Comment (vabruzzo) [reply app/src/organisms/Devices/ProtocolRun/ProtocolRunHeader.tsx]: good question. I don't think it affects anything, it might be better to lowercase these to make it clear. good call

**Review by b-cooper — APPROVED** [review]
🎏
