### PR TITLE
fix(app): fix historical protocol run overflow menu bugs

### LINKED ISSUE #10404: 6.0 Feedback: Should "run a protocol" CTA be consistent throughout the experience?
### Overview

In some places the button to run a protocol says "run protocol" and in others it says "run a protocol"

do we need to be consistent? i think we are inconsistent because saying "run a protocol" on a protocol detail page sounds odd. But should we say "run protocol" everywhere?

cc @ecormany 

### Current Behavior

_No response_

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Operating system

_No response_

### Robot setup or anything else?

_No response_

### PR DESCRIPTION
**Pull request by jerader**
closes #10404 #10545 #10548

# Overview

This PR addresses multiple bugs and a quick UI change:
1. only 1 overflow menu opens at a time in historical run protocols
2. the historical run record deletes immediately when you select "delete protocol run record"
3. all "run protocol" CTAs are changed to "run a protocol"

# Changelog

- a quick copy change to `RobotOverview`
- change in `HistoricalProtocolRunOverflowMenu`
- create test file for `HistoricalProtocolRunOverflowMenu`

# Review requests

- in the Historical protocol run section: click on a kebab and open an overflow menu. Click on another kebab, the 1st overflow menu should close
- in the Historical protocol run, open an overflow menu, click on "delete protocol run record". The run should delete immediately.

# Risk assessment

low

### CODE REVIEW

File: app/src/organisms/Devices/HistoricalProtocolRunOverflowMenu.tsx [hunk 1]
```diff
@@ -104,6 +113,13 @@ function MenuDropdown(props: MenuDropdownProps): JSX.Element {
   }
   const { reset } = useRunControls(runId, onResetSuccess)
   const { deleteRun } = useDeleteRunMutation()
+
+  React.useEffect(() => {
+    if (runId !== null) {
+      deleteRun(runId)
```
Comment (b-cooper) [inline app/src/organisms/Devices/HistoricalProtocolRunOverflowMenu.tsx]: what is this useEffect's intention?  This seems like it will always delete a run when the overflow menu is open.

Comment (jerader) [reply app/src/organisms/Devices/HistoricalProtocolRunOverflowMenu.tsx]: oh yeah, you're right. Thanks for catching that. This addition was to address the bug outlined in ticket 10454. I'll look into another workaround.

File: app/src/assets/localization/en/protocol_details.json [hunk 2]
```diff
@@ -21,7 +21,7 @@
   "robot_configuration": "robot configuration",
   "robot_is_busy": "{{robotName}} is busy",
   "robot_is_busy_with_protocol": "{{robotName}} is busy with {{protocolName}} in {{runStatus}} state. Do you want to clear it and proceed?",
-  "run_protocol": "Run protocol",
+  "run_a_protocol": "Run a protocol",
```
Comment (koji) [inline app/src/assets/localization/en/protocol_details.json]: We don't need to add a to the protocol details page.
Please see check the thread on app-ui team channel.

File: app/src/organisms/Devices/HistoricalProtocolRunOverflowMenu.tsx [hunk 3]
```diff
@@ -58,11 +62,16 @@ export function HistoricalProtocolRunOverflowMenu(
...
       <OverflowBtn alignSelf={ALIGN_FLEX_END} onClick={handleOverflowClick} />
       {showOverflowMenu && (
-        <MenuDropdown
-          {...props}
-          closeOverflowMenu={handleOverflowClick}
-          setShowDownloadRunLogToast={setShowDownloadRunLogToast}
-        />
+        <div
+          ref={protocolRunOverflowWrapperRef}
+          data-testid={`HistoricalProtoclRunOverflowMenu_${runId}`}
```
Comment (koji) [inline app/src/organisms/Devices/HistoricalProtocolRunOverflowMenu.tsx]:
```suggestion
          data-testid={`HistoricalProtocolRunOverflowMenu_${runId}`}
```

**Review by koji — CHANGES_REQUESTED** [review]
I don't see any weird parts in changes but when clicking the overflow menu button, the app deletes protocol runs. Could you check this? (Maybe my env issue?)

Also, there is one weird thing that #10545 doesn't occur on my end with `edge`. 
But I think using `useClickOutside()` would be good.

https://user-images.githubusercontent.com/474225/171883781-0afd6b83-420d-442c-8ebf-3865ea892230.mov

**Comment by jerader** [comment]
> I don't see any weird parts in changes but when clicking the overflow menu button, the app deletes protocol runs. Could you check this? (Maybe my env issue?)

@koji I think this is what Brian mentioned in my comment, it was introduced by the `useEffect` that I added. I am deleting it now. It seems that the bug outlined in ticket 10545 that I thought i was fixing by adding `useEffect`, isn't actually a bug.

File: app/src/assets/localization/en/protocol_details.json (hunk 2 above)
Comment (jerader) [reply app/src/assets/localization/en/protocol_details.json]: Yup just saw the thread, thank you!

**Review by koji — CHANGES_REQUESTED** [review]
Seem that #10404 and #10548 have been solved by PR but still, #10545 isn't solved.

https://user-images.githubusercontent.com/474225/172221201-783c64ed-c0ce-473f-9047-52b1491eedc5.mov

File: app/src/organisms/Devices/HistoricalProtocolRunOverflowMenu.tsx [hunk 4]
```diff
@@ -115,29 +125,30 @@ function MenuDropdown(props: MenuDropdownProps): JSX.Element {
...
       <MenuItem
-        dataTest-id={`RecentProtocolRun_OverflowMenu_downloadRunLog`}
+        data-testid={`RecentProtocolRun_OverflowMenu_downloadRunLog`}
         onClick={onDownloadClick}
       >
         {t('download_run_log')}
       </MenuItem>
       <Divider />
       <MenuItem
         onClick={() => deleteRun(runId)}
```
Comment (koji) [inline app/src/organisms/Devices/HistoricalProtocolRunOverflowMenu.tsx]: In my understanding, we need to call `closeOverflowMenu(e)` after deleting run logs. Seems that re-run also has the same issue.

Comment (koji) [reply app/src/organisms/Devices/HistoricalProtocolRunOverflowMenu.tsx]: Probably something like this.

```typescript
const handleDeleteRunClick: React.MouseEventHandler<HTMLButtonElement> = e => {
    deleteRun(runId)
    closeOverflowMenu(e)
}

onClick={handleDeleteRunClick}
```

**Review by koji — APPROVED** [review]
🧹 looks good to me and works as expected (after clicking `Delete protocol run record`, the overflow menu is closed)

**Comment by y3rsh** [comment]
verified fixed
