### PR TITLE
fix(app): restrict size of reset config modal

### LINKED ISSUE #7157: bug: Not able to Factory Reset using opentrons app 4.0.
# Overview

It is not possible to do factory reset in App 4.0 because the bottom is not accessible. 
# Steps to reproduce

Click Reset botton
# Current behavior
no bottons availeble

# Expected behavior
botton availeble
screen

### PR DESCRIPTION
**Pull request by Laura-Danielle**
# Overview

closes #7157. Restrict the size of the modal to avoid the contents of the modal box from spilling over when shrinking the app screen. Please note that it doesn't fully resolve the problem, only makes it slightly better. The main fix would be to refactor the `AlertModal` component to somehow force the actual modal to be the parent of its contents as opposed to the overlay screen.

Would love input here which is why I'm making this a draft PR.

Screen Shot 2021-01-11 at 4 37 23 PM

# Changelog

- Restrict size of alert modal
- Pull buttons out into a flex box

# Review requests

Are there better small adjustments I can make outside of refactoring all of the alert modals? Should I just refactor all of the alert modals? (side note, scared about doing that).

# Risk assessment

Low, just adjusting one modal.

### CODE REVIEW

File: app/src/components/RobotSettings/ResetRobotModal.js [hunk 1]
```diff
@@ -65,25 +77,41 @@ export function ResetRobotModal(props: ResetRobotModalProps): React.Node {
...
-            }}
-            name={o.id}
-            value={resetOptions[o.id]}
-            key={o.id}
-          >
-            <p>{o.description}</p>
-          </LabeledCheckbox>
-        ))}
+        <Flex maxHeight={SIZE_5} flexDirection={DIRECTION_COLUMN}>
+          <Box overflow={OVERFLOW_SCROLL}>
```
Comment (mcous) [inline app/src/components/RobotSettings/ResetRobotModal.js]: Setting `overflow: scroll` means that scroll bars (both vertical and horizontal) will _always_ show. Here, we'd be looking for `overflow-y: auto`, which has some weird rules about how, exactly, to get scroll bars to show when they're needed

**Review by mcous — COMMENTED** [review]
This whole "scrolling modal" problem came up during some recent app update modal work. As such, we added [`<BaseModal>`](https://s3-us-west-2.amazonaws.com/opentrons-components/edge/index.html#basemodal) to the components library, which has automatic scroll behavior figured out and integrated by default.


The downside is that it's fairly low level. You can see this in [`<UpdateAppModal>`](https://github.com/Opentrons/opentrons/blob/edge/app/src/components/app-settings/UpdateAppModal.js), which uses BaseModal to have a scrollable AlertModal. That being said, in terms of looks, it's _way_ better than `<ScrollableAlertModal>`

File: app/src/components/RobotSettings/ResetRobotModal.js [hunk 2]
```diff
@@ -65,26 +82,57 @@ export function ResetRobotModal(props: ResetRobotModalProps): React.Node {
...
+            fontSize={FONT_SIZE_HEADER}
+            fontWeight={FONT_WEIGHT_REGULAR}
+          >
+            <Icon name="alert" width="2rem" marginRight={SPACING_2} />
+            {TITLE}
+          </Text>
+        }
+        footer={
+          <Flex justifyContent={JUSTIFY_FLEX_END}>
+            {buttons.filter(Boolean).map((button, index) => (
```
Comment (mcous) [inline app/src/components/RobotSettings/ResetRobotModal.js]: It doesn't look like `const buttons` is doing anything (nor does it have any falsey values, so the `filter` isn't needed), so mapping over a variable might be a little less clear than just unrolling the loop and using the components directly

File: app/src/components/RobotSettings/ResetRobotModal.js [hunk 3]
```diff
@@ -65,26 +82,57 @@ export function ResetRobotModal(props: ResetRobotModalProps): React.Node {
...
+              <OutlineButton
```
Comment (mcous) [inline app/src/components/RobotSettings/ResetRobotModal.js]: Prefer `SecondaryBtn`, with style props, to `OutlineButton`

File: app/src/components/RobotSettings/styles.css [hunk 4]
```diff
@@ -92,3 +92,7 @@
 .confirm_start_deck_cal_modal {
   padding: 4rem 2rem;
 }
+
+.alert_modal_button {
```
Comment (mcous) [inline app/src/components/RobotSettings/styles.css]: This CSS is unnecessary if you use `SecondaryBtn`

File: app/src/components/RobotSettings/ResetRobotModal.js [hunk 5]
```diff
@@ -65,26 +82,57 @@ export function ResetRobotModal(props: ResetRobotModalProps): React.Node {
...
+      <BaseModal
+        header={
+          <Text
+            as="h2"
+            display={DISPLAY_FLEX}
+            alignItems={ALIGN_CENTER}
+            fontSize={FONT_SIZE_HEADER}
+            fontWeight={FONT_WEIGHT_REGULAR}
+          >
+            <Icon name="alert" width="2rem" marginRight={SPACING_2} />
```
Comment (mcous) [inline app/src/components/RobotSettings/ResetRobotModal.js]: I _think_ `2rem` is `SIZE_2`, right?

Comment (Laura-Danielle) [reply app/src/components/RobotSettings/ResetRobotModal.js]: yep you're right!

**Review by b-cooper — APPROVED** [review]
Looks like a good spot fix to me! A widely shared Alert Modal component my be right on the divide where a common abstraction is bound to present more trouble than it avoids. Because of the many ways we use the `AlertModal` component across our applications, making any change to address situational weirdnesses almost always leads to unexpected consequences.

File: app/src/components/RobotSettings/ResetRobotModal.js [hunk 6]
```diff
@@ -54,37 +70,66 @@ export function ResetRobotModal(props: ResetRobotModalProps): React.Node {
...
-            name={o.id}
-            value={resetOptions[o.id]}
-            key={o.id}
-          >
-            <p>{o.description}</p>
-          </LabeledCheckbox>
-        ))}
-      </AlertModal>
+        <Flex flexDirection={DIRECTION_COLUMN}>
+          <Box>
```
Comment (mcous) [inline app/src/components/RobotSettings/ResetRobotModal.js]: I suspect that either this `<Flex>` or `<Box>` (or possibly both) is unnecessary. This looks like it will render as:

```
<div>  # Flex
    <div>  # Box
        <LabeledCheckbox ... />
        <LabeledCheckbox ... />
        ...
    </div>
</div>
```

`flex-direction: column` probably isn't doing anything because the `<Flex>` has only one child: the `<Box>`

**Review by mcous — APPROVED** [review]
