### PR TITLE
feat(protocol-designer): fix batch edit step count bug

### LINKED ISSUE #7509: bug: PD - incorrect step count displayed
Generate the error "Not enough tips to complete action"
And enter into the batch edit mode, number of steps shown is increased by 1

### PR DESCRIPTION
**Pull request by shlokamin**
# Overview

Closes #7509

If you are in single select mode and have a step selected, lets call it `Step 1` , and then you enter batch edit mode by cmd+ clicking that very same step (`Step 1`), you will enter batch edit mode with the selected steps being `[Step 1, Step 1]`. 

# Review requests
Make sure bug is fixed and stepcount isn't broken

# Risk assessment
Low

### CODE REVIEW

File: protocol-designer/src/containers/ConnectedStepItem.js [hunk 1]
```diff
@@ -246,7 +246,8 @@ function getMetaSelectedSteps(multiSelectItemIds, stepId, selectedStepId) {
       ? multiSelectItemIds.filter(id => id !== stepId)
       : [...multiSelectItemIds, stepId]
   } else if (selectedStepId) {
-    stepsToSelect = [selectedStepId, stepId]
+    stepsToSelect =
+      selectedStepId === stepId ? [selectedStepId] : [selectedStepId, stepId]
```
Comment (shlokamin) [inline protocol-designer/src/containers/ConnectedStepItem.js]: decided to do this here rather than in the reducer/selector bcuz it seems like it's the responsibility of the component to determine which steps to select.

Comment (IanLondon) [reply protocol-designer/src/containers/ConnectedStepItem.js]: would it be easier to read if we changed the ternary to an `if`? I tried to comment about the cases bc I'm not sure if I understood this fn correctly

```js
function getMetaSelectedSteps(multiSelectItemIds, stepId, selectedStepId) {
  let stepsToSelect: Array<StepIdType> = []
  if (multiSelectItemIds?.length) {
    // already have a selection, add/remove the meta-clicked item
    stepsToSelect = multiSelectItemIds.includes(stepId)
      ? multiSelectItemIds.filter(id => id !== stepId)
      : [...multiSelectItemIds, stepId]
  } else if (selectedStepId && selectedStepId === stepId) {
    // meta-clicked on the selected single step
    stepsToSelect = [selectedStepId]
  } else if (selectedStepId) {
    // meta-clicked on a different step, multi-select both
    stepsToSelect = [selectedStepId, stepId]
  } else {
    // meta-clicked on a step when a terminal item was selected
    stepsToSelect = [stepId]
  }
  return stepsToSelect
}
```

It also might be good to add some quick tests to `getMetaSelectedSteps`?

Comment (shlokamin) [reply protocol-designer/src/containers/ConnectedStepItem.js]: oh ya you're right, we're already doing `stepsToSelect = [stepId]`, in the final `else`. I'll update! and yeah thats a good call all add some tests

**Review by IanLondon — APPROVED** [review]

**Review by Kadee80 — APPROVED** [review]
🐤
