### PR TITLE
fix(app): robot Update banner renders when bot is unavailable fix

### LINKED ISSUE #10670: 6.0 Feedback:  Software upgrade is available is displayed for unavailable robots
### Overview

Software upgrade banner is displayed for unavailable robots

### Current Behavior

Screen Shot 2022-06-08 at 11 53 15 AM

### Expected Behavior

upgrade banner should not be available

### Steps To Reproduce

1. Robot server is not running
2. it is displayed in the Unavailable robot section, with the software update is available banner
3. Similar behavior is seen with robot OT2 where the app goes unavailable after the upgrade, and OT2 appears in the unavailable section - still displaying the software upgrade banner
Screen Shot 2022-06-08 at 10 26 12 AM

### Operating system

_No response_

### Robot setup or anything else?

_No response_

### PR DESCRIPTION
**Pull request by jerader**
closes #10670

# Overview

Previously, when a robot is reachable but the health status is 'not ok', it appears in the Unavailable section of the Device Landing page with the update robot banner still available and clickable. This fixes that bug so the banner is no longer there.

# Changelog

- edit logic in `updateRobotBanner` to also look for if the robot health status is not ok

# Review requests

- with a robot with an update available, connect to it, then turn off the robot. When it is in the Unavailable robot section, the update robot banner should not be present.

# Risk assessment

low

### CODE REVIEW

File: app/src/organisms/UpdateRobotBanner/index.tsx [hunk 1]
```diff
@@ -59,8 +60,10 @@ export function UpdateRobotBanner(props: UpdateRobotBannerProps): JSX.Element {
   }
 
   return (
-    <Flex onClick={e => e.stopPropagation()}>
-      {autoUpdateAction === 'upgrade' || autoUpdateAction === 'downgrade' ? (
+    <Flex onClick={e => e.stopPropagation()} flexDirection={DIRECTION_COLUMN}>
```
Comment (jerader) [inline app/src/organisms/UpdateRobotBanner/index.tsx:63]: this `flexDirection` is added so the banner now spans the whole width of the robot card (this was a bug introduced in one of my previous PRs when I added a `stopPropagation()`)

File: app/src/organisms/UpdateRobotBanner/__tests__/UpdateRobotBanner.test.tsx [hunk 2]
```diff
@@ -70,4 +73,14 @@ describe('UpdateRobotBanner', () => {
     const { getByText } = render(props)
     getByText('A software update is available for this robot.')
   })
+
+  it('should render nothing if robot health status is not ok', () => {
+    props = {
+      robot: mockReachableRobot,
```
Comment (koji) [inline app/src/organisms/UpdateRobotBanner/__tests__/UpdateRobotBanner.test.tsx:79]: Probably adding `mockUnreachableRobot` as another test case would be good.

Comment (jerader) [reply app/src/organisms/UpdateRobotBanner/__tests__/UpdateRobotBanner.test.tsx:79]: I'm a bit confused by your question - this PR is addressing 10670 😄

**Review by koji — APPROVED** [review]
The changes look good to me 🤖

File: app/src/organisms/UpdateRobotBanner/__tests__/UpdateRobotBanner.test.tsx (hunk 2 above)
Comment (jerader) [reply app/src/organisms/UpdateRobotBanner/__tests__/UpdateRobotBanner.test.tsx:79]: Oh nevermind, I see what you mean - the health status for `mockReachableRobot` is `not ok`, which is a combination you can have.

Comment (koji) [reply app/src/organisms/UpdateRobotBanner/__tests__/UpdateRobotBanner.test.tsx:79]: @jerader sorry, just updated the comment.
Unavailable robot = `recent seen` and `unreachable` ( both of them are `health status is not ok`), but I think that is totally optional.
