### PR TITLE
fix(app): make cal commands chain instead of race

### LINKED ISSUE #6535: Pipette Offset Calibration: Refactor chained commands into epics
There are some commands that get issued in sequence without UI changes or user interaction. Each command is only valid when the server in the appropriate state, and so should be triggered when the results from the previous command arrive at the app; refactor these chained commands away from their current sleep()-based ordering into a proper epic.

### PR DESCRIPTION
**Pull request by b-cooper**
# Overview

In order to avoid various race conditions created by sequential commands being requested of the
robot during/before/after calibration sessions, create mechanism to ensure that they are dispatched
sequentially. Also ensure that wizard only closes on successful deletion, to avoid orphaned session.

Closes #6535

NOTE: these changes have been made within the generic `CalibrationPanels` component directory, which is only being used in the pipette offset calibration flow. The deck calibration and tip length calibration flows will be refactored to use the panels from this shared directory in a following PR.

TODO: ~unit tests for new `useDispatchApiRequests` hook~, ensure unit tests for `PipetteOffsetCalibrationControl` cover new additions 
 
# Changelog

- add a new utility hook called `useDispatchApiRequests` that is very similar to the existing `useDispatchApiRequest`, but accepts any number of api request actions and will only dispatch each sequential action once the request from the previous action has resolved (`status !== PENDING`).
- plug this new hook into the pipette offset calibration flow for all sequential calls
- remove temporary setTimeout fix for sequential calls
- while hoisting dispatch machinery up to the `PipetteOffsetCalibrationControl` component, let it manage closing the wizard so as to avoid orphaned (undeleted) sessions on the robot that can't be viewed or "redeleted" on the app.

# Review requests

- [ ] run through the existing pipette offset calibration flow and ensure that all transitions occur as expected.

# Risk assessment

low, this change is contained within the unreleased pipette offset calibration flow, though this functionality will be added to the other cal overhaul front-ends immediately following this PR merging.

### CODE REVIEW

File: app/src/robot-api/hooks.js [hunk 1]
```diff
@@ -40,15 +44,74 @@ export function useDispatchApiRequest<A: { meta: { requestId: string } }>(): [
...
+ * @example
+ * import { useDispatchApiRequests } from '../../robot-api'
+ * import { fetchPipettes } from '../../pipettes'
+ * import { fetchModules } from '../../modules'
+ *
+ * type Props = {| robotName: string |}
+ *
+ * export function FetchPipettesButton(props: Props) {
+ *   const { robotName } = props
+ *   const [dispatchRequests, requestIds] = useDispatchApiRequest()
```
Comment (sfoster1) [inline app/src/robot-api/hooks.js:79]:
```suggestion
 *   const [dispatchRequests, requestIds] = useDispatchApiRequests()
```

File: app/src/robot-api/hooks.js [hunk 2]
```diff
@@ -40,15 +44,74 @@ export function useDispatchApiRequest<A: { meta: { requestId: string } }>(): [
...
+ *
+ *   return (
+ *     <button onClick={() => dispatchRequest([fetchPipettes(robotName), fetchModules(robotName)])}>
```
Comment (sfoster1) [inline app/src/robot-api/hooks.js:82]:
```suggestion
 *     <button onClick={() => dispatchRequests([fetchPipettes(robotName), fetchModules(robotName)])}>
```

**Review by sfoster1 — COMMENTED** [review]
Looks like some typos in the example for the new selector

**Review by sfoster1 — APPROVED** [review]
A quick test on my robot does indicate that these requests are chaining!

**Review by Laura-Danielle — APPROVED** [review]
lgtm, also cool
