### PR TITLE
fix(app): pipette card calibrate banner bug fix

### LINKED ISSUE #10324: 6.0 Feedback:  Pipette offset calibration alert shows up after calibration
### Overview

image
Showing right after I complete the attach pipette -> pipette offset calibration -> tip length calibration  flow.
Note that the overflow menu also did not reflect the pipette state. It said calibrate  and should say recalibrate since the calibration was just completed.

### Current Behavior

I attached a new pipette and did the calibration as suggested during that wizard process.
When I see the device details screen again after finishing pipette offset and tip length calibration the below alert is present on the pipette I just attached and calibrated that says I need to perform Pipette Offset calibration.
image
If I click X it goes away
When I navigate to labware then back to devices, expand the robot with the just attached pipette, the alert shows but then disappears on its own.

### Expected Behavior

This alert does not show because I just completed this calibration.
The overflow menu is also updated to say recalibrate pipette offset.

### Steps To Reproduce

Attach a different pipette and follow the wizard through pipette offset and tip length calibration.
See the alert.

### Operating system

Mac

### Robot setup or anything else?

This was one of the latest .dmg from the #builds channel.

### PR DESCRIPTION
**Pull request by jerader**
closes #10324

# Overview

This PR fixes a bug where the calibration banner remains even after performing pipette calibration

# Changelog

- add a `useInterval` to poll for the pipette calibration data every 1 second

# Review requests
- remove pipette calibrations from your robot, launch the pipette calibration wizard via the banner on the pipette card. Once you complete calibration, the banner should no longer be there.

# Risk assessment

low

### CODE REVIEW

File: app/src/organisms/Devices/PipetteCard/index.tsx [hunk 1]
```diff
@@ -47,10 +50,13 @@ interface PipetteCardProps {
   robotName: string
 }
 
+const FETCH_PIPETTE_CAL_MS = 1000
+
```
Comment (jerader) [inline app/src/organisms/Devices/PipetteCard/index.tsx]: Is polling every 1 second okay or should I increase the time?

Comment (koji) [reply app/src/organisms/Devices/PipetteCard/index.tsx]: The changes look good to me but not sure about the reasonable fetch interval. 
Most intervals in this repo are `5000`/`10000` and the following uses `5000`. 

https://github.com/Opentrons/opentrons/blob/edge/app/src/pages/Robots/InstrumentSettings/AttachedPipettesCard.tsx

Maybe increasing would be good.

@b-cooper @brenthagen and @shlokamin
Any suggestion on this?

**Review by b-cooper — APPROVED** [review]
🏁  this looks like a reasonable fix and polling interval
