### PR TITLE
fix(app): add looking for robots state

### LINKED ISSUE #10483: 6.0 Feedback:  App does not display spinner when refresh button in devices tab clicked
### Overview

_No response_

### Current Behavior

The app does not display a spinner when refresh button to find robots is clicked 

### Expected Behavior

image

### Steps To Reproduce

1. Click refresh button
Screen Shot 2022-05-26 at 4 20 35 PM
 

2. See no spinner is displayed, blank app 
Screen Shot 2022-05-26 at 4 18 21 PM
 

### Operating system

Mac

### Robot setup or anything else?

_No response_

### PR DESCRIPTION
**Pull request by vabruzzo**
# Overview
Fixes looking for robots state on devices landing page
Closes #10483

# Changelog
- adds looking for robots copy
- add spinner icon

# Review requests
Click Refresh button when no robots are found to confirm copy and spinner render

# Risk assessment
Low

### CODE REVIEW

**Review by koji — COMMENTED** [review]
The changes make sense to me but as I posted to Slack the current behavior is a little bit weird.
I think getting the answer from the team would be good.

File: app/src/pages/Devices/DevicesLanding/index.tsx [hunk 1]
```diff
@@ -51,6 +54,20 @@ export function DevicesLanding(): JSX.Element {
           <DevicesEmptyState />
         </Flex>
       ) : null}
+      {isScanning && (
```
Comment (koji) [inline app/src/pages/Devices/DevicesLanding/index.tsx]:
```suggestion
      {isScanning && availableDevices.length === 0  (
```

**Review by b-cooper — APPROVED** [review]
🎡
