### PR TITLE
fix(api, app): Clear instrument offset before performing deck calibration

### LINKED ISSUE #5022: Pipette calibration poisons deck calibration
# Overview
A robot's pipette calibration affects the data produced by a deck calibration.

# Steps to reproduce
1. Factory reset pipette calibration.
1. Perform a deck calibration through the app.
1. Check your deck calibration, somehow. One way is to do a pipette calibration and pay attention to where the pipette starts off.
1. Intentionally save a bad pipette calibration. Trigger the top switch too early or late, so that the tip length is obviously affected.
1. Perform a second deck calibration through the app.
1. Factory reset pipette calibration.
1. Check your deck calibration again. The height, at least, will be different.

The only difference between the deck calibrations in steps 3 and 7 is the pipette calibration that was active when the deck calibration was initiated.

# Expected behavior
Deck calibration should always produce identical data, regardless of the initial state of the robot. (Except for unavoidable imprecision in movement and human perception.)

# Additional things to investigate
* ~~I saw the height of deck calibration get affected. Can the lateral component also be affected?~~ Yes.
* Does pipette calibration affect the movement that happens during the deck calibration process itself (when the robot moves to the crosses), or just the output data? (Movement should not be affected; bad pipette calibrations should not be able to cause crashes during deck calibration.)

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=535438347) by [Unito](https://www.unito.io/learn-more)

### PR DESCRIPTION
**Pull request by Laura-Danielle**
# Overview

Closes #5022 by resetting instrument offset for all pipettes any time a new deck calibration begins. Some design changes were also added in the app by following instructions from [this design](https://app.zeplin.io/project/5aa97729db58a2192f10d0d6/screen/5f174015bc047a778385eb90).

# Changelog

- Add messaging in deck cal CLI about re-doing pipette calibration (instrument offset does not get taken into account here because robot settings/deck cal are reset before beginning the program)
- Modify the app according to the design above
- The robot _no longer_ restarts after a deck calibration
- Reset instrument offset in `endpoints.py` and reload the current pip instrument offset to be (0, 0, 0)
- Remove feature flags for v1 in `endpoints.py` as it's no longer relevant

# Review requests

Please check that the code place for resetting instrument offset etc are OK.

# Test Plan

1. Verify the issue with the robot and app on 3.19 or edge
   a. Modify your instrument offset (the value in `/data/robot_settings.json` under `instrument_offset` and the mount and type of pipette you'll use for deck calibration - the output of tip probe) to be bad, for instance having a value of 20 in its z component.
   b. Run deck calibration, trying to do a good job.
   c. verify that after the robot restarts, the deck calibration is obviously incorrect - if you modified the z component of instrument offset, the deck calibration z offset should be very wrong
2. Verify that this PR fixes the issue, after putting this PR on the robot with `make push` and building the app on this pr with `make -C app dev`
   a. Edit `/data/robot_settings.json` and verify that the value under `instrument_offset` for the mount and type of pipette used for deck calibration is still bad and large
   b. Run deck calibration, trying to do a good job
   c. When ending deck calibration, the button should say "save and exit" rather than "save and restart robot". The robot should not restart when you click the button
   d. Edit `/data/robot_settings.json` and verify that the `instrument_offset` for the mount and type of pipette you did deck calibration with is now `(0, 0, 0)`
   e. Edit `/data/gantry_calibration.json` and verify that the deck calibration is not bad in the same way it was in 1c
   f. Run the calibrate-to-crosses protocol used by the labware creator. Run tip probe and check that the pipettes move to the crosses accurately (or as accurately as they normally do).

Let me know if you have any other questions!

# Risk assessment

Medium. There was concern that customers would be confused by the new messaging at the end of the deck calibration program in the app. Please make sure we are OK with this language before merging.

### CODE REVIEW

File: app/src/components/CalibrateDeck/AttachTip.js [hunk 1]
```diff
@@ -45,13 +48,23 @@ export function AttachTip(props: AttachTipProps): React.Node {
       <span>
         <p>Remove the Opentrons tip from the pipette.</p>
         <p>
-          You must restart your robot to finish the initial robot calibration
-          process and have the new settings take effect. It may take several
-          minutes for your robot to restart.
+          Please note that as a result of the new deck calibration data, your
```
Comment (sfoster1) [inline app/src/components/CalibrateDeck/AttachTip.js:51]: Maybe cut this para as discussed yesterday? I think just the final para ("In order to effectively use..." is enough of a warning.

**Review by sfoster1 — CHANGES_REQUESTED** [review]
Python side looks good (haven't tested though) but we should change the FE copy a bit

File: app/src/components/CalibrateDeck/AttachTip.js (hunk 1 above)
Comment (Laura-Danielle) [reply app/src/components/CalibrateDeck/AttachTip.js:51]: Ah ok, I misunderstood. Will remove it.

**Review by sfoster1 — APPROVED** [review]
LGTM pending QA and UX review

**Review by nusrat813 — APPROVED** [review]
Tested - working as intended

**Review by pantslakz — APPROVED** [review]

**Comment by SyntaxColoring** [comment]
@Laura-Danielle 

> by resetting instrument offset for all pipettes any time a new deck calibration begins

If you start and then abort a deck calibration, is the pipette calibration still cleared? (If so, I don't think it would be a big problem—just looking out for surprises.)
