### PR TITLE
fix(app): robot settings cal health check wizard issue

### LINKED ISSUE #10491: 6.0 Feedback:  Clicking robot Settings > Check Health homes the robot gantry but nothing happens in the app
### Overview

image

### Current Behavior

Nothing happens in the app after clicking Device > My robot > Robot Settings 
check health

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Operating system

_No response_

### Robot setup or anything else?

_No response_

### PR DESCRIPTION
**Pull request by koji**
# Overview
This will close #10491
One skipped test case in `RobotSettingsCalibration.test.tsx` will be solved by #10599

Currently, `RobotSettingsCalibration.tsx` is almost 700 lines so Calibration Health Check will be a component in another PR to make this functionality more maintainable.

# Changelog
- Fix the issue health check wizard display issue
- Update the health check button disabled condition

# Review requests
- Health Check button is disabled when deck, pipette offset, tip length calibrations are missing
- When click Health Check button, the health check wizard shows up

# Risk assessment
low

### CODE REVIEW

File: app/src/organisms/Devices/RobotSettings/RobotSettingsCalibration.tsx [hunk 1]
```diff
@@ -82,6 +89,20 @@ const spinnerCommandBlockList: SessionCommandString[] = [
   Sessions.sharedCalCommands.JOG,
 ]
 
+const attachedPipetteCalPresent: (
+  pipettes: AttachedPipettesByMount,
+  pipetteCalibrations: PipetteCalibrationsByMount
+) => boolean = (pipettes, pipetteCalibrations) => {
+  for (const m of Pipettes.PIPETTE_MOUNTS) {
```
Comment (b-cooper) [inline app/src/organisms/Devices/RobotSettings/RobotSettingsCalibration.tsx]: This can be written as a single `some`

e.g.
```
Pipettes.PIPETTE_MOUNTS.some(mount => pipettes[mount] != null && (!pipetteCalibrations[mount].offset || !pipetteCalibrations[mount].tipLength))
```

Note: this returns whether the attached pipette's cal is absent.  If you negate it with `!` you'll get the same value as before.

File: app/src/organisms/Devices/RobotSettings/RobotSettingsCalibration.tsx [hunk 2]
```diff
@@ -208,13 +240,30 @@ export function RobotSettingsCalibration({
...
+    pipetteCalPresent &&
+    pipettePresent
+
+  const healthCheckButtonDisabled =
+    Boolean(buttonDisabledReason) || isPending || checkHealthCheckIsPossible
+
+  console.log('buttonDisabledReason: ', buttonDisabledReason)
+  console.log('Boolean(buttonDisabledReason): ', Boolean(buttonDisabledReason))
+  console.log('isPending: ', isPending)
+  console.log('checkHealthCheckIsPossible: ', checkHealthCheckIsPossible)
```
Comment (b-cooper) [inline app/src/organisms/Devices/RobotSettings/RobotSettingsCalibration.tsx]:
```suggestion
```

File: app/src/organisms/Devices/RobotSettings/RobotSettingsCalibration.tsx [hunk 3]
```diff
@@ -88,6 +95,17 @@ const spinnerCommandBlockList: SessionCommandString[] = [
   Sessions.sharedCalCommands.JOG,
 ]
 
+const attachedPipetteCalPresent: (
+  pipettes: AttachedPipettesByMount,
```
Comment (jerader) [inline app/src/organisms/Devices/RobotSettings/RobotSettingsCalibration.tsx:99]: I'm surprised a function like this doesn't already exist?

**Review by jerader — APPROVED** [review]
smoke tested a bit, works as expected.

File: app/src/organisms/Devices/RobotSettings/RobotSettingsCalibration.tsx (hunk 3 above)
Comment (koji) [reply app/src/organisms/Devices/RobotSettings/RobotSettingsCalibration.tsx:99]: In 5.0.2, this function exists for Calibration Health Check so maybe that is the reason.
