### PR TITLE
style(app): fix icon wrapping in robots slideout

### LINKED ISSUE #10111: 6.0 Feedback:  wifi symbol is out of the <div> in robots slideout
### Overview

wifi symbol / usb symbol is out of the <div> on Robot slideout

### Current Behavior

Screen Shot 2022-04-27 at 4 12 45 PM

### Expected Behavior

Screen Shot 2022-04-27 at 4 14 02 PM

### Steps To Reproduce

Goto Protocols landing page -> Goto protocols details page -> click on the protocol card, robots slideout opens.
the Wifi symbol / usb symbol is out of the <div>

### Operating system

_No response_

### Robot setup or anything else?

_No response_

### PR DESCRIPTION
**Pull request by vabruzzo**
# Overview

This will fix the icon that overflows outside the robot slideout div.
Closes #10111 

# Changelog

- Restructure `AvailableRobotOption` markup such that the icon wraps  if necessary and sits at the end of the last line of text.

# Review requests

- Pull open the robot slideout to confirm the icon acts as desired.
- Ensure that code is following conventions, in particular I suspect we might want to do something with the negative margin-bottom. I've left a comment in the PR highlighting this.

# Risk assessment
Low

### CODE REVIEW

File: app/src/organisms/ChooseRobotSlideout/AvailableRobotOption.tsx [hunk 1]
```diff
@@ -40,18 +40,19 @@ export function AvailableRobotOption(
...
         <StyledText as="h6">{robotModel}</StyledText>
-        <Flex alignItems={ALIGN_CENTER}>
+        <Box>
           <StyledText as="p" fontWeight={TYPOGRAPHY.fontWeightSemiBold}>
             {robotName}
+            &nbsp;&nbsp;
+            <Icon
+              // local boolean corresponds to a wired usb connection
+              aria-label={local ? 'usb' : 'wifi'}
+              marginBottom="-0.25rem"
```
Comment (vabruzzo) [inline app/src/organisms/ChooseRobotSlideout/AvailableRobotOption.tsx]: This hardcoded margin might be a candidate for `spacing.ts` but I noticed we don't have any negative spacings there, and it doesn't quite make sense.

I'm open to other suggestions here that avoids a negative margin but this restructure is a bit tricky as we want to keep that vertical spacing.

Comment (smb2268) [reply app/src/organisms/ChooseRobotSlideout/AvailableRobotOption.tsx]: I think the negative margin is a fine solution but instead of adding "-0.25rem" to the `spacing.ts`, let's change this to `marginBottom={'-${SPACING.spacing2}'}`

File: app/src/organisms/ChooseRobotSlideout/AvailableRobotOption.tsx [hunk 2]
```diff
@@ -40,18 +40,19 @@ export function AvailableRobotOption(
         marginTop={SPACING.spacing3}
       >
         <StyledText as="h6">{robotModel}</StyledText>
-        <Flex alignItems={ALIGN_CENTER}>
+        <Box>
           <StyledText as="p" fontWeight={TYPOGRAPHY.fontWeightSemiBold}>
             {robotName}
+            &nbsp;&nbsp;
```
Comment (smb2268) [inline app/src/organisms/ChooseRobotSlideout/AvailableRobotOption.tsx]: Instead of having the non-breaking space here, let's add a `marginLeft` to the Icon to achieve the separation we want

**Review by smb2268 — CHANGES_REQUESTED** [review]
This works well if the robot name has spaces in it but if it's one long word the text will go out of the slide out. I think we'll need to add a text wrap property or something like that to cover our bases! 
Screen Shot 2022-05-18 at 12 45 49 PM

**Comment by vabruzzo** [comment]
Thanks @smb2268, your review notes have been addressed.

**Review by smb2268 — APPROVED** [review]
Looks great! If you run `yarn prettier --write app/src/organisms/ChooseRobotSlideout/AvailableRobotOption.tsx` and push up that JS check failure should resolve. Once all of the checks pass you can feel free to squash & merge! 🚀

**Review by mmencarelli — APPROVED** [review]
