### PR TITLE
fix(app): connect pipette settings form's submit button

### LINKED ISSUE #11281: bug: 6.0.0 App: Changes to advanced pipette settings do not take effect
### Overview

Changes to values in the advanced pipette settings menu don't take effect and there's no response from the app when clicking the "Confirm" button. 

Tested with all the values that can be edited in the pipette settings. Not seeing any response from the "Reset all" button either. 

### Steps to reproduce

1. Open App 
2. Devices Tab
3. Select connected Robot 
4. Open Pipette Settings Menu from one of the pipette tiles 
5. Change any of the values, hit the enter key on keyboard or click out of the dialog box
6. Click confirm 
7. Close out Pipette settings 
8. Re open settings menu 

### Current behavior

No response from the confirm button press, the values do not change after editing them. No values change, and it doesn't work on either pipette. 

[combined.log](https://github.com/Opentrons/opentrons/files/9245732/combined.log)

https://user-images.githubusercontent.com/95253244/182475763-44a423d2-6079-43b9-b017-0eddc7fc148e.mov

 

### Expected behavior

The value should hold when you edit it, and there should be a response from the confirm button. 

### Operating system

Mac

### System and robot setup or anything else?

6.0.0 
Connected via ethernet (OT-2R)

### PR DESCRIPTION
**Pull request by vabruzzo**
# Overview
Closes #11281.
When users edit pipette settings and click submit, the submit button does not handle the submit and no settings are saved. To fix this we added an `id` to the form, and a `form` prop that references the form's `id`. This fixes the submit functionality.

We had a remaining data de-sync issue: we were using redux via `updatePipetteSettings` to mutate the pipette data and `usePipetteSettingsQuery` to retrieve the data. This was causing some data de-syncing. This fixes data sync issues by using a redux selector to retrieve data. There is not yet a way to mutate this data using `ReactQuery`, so using redux as a single source of truth is a quick fix. Presumably we want to extend react-api-client and add a pipette settings mutation query. For hotfix purposes I think using redux makes sense.

# Changelog
- add id to pipette settings form
- add form prop to pipette settings submit button
- use redux selector instead of ReactQuery usePipetteSettings query to display settings

# Review requests
- confirm works as expected
- confirm that this approach is acceptable

# Risk assessment
low

### CODE REVIEW

File: app/src/organisms/ConfigurePipette/index.tsx [hunk 1]
```diff
@@ -11,21 +11,30 @@ import type {
   PipetteSettingsFieldsUpdate,
 } from '../../redux/pipettes/types'
 import type { RequestState } from '../../redux/robot-api/types'
+import type { State } from '../../redux/types'
 
-const PIPETTE_SETTINGS_POLL_MS = 5000
 interface Props {
   closeModal: () => unknown
```
Comment (koji) [inline app/src/organisms/ConfigurePipette/index.tsx]:
```suggestion
  closeModal: () => void
```

File: app/src/organisms/ConfigurePipette/ConfigForm.tsx [hunk 2]
```diff
@@ -217,7 +217,7 @@ export class ConfigForm extends React.Component<ConfigFormProps> {
           }
           return (
             <Box overflowY="scroll">
-              <Form>
+              <Form id="configurePipetteForm">
```
Comment (koji) [inline app/src/organisms/ConfigurePipette/ConfigForm.tsx]: L43 we can remove ` closeModal: () => unknown` since this part for the previous modal component and tried on my end and it wouldn't break the app.

File: app/src/organisms/Devices/PipetteCard/PipetteSettingsSlideout.tsx [hunk 3]
```diff
@@ -71,6 +71,7 @@ export const PipetteSettingsSlideout = (
           pipetteId={pipetteId}
           updateRequest={updateRequest}
           updateSettings={updateSettings}
+          robotName={robotName}
```
Comment (koji) [inline app/src/organisms/Devices/PipetteCard/PipetteSettingsSlideout.tsx:78]: L31 probably we can change to  `onCloseClick: () => void`

File: app/src/organisms/ConfigurePipette/index.tsx [hunk 4]
```diff
@@ -54,8 +63,7 @@ export function ConfigurePipette(props: Props): JSX.Element {
       {updateError && <ConfigErrorBanner message={updateError} />}
       {settings != null && pipetteId != null && (
         <ConfigForm
-          //  @ts-expect-error: pipetteId and settings should not be undefined
-          settings={settings[pipetteId].fields}
+          settings={settings}
           updateInProgress={updateRequest?.status === PENDING}
           updateSettings={updateSettings}
           closeModal={closeModal}
```
Comment (koji) [inline app/src/organisms/ConfigurePipette/index.tsx]: I think we can remove this `closeModal={closeModal}`

**Review by koji — APPROVED** [review]
smoke tested and the changes work as expected.
Thank you for fixing this! 🙏
I tried a few things with `usePipetteSettingsQuery` and still haven't found a solution.
I will create a ticket about that on Jira.

**Review by jerader — APPROVED** [review]
smoke tested and works! thanks so much for fixing this!! 🚀

File: app/src/organisms/ConfigurePipette/__tests__/ConfigurePipette.test.tsx [hunk 5]
```diff
@@ -0,0 +1,83 @@
...
+  it('renders correct text', () => {
+    const { getByText } = render(props)
+
+    getByText('Bottom')
+    getByText('Top')
+  })
+
+  it('renders reset button', () => {
+    const { getByText } = render(props)
+    getByText('Reset all')
```
Comment (mcous) [inline app/src/organisms/ConfigurePipette/__tests__/ConfigurePipette.test.tsx]: I'd prefer `getByRole` here, according to [testing-library docs](https://testing-library.com/docs/queries/about#priority).

Also, should this test be clicking the reset button and verifying that something happens?

File: app/src/organisms/ConfigurePipette/__tests__/ConfigurePipette.test.tsx [hunk 6]
```diff
@@ -0,0 +1,83 @@
...
+    )
+    dispatchApiRequest = jest.fn()
+    mockUseDispatchApiRequest.mockReturnValue([dispatchApiRequest, ['id']])
+  })
+  afterEach(() => {
+    jest.resetAllMocks()
+  })
+  afterEach(() => {
+    resetAllWhenMocks()
+  })
```
Comment (mcous) [inline app/src/organisms/ConfigurePipette/__tests__/ConfigurePipette.test.tsx]: I do not see any `when` mocks used in the file. I would recommend using them, or drop the `resetAllWhenMocks`

File: app/src/organisms/ConfigurePipette/__tests__/ConfigurePipette.test.tsx [hunk 7]
```diff
@@ -0,0 +1,83 @@
...
+
+  beforeEach(() => {
+    props = {
+      pipetteId: 'id',
+      robotName: mockRobotName,
+      updateRequest: { status: 'pending' },
+      updateSettings: jest.fn(),
+      closeModal: jest.fn(),
+    }
+    mockGetRequestById.mockReturnValue({
```
Comment (mcous) [inline app/src/organisms/ConfigurePipette/__tests__/ConfigurePipette.test.tsx]: Prefer `when` stubbing to unconditional stubbing, which can hide bugs

File: app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx [hunk 8]
```diff
@@ -56,24 +61,35 @@ describe('PipetteSettingsSlideout', () => {
         status: 200,
       },
     })
+    mockGetConfig.mockReturnValue({} as any)
+    mockGetAttachedPipetteSettingsFieldById.mockReturnValue(
```
Comment (mcous) [inline app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx]: Unconditional mock would hide if `getAttachedPipetteSettingsFieldsById` was called incorrectly

File: app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx [hunk 9]
```diff
@@ -56,24 +61,35 @@ describe('PipetteSettingsSlideout', () => {
...
-  afterEach(() => {
     resetAllWhenMocks()
   })
 
   it('renders correct text', () => {
     const { getByText, getByRole } = render(props)
 
     getByText('Left Pipette Settings')
-    getByText('mock configure pipette')
+    getByText('Bottom')
```
Comment (mcous) [inline app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx]: Prefer `getByRole('button', {type: 'submit'})` (apologies if I got the exact syntax wrong there, but it's something along those lines)

File: app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx [hunk 10]
```diff
@@ -1,28 +1,33 @@
...
-  typeof ConfigurePipette
->
+const mockGetConfig = getConfig as jest.MockedFunction<typeof getConfig>
 const mockUseDispatchApiRequest = RobotApi.useDispatchApiRequest as jest.MockedFunction<
   typeof RobotApi.useDispatchApiRequest
 >
 const mockGetRequestById = RobotApi.getRequestById as jest.MockedFunction<
   typeof RobotApi.getRequestById
 >
+const mockGetAttachedPipetteSettingsFieldById = getAttachedPipetteSettingsFieldsById as jest.MockedFunction<
```
Comment (mcous) [inline app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx]: Slight mismatch in mock name vs dependency name (missing an `s`)

```suggestion
const mockGetAttachedPipetteSettingsFieldsById = getAttachedPipetteSettingsFieldsById as jest.MockedFunction<
```

File: app/src/organisms/ConfigurePipette/ConfigForm.tsx [hunk 11]
```diff
@@ -217,7 +216,7 @@ export class ConfigForm extends React.Component<ConfigFormProps> {
           }
           return (
             <Box overflowY="scroll">
-              <Form>
+              <Form id="configurePipetteForm" data-testid="ConfigForm_form">
```
Comment (mcous) [inline app/src/organisms/ConfigurePipette/ConfigForm.tsx]: I don't think the `id` should be hardcoded like this; it should be passed in as a prop so that the parent that's rendering both the form and the submit button can ensure the IDs match (and also so the ID can be constructed to be more unique, perhaps by including the pipette serial number).

Also, see comment below about why we shouldn't use `data-testid` here

File: app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx [hunk 12]
```diff
@@ -56,24 +61,35 @@ describe('PipetteSettingsSlideout', () => {
...
     const button = getByRole('button', { name: /exit/i })
-    fireEvent.click(button)
+    act(() => button.click())
     expect(props.onCloseClick).toHaveBeenCalled()
   })
+  it('renders confirm button and calls form onsubmit when clicked', () => {
+    const { getByText, getByRole, getByTestId } = render(props)
+
+    getByText('Bottom')
+    const form = getByTestId('ConfigForm_form')
```
Comment (mcous) [inline app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx]: Related to comment above: do not use `testid`. We should get this element by the `form` role with a matching `id` that we've passed via props

File: app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx [hunk 13]
```diff
@@ -56,24 +61,35 @@ describe('PipetteSettingsSlideout', () => {
...
+    form.onsubmit = jest.fn()
+    const button = getByRole('button', { name: 'Confirm' })
```
Comment (mcous) [inline app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx:105]: Get by role with type submit

File: app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx [hunk 14]
```diff
@@ -56,24 +61,35 @@ describe('PipetteSettingsSlideout', () => {
...
-    fireEvent.click(button)
+    act(() => button.click())
     expect(props.onCloseClick).toHaveBeenCalled()
   })
+  it('renders confirm button and calls form onsubmit when clicked', () => {
+    const { getByText, getByRole, getByTestId } = render(props)
+
+    getByText('Bottom')
+    const form = getByTestId('ConfigForm_form')
+    form.onsubmit = jest.fn()
```
Comment (mcous) [inline app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx]: Do not modify the `form`; this creates a [contaminated test subject](https://github.com/testdouble/contributing-tests/wiki/Partial-Mock#contaminated-test-subjects) and makes this test so it doesn't really test anything.

We need to measure what the form is doing using public props or injected `import` dependencies

**Review by mcous — CHANGES_REQUESTED** [review]
Have not smoke tested, but I would like to make sure our unit tests are in better shape since this is a hotfix release and our testing bar needs to be quite high.

This PR makes some serious improvements in that regard, so I'd like to push it just a little further

File: app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx (hunk 14 above)
Comment (vabruzzo) [reply app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx]: I'm not sure the best way to test this. This tests that the submit button, when clicked, submits the form that matches its `form` id.  this test was not so much about what the form is doing but rather that the submit button is properly wired to the form.

File: app/src/organisms/ConfigurePipette/__tests__/ConfigurePipette.test.tsx (hunk 5 above)
Comment (vabruzzo) [reply app/src/organisms/ConfigurePipette/__tests__/ConfigurePipette.test.tsx]: this functionality is actually tested by the reset buttons own preexisting unit tests. i can remove this test

File: app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx (hunk 9 above)
Comment (vabruzzo) [reply app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx]: _this `getByText` is grabbing a `p` or `span`, i dont think `getByRole` really works for these as we don't include a `name` for all of these._     scratch that some of these are inputs as well

File: app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx (hunk 13 above)
Comment (vabruzzo) [reply app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx:105]: it seems that this is not supported by the testing-library api: https://github.com/testing-library/dom-testing-library/issues/1012

File: app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx (hunk 9 above)
Comment (mcous) [reply app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx]: This command may have landed on the long line, sorry about that

File: app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx (hunk 14 above)
Comment (mcous) [reply app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx]: Verify that `dispatchApiRequest` (which is a mock that is already in this suite) is called with the correct action and parameters, probably with some relatively permissive expectations with the actual form values

File: app/src/organisms/ConfigurePipette/ConfigForm.tsx [hunk 15]
```diff
@@ -217,7 +217,7 @@ export class ConfigForm extends React.Component<ConfigFormProps> {
           }
           return (
             <Box overflowY="scroll">
-              <Form>
+              <Form id={formId} aria-label="configure_pipette_form">
```
Comment (mcous) [inline app/src/organisms/ConfigurePipette/ConfigForm.tsx]: What's this `aria-label` doing? It looks like it was added for tests, not for user-facing accessibility purposes. I would remove it

File: app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx [hunk 16]
```diff
@@ -56,24 +61,41 @@ describe('PipetteSettingsSlideout', () => {
...
     const button = getByRole('button', { name: /exit/i })
-    fireEvent.click(button)
+    button.click()
     expect(props.onCloseClick).toHaveBeenCalled()
   })
+
+  it('renders confirm button and calls form onsubmit when clicked', () => {
+    const { getByRole } = render(props)
+
+    const form = getByRole('form', { name: 'configure_pipette_form' })
```
Comment (mcous) [inline app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx]: There is only one form under test, no need for the `name` filter

```suggestion
    const form = getByRole('form')
```

File: app/src/organisms/Devices/PipetteCard/PipetteSettingsSlideout.tsx [hunk 17]
```diff
@@ -24,11 +24,12 @@ import type {
 import type { Dispatch, State } from '../../../redux/types'
 
 const FETCH_PIPETTES_INTERVAL_MS = 5000
+const FORM_ID = 'configurePipetteForm'
```
Comment (mcous) [inline app/src/organisms/Devices/PipetteCard/PipetteSettingsSlideout.tsx]: Can this ID include the pipette serial number rather than a constant which in the most technical sense will run an ID collision risk?

**Review by mcous — COMMENTED** [review]
Also getting `Warning: An update to Formik inside a test was not wrapped in act(...).` when running these tests

File: app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx (hunk 14 above)
Comment (vabruzzo) [reply app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx]: @mcous this is what I tried initially, but the test fails and `dispatchApiRequest` does not get called, i believe it has something to do with how Formik is wired that i have not quite figured out to work around in the testing. here is what i have tried::

```
  it('renders confirm button and calls form onsubmit when clicked', () => {
    const { getByRole } = render(props)

    // const form = getByRole('form', { name: 'configure_pipette_form' })
    // form.onsubmit = jest.fn()
    const button = getByRole('button', { name: 'Confirm' })
    act(() => button.click())
    expect(dispatchApiRequest).toHaveBeenCalled()
  })
```

i fear trying to get formik working in the test might lead to a bit of a rabbit hole.

i will continue to dig further but might this be acceptable for the hotfix to confirm that the button is wired properly to get the form to submit when clicked?

File: app/src/organisms/ConfigurePipette/ConfigForm.tsx (hunk 15 above)
Comment (vabruzzo) [reply app/src/organisms/ConfigurePipette/ConfigForm.tsx]: this is required by testing-library: https://github.com/testing-library/dom-testing-library/issues/474

File: app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx (hunk 16 above)
Comment (vabruzzo) [reply app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx]: yeah this is weird by test-library has a lot of caveats about which elements can be found by role alone: https://github.com/testing-library/dom-testing-library/issues/474

Comment (vabruzzo) [reply app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx]: actually, as the issue refers, this is required by the spec, not the library itself

**Comment by vabruzzo** [comment]
> Also getting `Warning: An update to Formik inside a test was not wrapped in act(...).` when running these tests

fixed with `waitFor`. the `act` that i was using _should_have worked but it is a formik bug as documented here: https://github.com/jaredpalmer/formik/issues/1543

File: app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx (hunk 14 above)
Comment (mcous) [reply app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx]: > i will continue to dig further but might this be acceptable for the hotfix to confirm that the button is wired properly to get the form to submit?

The key reason this is _not_ acceptable is that this test doesn't actually assert that our UI is wired up properly, therefore it does not verify that the user-facing bug is fixed. Because we've modified the `<form>` under test, we're not testing that our form works, we're testing that some partially fake `<form>` is able to submit.

If you wanted to do this specific test ("submit" button is wired to form), you should simply check that the button has a `form` attribute that matches the `form`'s `id` attribute. This would resolve the contaminated test subject problem, **but it would still be insufficient, because we need to verify that form submission results in the correct side effect,** not that form submission happens.

> i fear trying to get formik working in the test might lead to a bit of a rabbit hole

Trying to add tests to code that isn't well tested often results in this feeling. I encourage you to try to start shifting your mentality on these sorts of issues. If you've got this sort of rabbit hole in front of you, instead of saying to yourself:

> These tests are too hard, since everything looks like it's working can we skip the tests?

...try to say to yourself instead...

> This code isn't testable / verifiable, how can I change the code so that testing isn't a rabbit hole?

\</tedtalk>

For the Formik warning issue:

- You do not need to explicitely wrap most testing-library stuff in `act`
    - You should use `fireEvent.click` instead
- You should wrap your expectation in `await waitFor(() => ...` to resolve the `act` warnings


For the issue where the dispatch isn't firing:

- The dispatch isn't firing because the fixture data in `api-client/src/pipettes/__fixtures__/index.ts` that is fed into the form in the test is invalid
- The `top` setting must be greater than the `bottom` setting must be greater than `blowOut` must be greater than `dropTip`

Finally:

- `toHaveBeenCalled()` if _very_ rarely sufficient
- In collaborator tests like these, you should be testing that things are correctly wired up, and that means asserting that dependencies are called **with the correct arguments**

Recommended test:

```ts
// ...

import {
  getAttachedPipetteSettingsFieldsById,
  updatePipetteSettings,
} from '../../../../redux/pipettes'

// ...

const mockUpdatePipetteSettings = updatePipetteSettings as jest.MockedFunction<
  typeof updatePipetteSettings
>

// ...

  it('renders confirm button and calls form onsubmit when clicked', async () => {
    const { getByRole } = render(props)
    const button = getByRole('button', { name: 'Confirm' })

    when(mockUpdatePipetteSettings)
      .calledWith(
        expect.any(String),
        props.pipetteId,
        expect.objectContaining({ top: null, bottom: null })
      )
      .mockReturnValue({
        type: 'pipettes:UPDATE_PIPETTE_SETTINGS',
      } as UpdatePipetteSettingsAction)

    fireEvent.click(button)

    await waitFor(() => {
      expect(dispatchApiRequest).toHaveBeenCalledWith({
        type: 'pipettes:UPDATE_PIPETTE_SETTINGS',
      })
    })
  })
```

Sequence of the test above:

1. Arrange
    - Find the submit button
    - Configure the `mockUpdatePipetteSettings` action creator stub to return an action if called correctly (with the values from the form)
2. Act
    - Click the button 
3. Assert
    - Check action from stubbed action creator was dispatched

File: app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx (hunk 16 above)
Comment (mcous) [reply app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx]: This element is not needed for the test. I still think the aria-label should be removed or replaced with something human-readabale

File: app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx (hunk 14 above)
Comment (vabruzzo) [reply app/src/organisms/Devices/PipetteCard/__tests__/PipetteSettingsSlideout.test.tsx]: thank you for this, i greatly appreciate your guidance and mentorship!

**Review by mcous — APPROVED** [review]
Smoke tested the changes in the app against the dev server, looks to be working. Tests around this UI also look much improved, thanks for making that happen
