### PR TITLE
fix(app): fix pipette calibration modal auto closing

### LINKED ISSUE #10941: 6.0 Feedback:  Protocol setup: pipette calibration modal disappears before I can click return tip to tip rack and exit
### Overview
```gherkin
Given I proceed to setup on a protocol when a pipette needs calibration
When I get to the final step of the pipette calibration
Then I am navigated to the setup for run page without time 
to click the `RETURN TIP TO TIP RACK AND EXIT`  button
And the robot is in a bad state, tip on the pipette and not homed 
```
> Calibration steps truncated in the video

https://user-images.githubusercontent.com/502770/176444975-e1f61ed2-95b5-4a79-8b1b-cb97302c4b15.mp4

I must navigate to the device details page, then I can see the modal and click  `RETURN TIP TO TIP RACK AND EXIT` 

https://user-images.githubusercontent.com/502770/176444954-bf088eaa-aabc-4a35-9456-82952daf3ffd.mp4

### Current Behavior

Seems once there is a valid calibration detected through the API call then the page reloads hiding the modal?

### Expected Behavior

The modal does not disappear, I can click the button and the tip is returned and gantry homed.

### Steps To Reproduce

Example in video.

### Operating system

Mac

### Robot setup or anything else?

_No response_

### PR DESCRIPTION
**Pull request by vabruzzo**
# Overview
Fixes pipette calibration modal auto closing.
Closes #10941

# Changelog
- no longer conditionally render calibration modal in `SetupPipetteCalibrationItem`

# Review requests
confirm that modal does not close on its own

# Risk assessment

Low

### CODE REVIEW

File: app/src/pages/Devices/DeviceDetails/index.tsx [hunk 1]
```diff
@@ -23,9 +23,8 @@ import type { NavRouteParams } from '../../../App/types'
 export function DeviceDetails(): JSX.Element | null {
   const { robotName } = useParams<NavRouteParams>()
   const robot = useRobot(robotName)
-  console.log('RENDERED DEV')
```
Comment (b-cooper) [inline app/src/pages/Devices/DeviceDetails/index.tsx:26]: whooops, thanks for catching these 🙈

**Review by b-cooper — APPROVED** [review]
Changes look good to me 👍
