### PR TITLE
fix(app): remove copy link from context menu

### LINKED ISSUE #10054: 6.0 Feedback: many UI elements offer "Copy Link" contextual menu item
### Overview

Most UI elements in the new app UI can spawn a contextual menu item with a "Copy Link" item.

Screen Shot 2022-04-22 at 5 06 26 PM
Screen Shot 2022-04-22 at 5 06 38 PM
Screen Shot 2022-04-22 at 5 06 47 PM
Screen Shot 2022-04-22 at 5 07 10 PM

### Current Behavior

Most UI elements in the new app UI can spawn a contextual menu item, which usually only contains a "Copy Link" item (and also "Copy" if the text is selectable). This item does in fact copy a `file:///` URL to the clipboard, but its contents serve no purpose to the end user.

### Expected Behavior

These contextual menus should not appear if their only item is "Copy Link". Alternatively, if the URLs produced by Copy Link serve some internal or debugging purpose, the feature should be enabled by advanced preference / feature flag only.

### Steps To Reproduce

1. Launch the Opentrons App.
2. Right click on certain interface elements. These include (but are not limited to) sidebar text items, sidebar icons, protocol cards, and robot cards. Labware cards do _not_ spawn these menus.
3. Click Copy Link.

A link similar to `file:///Applications/Opentrons.app/Contents/Resources/app.asar/ui/index.html#/robots` will be put on the clipboard. This URL is meaningless because the app.asar file is not a bundle whose contents can be viewed individually.

Note: This behavior is also present in earlier versions of the app; it just manifests on significantly fewer UI elements.

### Operating system

Mac

### Robot setup or anything else?

_No response_

### PR DESCRIPTION
**Pull request by koji**
# Overview
This will fix #10054
Removed `copy link` by using the `menu` function
https://github.com/sindresorhus/electron-context-menu#menu.

There is a kind of issue with `electron-context-menu` in this project.

The version app-shell uses is 0.15.0 (released in Aug 2019). The current version is 3.1.2.
For safe, I would like to upgrade this package by another PR.
 
In addition, 0.15.0 has an issue with `searchWithGoogle` option.

Screen Shot 2022-05-18 at 12 53 29 PM

Screen Shot 2022-05-18 at 12 53 41 PM

# Changelog
- Updated `contextMenu` option

# Review requests
no copy link

# Risk assessment
low

### CODE REVIEW

File: app-shell/src/main.ts [hunk 1]
```diff
@@ -65,7 +65,13 @@ function startUp(): void {
 
   mainWindow.once('closed', () => (mainWindow = null))
 
-  contextMenu({ showInspectElement: config.devtools })
+  contextMenu({
+    menu: actions => [
+      actions.copy({}),
+      actions.lookUpSelection({}),
```
Comment (koji) [inline app-shell/src/main.ts:73]: Passing `{}` because currently, options are not optional.

https://github.com/sindresorhus/electron-context-menu/issues/153

Once fix the above issue, probably we can remove `{}`

**Comment by ecormany** [comment]
Looks good in the GUI. I see we decided to keep "Look up…" for compatibility, and it works. No "Copy Link" anywhere.

**Review by ecormany — APPROVED** [review]
Looks good in the GUI. I see we decided to keep "Look up…" for compatibility, and it works. No "Copy Link" anywhere.

**Comment by koji** [comment]
> Looks good in the GUI. I see we decided to keep "Look up…" for compatibility, and it works. No "Copy Link" anywhere.

@ecormany I keep `Look up` since the version the app uses is very old (0.1.5 the latest version is 3.1.2 😹) and there is an issue with adding `searchWithGoogle` as an option. In my opinion, upgrading a package is kind of troublesome. I would like to open another PR for adding `searchWithGoogle` which is including upgrading the package.

**Comment by ecormany** [comment]
> the version the app uses is very old (0.1.5 the latest version is 3.1.2 😹) 

glad we pin our dependencies 🤣

**Comment by koji** [comment]
- [ ] upgrade `electron-context-menu`

File: app-shell/src/main.ts (hunk 1 above)
Comment (vabruzzo) [reply app-shell/src/main.ts:73]: Perhaps a `TODO` with that link would be useful for tracking this?
