### PR TITLE
fix(app): wire up Software Update Alerts toggle logic

### LINKED ISSUE #10576: 6.0 Feedback:  software updates still shown after disabling software updates settings
### Overview

disable the software update alert (general app settings)-> then change the update channel to stable(advance app settings). Even though the alert is turned off, i am seeing the software update pop-up appearing

### Current Behavior

Screen Shot 2022-06-01 at 4 14 35 PM

There is a success banner
software update modal

### Expected Behavior

_No response_

### Steps To Reproduce

disable the software update alert (general app settings)-> then change the update channel to stable(advance app settings). 

### Operating system

_No response_

### Robot setup or anything else?

_No response_

### LINKED ISSUE #10783: 6.0 Feedback:  Unable to dismiss the software update banner on device landing page
### Overview

_No response_

### Current Behavior

Screen Shot 2022-06-15 at 4 11 43 PM

### Expected Behavior

_No response_

### Steps To Reproduce

1. Click on "X" on the software update modal on device landing page
2. I am on 6.0.0-beta-0
3. the banner doesn't disappear

### Operating system

_No response_

### Robot setup or anything else?

_No response_

### LINKED ISSUE #10831: If robot needs to be updated, always display the update available banner and warn if robot is busy
1. If the robot has an update available, always show the software update available banner on the robot card on the robot landing page, the robot detail page and the Robot Settings > Advanced Settings page

2. If the user launches the View Update modal and clicks Update Robot, show an “Are you sure” modal to the user to let them know updating will kill any in-progress actions.

See Figma for design details: https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=5196%3A190443

### PR DESCRIPTION
**Pull request by jerader**
closes #10576, closes #10783, closes #10831

# Overview

When you switch `Software Update Alerts` toggle to off, this PR fixes it so you won't receive the modal popup when there is an update available. It also removes the `useIsRobotBusy` hook from the update banners which is in the 1) Robot Card 2) Robot overview and 3) Robot Software Version. 

Additionally, this PR fixes the  X icon button on the banner. It will dismiss when you click on it now.

Also, if you try to update your robot when the robot is busy, there will be a warning modal

Screen Shot 2022-06-21 at 9 23 06 AM

# Changelog

- fix logic in `GeneralSettings` to take enabled boolean const into consideration, fix test
- add state setter for the delete button icon of the update robot banner
- remove usage of the `useIsRobotBusy` hook from the 3 areas the update banner renders.
- add the useISRobotBusy hook to the `ViewUpdateModal` and add a modal `RobotIsBusyModal`

# Review requests

- in the app settings page when you have an update available, toggle the `Software Update Alerts` to off. You should no longer get the Update app modal pop up.
- with the toggle turned on, you should be able to dismiss the update banner by pressing the x icon button
- when you upload a protocol to the robot, the update robot banners should be visible in the 1) robot card 2)robot overview 3)robot software version components. If you click up update the software (when you click on the view update on the banner => Update Robot) there should be a warning modal that pops up

# Risk assessment

low

### CODE REVIEW

File: app/src/organisms/AppSettings/GeneralSettings.tsx [hunk 1]
```diff
@@ -104,7 +104,7 @@ export function GeneralSettings(): JSX.Element {
         paddingX={SPACING.spacing4}
         paddingY={SPACING.spacing5}
       >
-        {showUpdateBanner && (
+        {showUpdateBanner && enabled && (
```
Comment (vabruzzo) [inline app/src/organisms/AppSettings/GeneralSettings.tsx]: I understand this variable name was pre-existing, but it is a bit confusing, to me at least. What is enabled exactly? I don't think this is a required change, but it could be helpful if there was more information encoded in the name here so someone reading bits of code don't have to look elsewhere to see what is meant.

Comment (vabruzzo) [reply app/src/organisms/AppSettings/GeneralSettings.tsx]: it looks like in the new hook you created you use the variable `isUpdateAlertEnabled` to capture the same logic. perhaps we could use that name here or even use the newly created hook since it is the same logic.

File: app/src/organisms/Devices/hooks/useRobotBusyAndUpdateAlertEnabled.tsx [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+import { useCurrentRunId } from '../../ProtocolUpload/hooks'
+import type { State } from '../../../redux/types'
+
+export interface RobotBusyAndUpdateAlertEnabled {
+  isRobotBusy: boolean
+  isUpdateAlertEnabled: boolean | null
+}
+
+export function useRobotBusyAndUpdateAlertEnabled(): RobotBusyAndUpdateAlertEnabled {
+  const isUpdateAlertEnabled = useSelector((state: State) => {
```
Comment (vabruzzo) [inline app/src/organisms/Devices/hooks/useRobotBusyAndUpdateAlertEnabled.tsx]: It seems like this hook now does two things that are not that related semantically. One for the robot that should live here, and another for app settings that doesn't seem to quite fit. I suggest we continue to use `useRobotBusy` and create a new hook that lives near `organisms/AppSettings`, something like `useAppSettings`.

I did a quick search and didn't see a hook such as this, we use useSelector directly to grab this stuff from the store. If we do want to move reduxy stuff into custom hooks I think we should keep the organization somewhat close to the store's organization, so e.g. data we typically grab with `redux/config` can have it's own hook. Perhaps @b-cooper @koji have some thoughts on this one?

File: app/src/organisms/AppSettings/GeneralSettings.tsx (hunk 1 above)
Comment (jerader) [reply app/src/organisms/AppSettings/GeneralSettings.tsx]: This makes sense to me! Thanks!

File: app/src/organisms/Devices/RobotSettings/UpdateBuildroot/RobotIsBusyModal.tsx [hunk 3]
```diff
@@ -0,0 +1,63 @@
...
+
+  return (
+    <Modal type="warning" title={t('robot_is_busy')}>
+      <Flex flexDirection={DIRECTION_COLUMN}>
+        <Trans
+          t={t}
+          i18nKey="this_robot_will_restart_with_update"
+          components={{
+            block: (
+              <Text
```
Comment (koji) [inline app/src/organisms/Devices/RobotSettings/UpdateBuildroot/RobotIsBusyModal.tsx]:
```suggestion
              <StyledText as="p" marginBottom={SPACING.spacing}>
```

**Comment by emilywools** [comment]
LGTM!

**Review by aptrons22 — APPROVED** [review]
Looks good and nice job.

File: app/src/organisms/Devices/RobotSettings/UpdateBuildroot/ReleaseNotesModal.tsx [hunk 4]
```diff
@@ -34,20 +43,26 @@ export function ReleaseNotesModal(props: ReleaseNotesModalProps): JSX.Element {
...
   return (
-    <ScrollableAlertModal
-      heading={heading}
-      buttons={buttons}
-      restrictOuterScroll={false}
-      alertOverlay
-    >
-      <ReleaseNotes source={releaseNotes} />
-    </ScrollableAlertModal>
+    <>
```
Comment (b-cooper) [inline app/src/organisms/Devices/RobotSettings/UpdateBuildroot/ReleaseNotesModal.tsx]: this fragment is unnecessary.  

It can just be:

```
return showRobotIsBusyModal ? (...) : (...)
```

File: app/src/organisms/Devices/RobotSettings/UpdateBuildroot/__tests__/ViewUpdateModal.test.tsx [hunk 5]
```diff
@@ -38,17 +39,18 @@ describe('ViewUpdateModal', () => {
...
   ) => {
     return mountWithStore<React.ComponentProps<typeof ViewUpdateModal>>(
-      <ViewUpdateModal
-        robotName={MOCK_ROBOT_NAME}
-        robotUpdateType={robotUpdateType}
-        robotSystemType={robotSystemType}
-        close={handleClose}
-        proceed={handleProceed}
-      />,
+      <QueryClientProvider client={queryClient}>
```
Comment (b-cooper) [inline app/src/organisms/Devices/RobotSettings/UpdateBuildroot/__tests__/ViewUpdateModal.test.tsx:42]: Why did we need to add the query client provider to this test?

File: app/src/organisms/Devices/RobotSettings/UpdateBuildroot/RobotIsBusyModal.tsx [hunk 6]
```diff
@@ -0,0 +1,58 @@
...
+          justifyContent={JUSTIFY_FLEX_END}
+          alignItems={ALIGN_CENTER}
+          marginTop={SPACING.spacing3}
+        >
+          <Btn
+            onClick={closeModal}
+            textTransform={TEXT_TRANSFORM_CAPITALIZE}
+            marginRight={SPACING.spacing5}
+            css={TYPOGRAPHY.linkPSemiBold}
+            fontWeight={TYPOGRAPHY.fontWeightSemiBold}
```
Comment (koji) [inline app/src/organisms/Devices/RobotSettings/UpdateBuildroot/RobotIsBusyModal.tsx]: linkPSemiBold sets `font-weight: 600` so we don't need this.
```suggestion
            
```

File: app/src/organisms/Devices/RobotSettings/UpdateBuildroot/__tests__/RobotIsBusyModal.test.tsx [hunk 7]
```diff
@@ -0,0 +1,41 @@
...
+      closeModal: jest.fn(),
+      proceed: jest.fn(),
+    }
+  })
+
+  afterEach(() => {
+    jest.resetAllMocks()
+  })
+
+  it('should render title, description, and buttons', () => {
```
Comment (koji) [inline app/src/organisms/Devices/RobotSettings/UpdateBuildroot/__tests__/RobotIsBusyModal.test.tsx:26]: The test code looks good to me.
But maybe we can create a new case(cases) for L34-L39 since the test case is `should render title, description, and buttons`.

for example 
- when clicking the cancel button, call mock func
- when clicking the yes button, call mock func

**Review by koji — APPROVED** [review]
The changes look good to me.
I left a couple of comments but they are small things.
