### PR TITLE
refactor(app): fix cancel run and close protocol behavior

### LINKED ISSUE #9231: Investigate Cancel and Close behavior
Cancelling and Closing a protocol run should be a seamless experience.  Both actions take a few seconds to complete.  

In the case of cancelling a drop tip and home is performed. We should update the UI in a way that shows this finishing action is occurring. 

Closing a protocol run should ideally immediately return the user to the empty upload screen. This may require more than just monitoring the close request loading state. We may need to invalidate some queries ala work that Brent did in the closed PR.

### PR DESCRIPTION
**Pull request by jerader**
closes #9231 

# Overview

This PR does a few things:

1) fixes the cancel run CTA behavior when you are cancelling from the Protocol Upload page - the logic is similar to what is done in #9252 for the cancel run CTA on the Run Details page

2) fixes the close protocol behavior when you close the protocol from both the Protocol Upload and Run Details pages. Currently, when you click to close the protocol from the Run Details page, is goes to the Protocol Upload page with the `ProtocolSetup` component rendered for a few seconds and then renders the `UploadInput` component. Now, when you click to close the protocol, it should go directly to displaying the `UploadInput` component.

# Changelog

- implemented similar logic from Sakib's PR #9252 when you cancel run from the Protocol Upload page
- extended `useCloseCurrentRun` props  so that you can utilize `useHistory` to `push` to the `upload` page when you click on the close protocol CTA button

# Review requests

- on your robot, upload a protocol and start a run. When you cancel the run from the Protocol Upload page, the 'Cancel run' CTA should disappear until the run has stopped. When you close the protocol from both the Protocol Upload page and the Run Details pages, it should display the protocol empty state (`UploadInput` component) and not display the `ProtocolSetup` component first.

# Risk assessment

low

### CODE REVIEW

File: app/src/organisms/ProtocolUpload/index.tsx [hunk 1]
```diff
@@ -154,7 +158,8 @@ export function ProtocolUpload(): JSX.Element {
   const isRunInMotion =
     runStatus === RUN_STATUS_RUNNING ||
     runStatus === RUN_STATUS_PAUSED ||
-    runStatus === RUN_STATUS_PAUSE_REQUESTED
+    runStatus === RUN_STATUS_PAUSE_REQUESTED ||
+    runStatus === RUN_STATUS_FINISHING
 
   let titleBarProps
   if (isProtocolRunLoaded && !isRunInMotion) {
```
Comment (sakibh) [inline app/src/organisms/ProtocolUpload/index.tsx]: Looks like when the run status is `Stop Requested` the protocol page is still rendering a Close button and never goes to the else if statement. You can add in a check for the run status in the first if statement to get around this.

```suggestion
  if (isProtocolRunLoaded && !isRunInMotion && runStatus !== RUN_STATUS_STOP_REQUESTED) {
```

**Review by sakibh — APPROVED** [review]
Looks great! Tested the flow on my robot and it is very seamless.

File: app/src/organisms/ProtocolUpload/__tests__/ProtocolUpload.test.tsx [hunk 2]
```diff
@@ -249,6 +257,80 @@ describe('ProtocolUpload', () => {
...
+        createProtocolRun: jest.fn(),
+      } as any)
+    when(mockUseRunStatus)
+      .calledWith()
+      .mockReturnValue(RUN_STATUS_STOP_REQUESTED)
+    when(mockConfirmCancelModal).mockReturnValue(
+      <div>mock confirm cancel modal</div>
+    )
+    expect(screen.queryByText('mock confirm cancel modal')).toBeNull()
+    expect(screen.queryByText('Cnacel Run')).toBeNull()
```
Comment (shlokamin) [inline app/src/organisms/ProtocolUpload/__tests__/ProtocolUpload.test.tsx]: `Cnacel Run` 😝

File: app/src/organisms/ProtocolUpload/hooks/useCloseCurrentRun.ts [hunk 3]
```diff
@@ -1,6 +1,6 @@
 import * as React from 'react'
 import { useDismissCurrentRunMutation } from '@opentrons/react-api-client'
-import { UseDismissCurrentRunMutationOptions } from '@opentrons/react-api-client/src/runs/useDismissCurrentRunMutation'
+import type { UseDismissCurrentRunMutationOptions } from '@opentrons/react-api-client/src/runs/useDismissCurrentRunMutation'
```
Comment (shlokamin) [inline app/src/organisms/ProtocolUpload/hooks/useCloseCurrentRun.ts]: this type import should go below everything else

File: app/src/organisms/ProtocolUpload/index.tsx [hunk 4]
```diff
@@ -171,6 +180,12 @@ export function ProtocolUpload(): JSX.Element {
       },
       className: styles.reverse_titlebar_items,
     }
+  } else if (runStatus === RUN_STATUS_STOP_REQUESTED) {
```
Comment (shlokamin) [inline app/src/organisms/ProtocolUpload/index.tsx:185]: nit: if you move this if statement up to the top, i don't think you need to add the `&& runStatus !== RUN_STATUS_STOP_REQUESTED` above since the if statement will short circuit.

File: app/src/organisms/ProtocolUpload/index.tsx [hunk 5]
```diff
@@ -171,6 +180,12 @@ export function ProtocolUpload(): JSX.Element {
...
+    titleBarProps = {
+      title: t('protocol_title', {
+        protocol_name: protocolRecord?.data?.metadata?.protocolName ?? '',
+      }),
```
Comment (shlokamin) [inline app/src/organisms/ProtocolUpload/index.tsx]: nit: this same title property looks like it's copied and pasted a few times. can we extract it into a variable and share it? like what we did with `cancelRunButton `

File: app/src/organisms/ProtocolUpload/index.tsx [hunk 6]
```diff
@@ -228,16 +242,31 @@ export function ProtocolUpload(): JSX.Element {
...
+                      robot_name: robotName,
+                    })
+                  : t('protocol_finishing', {
+                      robot_name: robotName,
+                    })
+              }
+            />
+          ) : (
+            pageContents
+          )}
```
Comment (shlokamin) [inline app/src/organisms/ProtocolUpload/index.tsx]: nit: this is quite the ternary. can we extract this into a function so it's a bit easier to follow

File: app/src/organisms/RunDetails/index.tsx [hunk 7]
```diff
@@ -65,7 +66,7 @@ export function RunDetails(): JSX.Element | null {
   } = useConditionalConfirm(handleCloseProtocol, true)
 
   if (!isProtocolRunLoaded) {
-    return <Redirect to="/upload" />
+    return null
   }
```
Comment (shlokamin) [inline app/src/organisms/RunDetails/index.tsx:70]: i think i might need you to walk me through this after standup, i think this makes sense but tbh i don't entirely follow

**Review by shlokamin — APPROVED** [review]
code looks good to me, and looks like you've thoroughly tested the important stuff 😄 just left some nits that might make the code a bit cleaner.

i don't have a robot to test on so i couldn't verify it does what we expect, but looks like sakib already verified. 

maybe you me sakib and brian can all walk through the new logic just so we're all on the same page? i think this makes sense to me but would just like to try to poke some holes in it to make sure we're not missing anything

**Review by b-cooper — APPROVED** [review]
Looks good 🍨
