### PR TITLE
fix(app): labware setup H-S latch command add runId

### LINKED ISSUE #11048: 6.0 Feedback:  Close labware latch button in Labware setup is unresponsive
### Overview

When in labware setup the close labware button doesnt do anything

### Current Behavior

Button doesnt do anything

### Expected Behavior

Button closes labware latch then changes to open button

### Steps To Reproduce

1. Open App
2. Upload a protocol with H/S and labware on H/S
3. Go thru labware setup
4. Click close latch butto

https://user-images.githubusercontent.com/106115893/177845030-dbe3a538-13c6-4d13-a4e4-b46c0cb4b7d7.mov

n

### Operating system

Mac

### Robot setup or anything else?

_No response_

### PR DESCRIPTION
**Pull request by jerader**
closes #11048 & #11125

# Overview

The labware setup extra attention banner for the H-S has a button that allows you to open/close the latch. However, the latch command didn't include the runId which is required to send commands to modules during setup. 

# Changelog

- refactor command logic to include `runId` in `ModuleExtraAttention` and fix test

# Review requests

- does logic sound correct? Try to test this on a h-s if you can! I am still unable to upload H-S protocols for some reason

# Risk assessment

low

### CODE REVIEW

File: app/src/organisms/Devices/ProtocolRun/ModuleExtraAttention.tsx [hunk 1]
```diff
@@ -113,7 +116,8 @@ const ModuleExtraAttentionItem = (
         }
 
         const toggleLatch = (): void => {
```
Comment (sakibh) [inline app/src/organisms/Devices/ProtocolRun/ModuleExtraAttention.tsx:118]: You can also use the `useLatchControls` hook where it now can take in an optional `runId` for controls that have a run associated with them. It returns a `toggleLatch` function as well. Although, this will require passing in the `AttachedModule` as the first parameter.

**Review by sakibh — APPROVED** [review]
The code LGTM!

File: app/src/organisms/Devices/ProtocolRun/ModuleExtraAttention.tsx (hunk 1 above)
Comment (jerader) [reply app/src/organisms/Devices/ProtocolRun/ModuleExtraAttention.tsx:118]: yeah, i tried using `useLatchControls` initially but was having a hard time getting `HeaterShakerAttachedModule`, so not using it was the cleanest way I think. But I can look into it more!
