### PR TITLE
fix(app): remove Robot is now successful modal from update flow

### LINKED ISSUE #10721: 6.0 Feedback: robot update modal disappears prematurely
### Overview

During a robot upgrade, the robot will briefly become "unhealthy" as the server reboots. In the v5 app, the robot upgrade modal will remain present, even as the robot becomes unhealthy, displaying a "Robot is rebooting" message.

In the v6 app, the UI navigates away from the robot's settings page / update modal as soon as the robot becomes unhealthy, dropping you to a "Devices" page that's missing your robot.

### Current Behavior

In v6, the "Robot is restarting" message flashes briefly, then you are dropped to this screen:

Screen Shot 2022-06-10 at 09 37 58

The robot being updated is hidden in the "Unavailable" collapsed section. Eventually, when the robot finishes rebooting, it displays here again

### Expected Behavior

This is the end of a robot update in v5. Notice the changes in the robot sidebar as the robot becomes unconnectable, but the update modal remains open

At the conclusion of the update, the user is given a success message when the app detects the robot is healthy again with the correct version

Screen Shot 2022-06-10 at 09 31 57

### Steps To Reproduce

Update a robot using the v6 app and compare it to an update run from the v5 app.

### Operating system

_No response_

### Robot setup or anything else?

_No response_

### PR DESCRIPTION
**Pull request by jerader**
closes #10721 

# Overview

Remove "Your robot is now successfully updated." modal when a software update is complete. Brian and I tested it but if able, please smoke test it as well!

# Changelog

- clear buildroot state if sessions is finished, so the `finished` modal should never render

# Review requests

- upload the robot build from this branch. Update your robot, when the update is complete, you should no longer get the robot update completed modal

# Risk assessment

low

### CODE REVIEW

File: app/src/organisms/Devices/RobotSettings/UpdateBuildroot/index.tsx [hunk 1]
```diff
@@ -38,6 +38,15 @@ export function UpdateBuildroot(props: UpdateBuildrootProps): JSX.Element {
...
+  // clears buildroot state if session finished when initially mounted
+  React.useEffect(() => {
+    if (step === 'finished') {
+      dispatch(clearBuildrootSession())
+    }
+  }, [dispatch, step])
+
   // clear buildroot state on component dismount if done
   React.useEffect(() => {
     if (step === 'finished' || error !== null) {
```
Comment (koji) [inline app/src/organisms/Devices/RobotSettings/UpdateBuildroot/index.tsx:52]: Do we need to keep this `step === finished`? ( L52 - the latest code)
Maybe 

```ts
React.useEffect(() => {
  if(error !== null) {
    dispatch(clearBuildrootSession())
   }
 }, [dispatch, error])
```

Comment (b-cooper) [reply app/src/organisms/Devices/RobotSettings/UpdateBuildroot/index.tsx:52]: We probably don't unless there is a chance that the session were to update to 'finished' after the component mounts.  It's not really doing harm here now, and we're going to refactor/replace these components soon anyway.

Comment (koji) [reply app/src/organisms/Devices/RobotSettings/UpdateBuildroot/index.tsx:52]: Thank you for your explanation!

**Review by koji — APPROVED** [review]
The changes make sense to me now.

**Review by vabruzzo — APPROVED** [review]
