### PR TITLE
fix(app): Address Choose a robot to run slideout design feedback

### LINKED ISSUE #11029: 6.0 Feedback:  [Design QA] Choose a robot to run slideout
### Overview

The original feedback is in https://github.com/Opentrons/opentrons/issues/10618

### Current Behavior

_No response_

### Expected Behavior

- [x] (1) Add a margin-right: .5rem to the Slideout_title_Choose
- [x] (2) Make the icon 24px vs 20px
- [x] (3) Got an extra 8px margin top above "refresh list". Should be 16px total between the line above and refresh list
- [x] (4) Missing hover state for the "refresh list" link. Could we change this text to "refresh"?
- [x] (5) Robot image should be a fixed width of 64x57px
- [x] (6) Technically this content should be vertically centered within the container. So should be down a bit more
         Mel's request `margin-top: 0.5rem`, `margin-bottom: 1rem`
- [x] (7) Remove background-color: #f8f8f8; from the hover state
- [x] (8) Also missing the cursor change to the hand signifying a clickable item when hovering over this card
- [x] (9) Are we nixing this content? if so, let me know so I can update the designs.
- [x] (10) Remove box shadow from this button
- [x] (11) Made a pitch to add a countdown timer when the user clicks "refresh". To the left of the screenshot in figma you'll see the designs
- [x] (12) Make the icon bigger, should be 20x20px and should be darkGreyEnabled
- [ ] (13) If the discovery times out, then the copy changes to "try again".

171932945-acfb8637-9ee0-40dc-8ed9-9da91d7b0b20

171932958-a2350248-6711-41f4-a170-71c5e18ec80f

171932965-0f0ff2df-69e0-41e4-ab9f-e487b599d7fb

### Steps To Reproduce

_No response_

### Operating system

_No response_

### Robot setup or anything else?

_No response_

### PR DESCRIPTION
**Pull request by koji**
# Overview
This PR will address choose a robot to run slideout design feedback.
Will close #11029 and #11057

exported (13) as a new issue
#11094

# Changelog
- update ChooseRobotSlideout styling
- remove Mini card hover backgrond

# Review requests
- [ ] Addressed design feedback #11029
- [ ] When clicking the selected mini card, the card won't be unselected

# Risk assessment
low

### CODE REVIEW

File: app/src/organisms/ChooseRobotSlideout/AvailableRobotOption.tsx [hunk 1]
```diff
@@ -50,19 +50,23 @@ export function AvailableRobotOption(
         <img
           src={OT2_PNG}
           css={css`
-            width: 6rem;
+            width: 4rem;
+            height: 3.5625rem;
```
Comment (jerader) [inline app/src/organisms/ChooseRobotSlideout/AvailableRobotOption.tsx:54]: this height is so specific 😅

File: app/src/organisms/ChooseRobotSlideout/index.tsx [hunk 2]
```diff
@@ -159,20 +160,33 @@ export function ChooseRobotSlideout(
...
+          marginBottom={SPACING.spacing3}
           height={SIZE_2}
         >
           {isScanning ? (
-            <Icon name="ot-spinner" spin size={SIZE_1} />
+            <Flex flexDirection={DIRECTION_ROW} alignItems={ALIGN_CENTER}>
+              <StyledText
+                as="p"
+                color={COLORS.darkGreyEnabled}
+                marginRight="0.625rem"
```
Comment (jerader) [inline app/src/organisms/ChooseRobotSlideout/index.tsx]: can use `{SPACING.spacingSM}`

File: app/src/organisms/ChooseRobotSlideout/__tests__/ChooseRobotSlideout.test.tsx [hunk 3]
```diff
@@ -187,7 +187,6 @@ describe('ChooseRobotSlideout', () => {
     expect(proceedButton).not.toBeDisabled()
     const otherRobot = getByText('otherRobot')
     otherRobot.click() // unselect default robot
-    expect(proceedButton).toBeDisabled()
```
Comment (jerader) [inline app/src/organisms/ChooseRobotSlideout/__tests__/ChooseRobotSlideout.test.tsx:190]: why are you deleting this? Shouldn't the button be disabled if you've unselected the current robot?

**Review by vabruzzo — APPROVED** [review]
changes lgtm 👍

**Review by jerader — APPROVED** [review]
Looking good. I left a few comments but I don't wanna block merging this.

File: app/src/organisms/ChooseRobotSlideout/AvailableRobotOption.tsx (hunk 1 above)
Comment (koji) [reply app/src/organisms/ChooseRobotSlideout/AvailableRobotOption.tsx:54]: Yeah, but it's a request from Mel.

File: app/src/organisms/ChooseRobotSlideout/__tests__/ChooseRobotSlideout.test.tsx (hunk 3 above)
Comment (koji) [reply app/src/organisms/ChooseRobotSlideout/__tests__/ChooseRobotSlideout.test.tsx:190]: let me check.

Comment (koji) [reply app/src/organisms/ChooseRobotSlideout/__tests__/ChooseRobotSlideout.test.tsx:190]: I remove the line because of the following change. 
For the previous code, if a user clicks the default selected robot, the robot will be unselected but this PR will change that behavior for #11057.

```ts
before: setSelectedRobot(isSelected ? null : robot)

after: setSelectedRobot(robot)
```

I added `expect(proceedButton).not.toBeDisabled()` instead of deleting line.
