### PR TITLE
fix(app): address design feedback initial protocols landing page 

### LINKED ISSUE #10907: 6.0 Feedback: [Design QA] T1 Protocols landing
### Overview
**The original feedback is in #10767**

[To a dev who picks this up]
Please do not close #10767 until finish fixing the entire Protocols landing page design feedback. 

### Current Behavior

_No response_

### Expected Behavior
Round 2 feedback on the empty state of the T1 Protocols page. First round can be found on #10208

[Annotated Figma frame link](https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=14683%3A419869)

- [ ] (1) Update this text to our h1 style 
- [ ] (2) Add in margin between h1 and p copy 
- [ ] (3) Can you add in our hover state for our blue links for the word "browse"? 
- [ ] (4) I'm assuming fixing these links for the main page would fix these here too
- [ ] (5) Center this entire section to the middle of the page (see purple rectangle)

Screen Shot 2022-06-23 at 4 24 32 PM

### PR DESCRIPTION
**Pull request by koji**
# Overview
This will fix #10907 
Maybe you see some unclear changes in this PR but those will be solved in another PR (Protocol landing page #10767)
In terms of (1) - (4), they are checked by Mel. #10928 

# Changelog
- address 10907 feedback
- remove css const and  use `darkLableSemiBold`

# Review requests
- Would like to get feedback on the current centralizing implementation.
Initially, tried setting 0 to top, bottom, left, and right then margin: auto, but it didn't work as expected and I switched the current way.

# Risk assessment
low

### CODE REVIEW

File: components/src/primitives/Btn.tsx [hunk 1]
```diff
@@ -151,7 +151,6 @@ export const NewPrimaryBtn: BtnComponent = styled(PrimaryBtn)`
  * @component
  */
 export const NewSecondaryBtn: BtnComponent = styled(SecondaryBtn)`
-  background-color: ${Styles.C_WHITE};
```
Comment (jerader) [inline components/src/primitives/Btn.tsx]: why did you remove this?

File: app/src/organisms/ProtocolsLanding/ProtocolList.tsx [hunk 2]
```diff
@@ -1,5 +1,6 @@
 import * as React from 'react'
 import { useTranslation } from 'react-i18next'
+
```
Comment (jerader) [inline app/src/organisms/ProtocolsLanding/ProtocolList.tsx]: fyi: there are some random empty line additions to this file

File: app/src/organisms/ProtocolsLanding/ProtocolsEmptyState.tsx [hunk 3]
```diff
@@ -19,10 +20,14 @@ export function ProtocolsEmptyState(): JSX.Element | null {
       width="100%"
       padding={SPACING.spacing4}
       paddingTop={SPACING.spacing6}
+      position={POSITION_ABSOLUTE}
+      top="50%"
+      left="50%"
+      transform="translateY(25%) translateX(-50%)"
```
Comment (jerader) [inline app/src/organisms/ProtocolsLanding/ProtocolsEmptyState.tsx]: This feels a bit suspicious to me. Can't you achieve the same thing by only adding a translateY? 

```suggestion
      transform="translateY(25%)"
```

**Review by jerader — COMMENTED** [review]
Looking good, just have a few questions.

File: components/src/primitives/Btn.tsx (hunk 1 above)
Comment (koji) [reply components/src/primitives/Btn.tsx]: Good catch.

File: app/src/organisms/ProtocolsLanding/ProtocolsEmptyState.tsx (hunk 3 above)
Comment (koji) [reply app/src/organisms/ProtocolsLanding/ProtocolsEmptyState.tsx]: Thanks! You are right.

**Review by jerader — APPROVED** [review]
lgtm!

File: app/src/pages/Protocols/ProtocolsLanding/index.tsx [hunk 4]
```diff
@@ -16,7 +16,7 @@ export function ProtocolsLanding(): JSX.Element {
   )
   React.useEffect(() => {
     dispatch(fetchProtocols())
-  }, [])
+  }, [dispatch])
```
Comment (vabruzzo) [inline app/src/pages/Protocols/ProtocolsLanding/index.tsx:19]: does this fix an issue we were seeing, or is it being added to silent the lint warning?

Comment (vabruzzo) [reply app/src/pages/Protocols/ProtocolsLanding/index.tsx:19]: i thought this might change the behavior we wanted but i just read up on `useDispatch` and learned it returns a stable `dispatch` so a potential issue i was worrying about is not an issue. 👍

File: app/src/organisms/ProtocolsLanding/UploadInput.tsx [hunk 5]
```diff
@@ -33,7 +34,11 @@ export function UploadInput(props: UploadInputProps): JSX.Element | null {
   }
 
   return (
-    <Flex flexDirection={DIRECTION_COLUMN} alignItems={ALIGN_CENTER}>
+    <Flex
```
Comment (vabruzzo) [inline app/src/organisms/ProtocolsLanding/UploadInput.tsx:37]: is this the "current centralizing implementation" you wanted feedback on? does this current implementation fail to do something we want to do? i can take a look in app if there is something specific you were trying

File: app/src/pages/Protocols/ProtocolsLanding/index.tsx (hunk 4 above)
Comment (koji) [reply app/src/pages/Protocols/ProtocolsLanding/index.tsx:19]: yes, I saw a lint warning

File: app/src/organisms/ProtocolsLanding/UploadInput.tsx (hunk 5 above)
Comment (koji) [reply app/src/organisms/ProtocolsLanding/UploadInput.tsx:37]: Jethary's feedback could improve "current centralizing implementation".
But thank you for your offer!
`UploadInput` hasn't been pointed out anything from Mel, so I guess currently this component is okay.
