### PR TITLE
fix(app): flip modules on deck map when in slots 3, 6, or 9

### LINKED ISSUE #4422: App: Flip temperature module rendering in 3,6,9
## overview

When a temperature module is placed in slots 3, 6, or 9, the Run app displays it as if the cords were on the left side. We should treat all tempdecks in slots 3, 6, 9 as flipped in the RobotWorkSpace component.

### PR DESCRIPTION
**Pull request by b-cooper**
# Overview

This patches a visual bug that rendered modules in slots 3, 6, and 9 with their plugs towards the
center of the deck. This doesn't match the physical arrangement and occludes other information on in
the visualization. Any module in those right-most slots will now render in the correct orientation.

Closes #4422

# Changelog

- add an `extraTransform` prop to the `RobotCoordsForeignDiv` that appends to the svg transform if flipped.
- add logic to the `Module` component (only used in RA calibration tab deck map and protocol-library-kludge) that now takes the slot details as a prop and flips the module outline by 180° about the center of the slot if in slots 3, 6, or 9. 

NOTE: in order to make sure the contents of the div aren't also flipped upside down, we need to apply an opposite rotation of 180° to the inner div via css

# Review requests

- [ ] load a protocol into the run app with temperature (or magnetics) modules in slots 3, 6, and/or 9. They should render with their cords facing the outside of the robot housing, and the icon within the module UI should appear to the right of the descriptive text.
- [ ] make sure protocol library kludge's usage of the `Module` component is uneffected.

# Risk assessment

Low, other than the run app calibration tab deck map, the only other component this change potentially effects is in protocol-library-kludge, so it would be good to smoke test that as well.

### CODE REVIEW

File: components/src/deck/Module.js [hunk 1]
```diff
@@ -5,38 +5,36 @@ import cx from 'classnames'
...
   /** module model */
   model: ModuleModel,
   /** display mode: 'default', 'present', 'missing', or 'info' */
   mode: 'default' | 'present' | 'missing' | 'info',
+  /** slot details of the location of this module */
+  slot: DeckSlot,
 |}
 
 export function Module(props: ModuleProps): React.Node {
-  // TODO: BC 2019-7-23 get these from shared data, once absolute
```
Comment (sfoster1) [inline components/src/deck/Module.js:28]: probably should preserve this todo, it's still a good idea (or just implement it? i think we have that data now)

**Review by sfoster1 — COMMENTED** [review]
It's yucky and I love it

File: components/src/deck/Module.js (hunk 1 above)
Comment (b-cooper) [reply components/src/deck/Module.js:28]: We don't quite have that data yet, we need the overall `xDimension`, `yDimension`, and `zDimension` as well as the `cornerOffsetFromSlot` or `footprintOffset` vector in the module definitions.

Comment (sfoster1) [reply components/src/deck/Module.js:28]: :+1:

**Review by IanLondon — APPROVED** [review]
the kludge looks good now!
