### PR TITLE
fix(app): fix long protocol name display issue

### LINKED ISSUE #10087: 6.0 Feedback:  Long Protocol Name cuts off the X button on "Run protocol" slideout
### Overview

With a sufficiently long protocol name like `MagneticV2TempV2MixTransferNoPause`
The X button on the "Run protocol" slideout gets cut off
image

### Current Behavior

X cut off

### Expected Behavior

X not cut off

### Steps To Reproduce

Import a protocol with a long name.
[MagneticV2TempV2MixTransferNoPause.json.zip](https://github.com/Opentrons/opentrons/files/8565630/MagneticV2TempV2MixTransferNoPause.json.zip)
 Go to protocol detail  and click run a protoco

https://user-images.githubusercontent.com/502770/165360482-885819b0-f991-43e9-9813-5690c44088d8.mp4

l

### Operating system

Mac

### Robot setup or anything else?

_No response_

### PR DESCRIPTION
**Pull request by koji**
# Overview
This will fix #10087 and #10109
This PR got confirmation from Mel.

Screen Shot 2022-05-19 at 9 51 35 PM

Screen Shot 2022-05-19 at 9 57 19 PM

#10326 (Changed `word-wrap` to `overflow-wrap`)
Screen Shot 2022-05-23 at 8 30 33 PM

# Changelog
- ~~Added `word-break` to Slideout~~
- ~~Added `word-break` to a card on ChooseProtocolSlideout~~
- Added '`overflow-wrap`: `anywhere`'  instead of `'word-break': 'break-word'`
- Changed `word-wrap` to `overflow-wrap`

# Review requests
- These long name issues are solved
If you need a test JSON file, let me know. I cannot attach a .zip file (not sure why). 

# Risk assessment
low

### CODE REVIEW

**Comment by koji** [comment]
- [x] fix conflicts

File: app/src/atoms/Slideout/index.tsx [hunk 1]
```diff
@@ -112,6 +112,7 @@ export const Slideout = (props: Props): JSX.Element | null => {
             >
               <StyledText
                 as="h2"
+                css={{ 'word-break': 'break-word' }}
```
Comment (jerader) [inline app/src/atoms/Slideout/index.tsx]: How come you change between `word-break` and `word-wrap`?

**Review by jerader — APPROVED** [review]
Left a quick question but this LGTM and works as expected!

File: app/src/atoms/Slideout/index.tsx (hunk 1 above)
Comment (koji) [reply app/src/atoms/Slideout/index.tsx]: using auto or not.
In the slideout, we use `flex="0 1 auto"` (line 101) and `word-wrap` doesn't work as we expect.

Comment (koji) [reply app/src/atoms/Slideout/index.tsx]: I just noticed that `css={{ 'word-break': 'break-word' }}` is deprecated.

I should change to  overflow-wrap 
```
css={{ 'overflow-wrap': 'anywhere' }}
```

**Comment by koji** [comment]
- [x] `word-wrap` --> `overflow-wrap`

File: app/src/atoms/Slideout/index.tsx (hunk 1 above)
Comment (vabruzzo) [reply app/src/atoms/Slideout/index.tsx]: according to [caniuse](https://caniuse.com/?search=overflow-wrap) and [mdn](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap), the `anywhere` value is not supported on safari, safari on ios, IE, and opera mobile. `break-word` is supported in all of these. i imagine we want to keep this support since it has no other effects? and perhaps add a TODO for future migration if `anywhere` is supported
