### PR TITLE
fix(app): block LPC when a protocol does not have a tip rack loaded

### LINKED ISSUE #9090: bug: Whitescreen when starting Labware Position Check on a protocol that loads, but does not use, a plate and pipette
# Steps to reproduce

Upload this protocol on v5.0.0-beta.3:

```python
metadata = {"apiLevel": "2.11"}

def run(protocol):
    plate = protocol.load_labware("biorad_96_wellplate_200ul_pcr", 1)
    pipette = protocol.load_instrument("p300_single_gen2", mount="left")
```

Then, start Labware Position Check.

# Current behavior

The app whitescreens. In the devtools console, I see:

> Uncaught Error: expected to be able to find labware location, but could not

# Expected behavior

Either LPC should be disabled with a descriptive tooltip, or it should not whitescreen.

### PR DESCRIPTION
**Pull request by sakibh**
# Overview

The white screen behavior described in the ticket below seems to occur when a tip rack is not loaded in the protocol. This PR blocks the LPC CTA when a protocol that is uploaded does not have a tip rack loaded. 

closes #9090

Screen Shot 2021-12-17 at 4 53 37 PM

# Changelog

- Added conditional to check if there is a primary tip rack in the protocol

# Review requests

- Check that when a protocol is loaded **without** a tip rack LPC is disabled.
- Check that when a protocol is loaded **with** a tip rack LPC is enabled.

Protocol with No Tip Rack:
```
metadata = {"apiLevel": "2.11"}

def run(protocol):

    # No Tip Rack
    plate = protocol.load_labware("biorad_96_wellplate_200ul_pcr", 2)
    pipette = protocol.load_instrument("p300_single_gen2", mount="right")
```

Protocol with Tip Rack:
```
metadata = {"apiLevel": "2.11"}

def run(protocol):

    # With Tip Rack
    p300racks = [protocol.load_labware('opentrons_96_tiprack_300ul', '3')]
    plate = protocol.load_labware("biorad_96_wellplate_200ul_pcr", 2)
    pipette = protocol.load_instrument("p300_single_gen2", mount="right")
```

# Risk assessment
low

### CODE REVIEW

File: app/src/organisms/ProtocolSetup/RunSetupCard/LabwareSetup/index.tsx [hunk 1]
```diff
@@ -91,6 +91,16 @@ export const LabwareSetup = (): JSX.Element | null => {
   const moduleAndCalibrationIncomplete =
     missingModuleIds.length > 0 && !isEverythingCalibrated
 
+  let tipRackLoadedInProtocol: boolean = false
```
Comment (b-cooper) [inline app/src/organisms/ProtocolSetup/RunSetupCard/LabwareSetup/index.tsx]: this would be a great place to use `some` [lodash docs](https://lodash.com/docs/4.17.15#some).

should be able to make this much more concise. something like:

```
const tipRackLoadedInProtocol = some(protocolData?.labwareDefinitions ?? [], def => def.parameters?.isTiprack)
```

**Review by b-cooper — APPROVED** [review]
✅
