### PR TITLE
fix(app): no longer require app restart after python override path config is updated

### LINKED ISSUE #10612: 6.0 Feedback:  Override Path to Python add copy to indicate restart required
### Overview

While investigating #10607 
@mcous noted 
- App must be restarted for change to take effect, but UI does not state this
- App's file picker uses an `<input>` element and `<button>` element; the semantically correct (and easier) solution is to use `<label>` styled like a button wrapping an `<input`>` so you don't have to do `onClick` trickery

> I think the first item to add copy indicating app restart is required is essential and should be a quick fix.

### PR DESCRIPTION
**Pull request by b-cooper**
# Overview

Instead of requiring the app to restart in order to incorporate a new pathToPythonOverride config
value, handle the config change on the fly

Closes #10612

# Review requests

- Change the value of the `pathToPythonOverride` advanced app setting on the build of this branch. Your change should be incorporated without requiring the app to be restarted.  Uploading a new protocol is a good way to test calling into the python interpreter before and after. 

# Risk assessment
low

### CODE REVIEW

File: app-shell/src/protocol-analysis/index.ts [hunk 1]
```diff
@@ -11,6 +11,10 @@ const log = createLogger('protocol-analysis')
 export function initializePython(): void {
   const pathToPythonOverride = getConfig().python.pathToPythonOverride
   selectPythonPath(pathToPythonOverride)
+
+  handleConfigChange('python.pathToPythonOverride', newValue => {
```
Comment (mcous) [inline app-shell/src/protocol-analysis/index.ts:15]: We should add a test for this behavior to the existing tests for the `initializePython` function

File: app-shell/src/protocol-analysis/__tests__/protocolAnalysis.test.ts [hunk 2]
```diff
@@ -45,6 +48,13 @@ describe('analyzeProtocolSource', () => {
     initializePython()
 
     expect(mockSelectPythonPath).toHaveBeenCalledWith('/some/override/python')
+
+    // the 'python.pathToPythonOverride' change handler
+    const changeHandler = mockHandleConfigChange.mock.calls[0][1]
+    const otherOverridePath = '/some/other/path/to/python'
+    changeHandler(otherOverridePath, '/some/override/python')
+
+    expect(mockSelectPythonPath).toHaveBeenCalledWith(otherOverridePath)
```
Comment (mcous) [inline app-shell/src/protocol-analysis/__tests__/protocolAnalysis.test.ts]: This is missing a check that `handleConfigChange` is called with the proper config path. You could change the first argument passed to `handleConfigChange` in source to something incorrect and this test would still pass, which is especially bad because these config paths aren't type-checked at the moment.

This is my suggestion for the test. I also renamed some test input to make the input more [obviously meaningless](https://github.com/testdouble/contributing-tests/wiki/Meaningless-Test-Data)

```suggestion
    expect(mockHandleConfigChange).toHaveBeenCalledWith(
      'python.pathToPythonOverride',
      expect.any(Function)
    )

    // the 'python.pathToPythonOverride' change handler
    const changeHandler = mockHandleConfigChange.mock.calls[0][1]
    changeHandler('/new/override/python', '/old/path/does/not/matter')
    expect(mockSelectPythonPath).toHaveBeenCalledWith('/new/override/python')
```

**Review by shlokamin — APPROVED** [review]
code LGTM
