### PR TITLE
style(app): Fix design feedback on FactoryReset

### LINKED ISSUE #10888: 6.0 Feedback: Design Feedback -  FactoryReset Slideout
- [x] (1) Up the size of this icon to 24px, currently it's 20px
 - [x] (2) Wondering why this is a different style from design?
 - [x] (3) Add 8px margin between the list items
 - [x] (4) Looks like there's a barely noticeable grey line right underneath the button?
 ~~- [ ] (5) remove box shadow from .layXKe~~
 ~~- [ ] (6) Looks like the SVG is a bit thicker than the designs—when you get to this step, contact me and I can try~~ sending you another SVG
 - [x] (7) The hover state colour should be our darkGreyHover (#646468), currently it's #283d52
 - [x] (8) When I try to tab through all the links using my keyboard none of the links of the tabs go into their focusVisible state

174907002-e2077252-120c-41b4-82e9-6e1a72b45112

The original feedback is in #10819

### PR DESCRIPTION
**Pull request by koji**
# Overview
This will fix design feedback on FactoryReset and update CheckboxField styling.
fix #10888

# Changelog
- Update FactoryReset Slideout styling
- Update CheckboxField styling
- Add scroll check to Slideout

# Review requests
- The UI aligns with the design #10888

# Risk assessment
low

### CODE REVIEW

File: app/src/atoms/CheckboxField/index.tsx [hunk 1]
```diff
@@ -124,11 +124,13 @@ export function CheckboxField(props: CheckboxFieldProps): JSX.Element {
         checked={props.value || false}
         disabled={props.disabled}
         onChange={props.onChange}
-        tabIndex={props.tabIndex}
+        tabIndex={0}
```
Comment (koji) [inline app/src/atoms/CheckboxField/index.tsx:127]: Changed the value to 0 because mdn suggests devs to use a number greater than 0

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex

File: app/src/atoms/Slideout/index.tsx [hunk 2]
```diff
@@ -77,6 +77,23 @@ const CLOSE_ICON_STYLE = css`
...
+      console.log('val', scrollTop, scrollHeight, clientHeight)
+      if (scrollTop + clientHeight === scrollHeight) {
+        setIsReachedBottom(true)
+      }
+    }
+  }
+
+  React.useEffect(() => {
+    onScroll()
+  }, [])
```
Comment (koji) [inline app/src/atoms/Slideout/index.tsx]: Need this because a few slideouts don't use the scroll.

File: app/src/organisms/Devices/RobotSettings/AdvancedTab/AdvancedTabSlideouts/FactoryResetSlideout.tsx [hunk 3]
```diff
@@ -143,6 +153,8 @@ export function FactoryResetSlideout({
               {t('reset_option_calibration')}
             </StyledText>
             <Link
+              role="button"
+              tabIndex={0}
```
Comment (koji) [inline app/src/organisms/Devices/RobotSettings/AdvancedTab/AdvancedTabSlideouts/FactoryResetSlideout.tsx:157]: This `tabIndex` might be temporary.
I will check all `Link` from `@opentrons/components` and open another PR.

The details are in the team slack channel.

File: app/src/organisms/Devices/RobotSettings/AdvancedTab/AdvancedTabSlideouts/FactoryResetSlideout.tsx [hunk 4]
```diff
@@ -180,6 +188,8 @@ export function FactoryResetSlideout({
               {t('reset_option_protocol_run_history')}
             </StyledText>
             <Link
+              role="button"
+              tabIndex={0}
```
Comment (koji) [inline app/src/organisms/Devices/RobotSettings/AdvancedTab/AdvancedTabSlideouts/FactoryResetSlideout.tsx:192]: same as above

File: app/src/pages/AppSettings/GeneralSettings.tsx [hunk 5]
```diff
@@ -187,20 +188,23 @@ export function GeneralSettings(): JSX.Element {
...
+              >
+                {t('restore_previous')}
+              </Link>
+              <ExternalLink
+                href={SOFTWARE_SYNC_URL}
+                id="GeneralSettings_appAndRobotSync"
+              >
+                {t('versions_sync')}
+              </ExternalLink>
+            </Flex>
```
Comment (koji) [inline app/src/pages/AppSettings/GeneralSettings.tsx:207]: Actually, this change is not related to FactoryResetSlideout.
I noticed this layout issue when I checked `Link`. If this shouldn't be included in this PR, please let me know. I will remove this and open a new pr for this.

File: app/src/organisms/Devices/RobotSettings/AdvancedTab/AdvancedTabSlideouts/FactoryResetSlideout.tsx [hunk 6]
```diff
@@ -10,16 +10,18 @@ import {
   SPACING,
   TYPOGRAPHY,
   Link,
-  // CheckboxField,
```
Comment (koji) [inline app/src/organisms/Devices/RobotSettings/AdvancedTab/AdvancedTabSlideouts/FactoryResetSlideout.tsx:13]: I missed Jethary's last feedback. Sorry about that.

File: app/src/atoms/CheckboxField/index.tsx [hunk 7]
```diff
@@ -96,7 +96,7 @@ const LABEL_TEXT_STYLE = css`
   font-weight: ${TYPOGRAPHY.fontWeightRegular};
   color: ${COLORS.darkBlack};
   flex: 0 0 auto;
-  padding: 0 0.5rem;
```
Comment (koji) [inline app/src/atoms/CheckboxField/index.tsx:99]: I missed Jethary's last feedback. Sorry about that.

File: app/src/atoms/Slideout/index.tsx (hunk 2 above)
Comment (jerader) [reply app/src/atoms/Slideout/index.tsx]: this removes the footer box-shadow styling needed for the slideouts that have a scroll: for example, the Choose a protocol slideout and Pipette Settings slideout should be like this - 
Screen Shot 2022-06-27 at 8 46 24 AM

Screen Shot 2022-06-27 at 8 45 54 AM

**Review by jerader — COMMENTED** [review]
just left a comment regarding the `onScroll`, it doesn't work correctly for the slideouts that need the`box-shadow` in the footer

**Review by mmencarelli — APPROVED** [review]
looks good!

**Review by mmencarelli — APPROVED** [review]

**Review by jerader — APPROVED** [review]
LGTM! `onScroll` looks SO GOOD! 🥳
