### PR TITLE
fix(app): fix pipette offset cal data fetch issue on RobotSettings

### LINKED ISSUE #10676: 6.0 Feedback:  Device pipettes, deck calibration and health check is disabled until a protocol is uploaded after software upgrade
### Overview

Functionalities are disabled on robot settings page
- this behavior can be reproduced in robot-server too

### Current Behavior

https://user-images.githubusercontent.com/39049853/172681301-b3b48fc4-499b-497a-ae51-9fa29d5e564e.mov

Screen Shot 2022-06-08 at 1 46 50 PM

Screen Shot 2022-06-08 at 1 47 11 PM

### Expected Behavior

_No response_

### Steps To Reproduce

1. Perform software update on app and robot to 6.0.0-alpha-1
2. Now from devices page or device detail page -> click on robot settings
3. I notice that Device pipettes are disabled , even if robot has pipettes page shows no pipettes
4. deck calibration is disabled
5. and health check is disabled
6. After the protocol is uploaded to the device -> from device page to go robot settings page 
7. All the above functionalities are enabled and reflected correctly

### Operating system

_No response_

### Robot setup or anything else?

_No response_

### PR DESCRIPTION
**Pull request by koji**
fix #10676

# Overview
This will fix #10676
Add data fetch to `useInterval` and switched `useAttachedPipetteCalibrations` from `Pipettes.getAttachedPipetteCalibrations`

# Changelog
- Add polling to fetch pipette offset cal and tip length cal data
- Use `useAttachedPipetteCalibrations` to get attachedPipette Calibration data

# Review requests

# Risk assessment
- low

### CODE REVIEW

File: app/src/organisms/Devices/RobotSettings/RobotSettingsCalibration.tsx [hunk 1]
```diff
@@ -470,6 +471,8 @@ export function RobotSettingsCalibration({
       dispatch(Calibration.fetchCalibrationStatus(robotName))
       dispatch(Calibration.fetchPipetteOffsetCalibrations(robotName))
       dispatch(Calibration.fetchTipLengthCalibrations(robotName))
+      dispatch(PipetteOffset.fetchPipetteOffsetCalibrations(robotName))
+      dispatch(TipLength.fetchTipLengthCalibrations(robotName))
```
Comment (vabruzzo) [inline app/src/organisms/Devices/RobotSettings/RobotSettingsCalibration.tsx]: Does this bug only occur after upgrading the app? If so, is it possible to dispatch these actions just once after an upgrade is complete rather than on an interval? I will approve now as it seems we want to get this out asap for the beta, and this is clean. Perhaps we could add a TODO to rethink where/how we dispatch these actions if it is the case that they are only needed directly after an upgrade.

**Review by vabruzzo — APPROVED** [review]
looks good. left one comment about possibly adding a TODO if my understanding is correct.

File: app/src/organisms/Devices/RobotSettings/RobotSettingsCalibration.tsx (hunk 1 above)
Comment (koji) [reply app/src/organisms/Devices/RobotSettings/RobotSettingsCalibration.tsx]: Actually, this occurs after rename a robot but the fetching issue doesn't happen to a robot detail page and recently I added these fetch to pipetteOffset component and tipLength component on the robot detail page.
Yes, you are right. Adding `TODO` is good. I will add TODO.

File: app/src/organisms/Devices/RobotSettings/RobotSettingsCalibration.tsx [hunk 2]
```diff
@@ -470,6 +471,8 @@ export function RobotSettingsCalibration({
       dispatch(Calibration.fetchCalibrationStatus(robotName))
       dispatch(Calibration.fetchPipetteOffsetCalibrations(robotName))
       dispatch(Calibration.fetchTipLengthCalibrations(robotName))
+      dispatch(PipetteOffset.fetchPipetteOffsetCalibrations(robotName))
```
Comment (b-cooper) [inline app/src/organisms/Devices/RobotSettings/RobotSettingsCalibration.tsx]: I think line 472 and line 474 are dispatching the exact same action right?  If so this one is unnecessary

Comment (koji) [reply app/src/organisms/Devices/RobotSettings/RobotSettingsCalibration.tsx]: Oh yes, thank you for pointing out this.
I will remove.

**Review by jerader — APPROVED** [review]
✅

**Comment by koji** [comment]
- [ ] check data from Neha

**Comment by reachojhaneha** [comment]
Screen Shot 2022-06-09 at 12 57 45 PM
Screen Shot 2022-06-09 at 12 57 57 PM

PR works for me. I see all Calibration Health Check, Deck Calibration and Pipette Offset calibration enabled

**Review by reachojhaneha — APPROVED** [review]
LGTM
