### PR TITLE
fix(app): fix RobotSettings pipette offset cals banner issue

### LINKED ISSUE #10485: 6.0 Feedback:  Missing Calibration alert still present after finishing calibration
### Overview

Just finished calibrating the highlighted pipette
image

### Current Behavior

_No response_

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Operating system

_No response_

### Robot setup or anything else?

_No response_

### PR DESCRIPTION
**Pull request by koji**
# Overview
This will close #10485, #10486, and #10574

before calibration
Screen Shot 2022-06-02 at 6 01 34 PM

after calibrations (without reloading)
Screen Shot 2022-06-02 at 6 10 29 PM

 

# Changelog
- Fix the conditions to check pipette offset calibration data (for #10485 & #10486)
- Check the length of attached pipettes and the length of calibrated pipettes (for #10574)

# Review requests
- when calibrating pipette offset the banner is gone without reloading

# Risk assessment
low

### CODE REVIEW

File: app/src/organisms/Devices/RobotSettings/RobotSettingsCalibration.tsx [hunk 1]
```diff
@@ -399,15 +452,28 @@ export function RobotSettingsCalibration({
...
   React.useEffect(() => {
     if (createStatus === RobotApi.SUCCESS) {
       createRequestId.current = null
     }
   }, [createStatus])
 
-  React.useEffect(() => {
-    checkPipetteCalibrationMissing()
-  }, [pipettePresent, pipetteOffsetCalibrations])
+  useInterval(
```
Comment (b-cooper) [inline app/src/organisms/Devices/RobotSettings/RobotSettingsCalibration.tsx:467]: should the new useEffect 's calls just also get put into this `useInterval` poll?

Comment (koji) [reply app/src/organisms/Devices/RobotSettings/RobotSettingsCalibration.tsx:467]: My bad, I think that `useEffect` should be removed.
Just pushed the code.

**Review by b-cooper — APPROVED** [review]
☑️
