### PR TITLE
fix(app): robot update Modal CTA fix

### LINKED ISSUE #10431: 6.0 Feedback: Robot update modal closes the first time you try to use it
### Overview

The first time I try to use the robot update modal, it closes without doing anything. Can reproduce consistently.

### Expected Behavior

The robot update wizard should proceed when I click "View Robot Update"

### Steps To Reproduce

1. Using the production v5.0.2 app, get an OT-2 onto v5.0.2
2. Open the development app from `edge`
3. Navigate to "Devices"
4. Click on "View update" > "Update robot now" > "View robot update"
5. Wizard closes instead of proceeding

If you then go through steps 4 and 5 again, the robot update will proceed normally.

### Operating system

Mac

### Robot setup or anything else?

- My OT-2R was on v5.0.2 production
- My app was on `edge` (a731395)
    - As of this commit, the app is unable to update v5 robots: #10430
    - However, the premature wizard close seems orthogonal
- Feel free to close this ticket in favor of #9808 and/or #9809

### PR DESCRIPTION
**Pull request by jerader**
closes #10431

# Overview

When trying to update the robot through the banner in the robot card, it won't properly and will instead redirect you to the robot overview page. This PR fixes that bug.

# Changelog

- add prop to `updateRobotBanner` so opening the `updateBuildroot` modal happens outside of the `onClick` in the flex in `RobotCard`. The `onClick` was causing the issue

- fix all instances of `updateRobotBanner`
- move `UpdateBuildroot` folder to `organisms/RobotSettings` and fix affected imports and tests (same thing that will be done in this PR: https://github.com/Opentrons/opentrons/pull/10385) 

# Review requests

run through the 3 ways to access the Robot update modal through the update Robot banner. Make sure it works okay:
1. Robot Card
2. Robot Advanced Settings
3. Robot Overview 

# Risk assessment

low

### CODE REVIEW

File: app/src/organisms/Devices/RobotSettings/AdvancedTab/RobotServerVersion.tsx [hunk 1]
```diff
@@ -35,14 +37,35 @@ export function RobotServerVersion({
...
+      robot != null &&
+      robot.status !== UNREACHABLE ? (
+        <Portal level="top">
+          <UpdateBuildroot
+            robot={robot}
+            close={() => setShowSoftwareUpdateModal(false)}
+          />
+        </Portal>
+      ) : null}
       {autoUpdateAction !== 'reinstall' && robot != null ? (
```
Comment (koji) [inline app/src/organisms/Devices/RobotSettings/AdvancedTab/RobotServerVersion.tsx]: Currently RobotSettings checks two thing (useCurrentRunId() and useAllSessionsQuery() ) to prevent unexpected issue. This component also needs to check them. 
When the robot isn't used by anyone or by any actions, we can show the banner. 
**Already talked about this with Brian**

`useIsRobotBusy` checks `/runs` and `/sessions` and return boolean.
```ts
import { useRobot, useIsRobotBusy } from '../../hooks'
const isBusy = useIsRobotBusy()
```

```suggestion
      {autoUpdateAction !== 'reinstall' && robot != null && !isBusy ? (
```

File: app/src/organisms/Devices/RobotCard.tsx [hunk 2]
```diff
@@ -19,6 +19,8 @@ import { getModuleDisplayName } from '@opentrons/shared-data'
 import OT2_PNG from '../../assets/images/OT2-R_HERO.png'
 import { StyledText } from '../../atoms/text'
 import { UNREACHABLE } from '../../redux/discovery'
+import { Portal } from '../../App/portal'
+import { UpdateBuildroot } from '../../pages/Robots/RobotSettings/UpdateBuildroot'
```
Comment (koji) [inline app/src/organisms/Devices/RobotCard.tsx]: Should we move this component to `organisms/Devices/RobotSettings` for #10385?

CC @b-cooper @brenthagen

**Review by koji — CHANGES_REQUESTED** [review]
Overall changes look good to me.
Need a small update.

File: app/src/organisms/Devices/RobotOverview.tsx [hunk 3]
```diff
@@ -49,70 +50,95 @@ export function RobotOverview({
...
+        <Portal level="top">
+          <UpdateBuildroot
+            robot={robot}
+            close={() => setShowSoftwareUpdateModal(false)}
+          />
+        </Portal>
+      ) : null}
+      <Flex
+        alignItems={ALIGN_CENTER}
+        backgroundColor={C_WHITE}
```
Comment (koji) [inline app/src/organisms/Devices/RobotOverview.tsx]: I guess changing the old color const to the latest would be good.

File: app/src/organisms/Devices/RobotSettings/AdvancedTab/RobotServerVersion.tsx (hunk 1 above)
Comment (jerader) [reply app/src/organisms/Devices/RobotSettings/AdvancedTab/RobotServerVersion.tsx]: Thanks for letting me know! Adding it now

**Review by koji — APPROVED** [review]
🚀 The changes look good!
Thank you for moving `UpdateBuildroot` into `RobotSettings`!
