### PR TITLE
fix(app): 6.0 feedback design QA T1 protocols landing page

### LINKED ISSUE #10208: 6.0 Feedback: Design QA: T1 Protocols Landing Page #10153
### Overview

Round 1 Feedback for Protocol Details page

### Current Behavior

n/a

### Expected Behavior

Link to view the annotated screenshot and side by side comparison to the intended design [on Figma](https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=11331%3A330817)

- [X] (1) Update styling of button to reflect our secondary style (no fill, update all states)
- [x] (2) Missing 'sort by' functionality
- [x] (3) Need 4px padding in between each card
- [X] (4) should be our p, semibold in dark-black #16212D
- [x] (5) should b our "link/secondary/grey/external" link styling which relies on our label font styling. Make sure to have all the states (currently missing them)
- [x] (6) center align the external svg icon and the text. Icon should be 12px, which is the same line height as the label text. 
- [x] (7) Need to align last updated text with design. Make sure it's follows the "styling/last-updated" style we have defined and in the correct location (fixed to the right hand side of the card)
- [x] (8) All text should be our dark-black #16212D, except for some the h6 headers, last updated date,  and links. 
- [x] (9) These h6's should be our dark-grey/enabled #707075, letter-spacing: 1%
- [x] (10) Can't figure out the flex box settings, but when the viewport is at 800px width, these columns should be able to hold the max number of characters without going onto two rows. (probably the "P1000 Single-Channel GEN2"). Not sure if it's because 'last updated' isn't tucked to the right? 
- [x] (11) The opened menu should be 4px below the menu overflow icon
- [x] (12) Menu overflow icon behavior [Loom video explaining](https://www.loom.com/share/3c49f4c275874210ae6dd2048a712d54)(please contact me if you have questions)
- [ ] (13) SVG adjustment. [Loom video explaining](https://www.loom.com/share/0c675ba03b80459f8c69db76e965e77b) (please contact me when you hit this, i think we'll need to work close together to solve)
- [x] (14) Update size of the spinner
- [x] (15) Update colour of the 'loading data...'
- [x] (16) Update to our h1 style, keeping it mind the colour should also be our 'dark-black'
- [x] (17) Update to our p style, make sure it's 'dark-black' colour
- [x] (18) Update to our primary button style 
- [x] (19) Update 'file_drop_zone' to our updated component in the design system 
- [x] (20) This entire section should be centered within the inner frame (see the original design to the left in Figma)
- [x] (21) should be the same amount of margin we have after the protocol cards when there's content (40px)

Screen Shot 2022-05-04 at 12 02 59 PM
Screen Shot 2022-05-04 at 2 41 49 PM

### Steps To Reproduce

_No response_

### Operating system

_No response_

### Robot setup or anything else?

_No response_

### PR DESCRIPTION
**Pull request by aptrons22**
# Overview
The PR will fix #10208

- [X] (1) Update styling of button to reflect our secondary style (no fill, update all states)
- [x] (2) Missing 'sort by' functionality
- [x] (3) Need 4px padding in between each card
- [X] (4) should be our p, semibold in dark-black #16212D
- [x] (5) should b our "link/secondary/grey/external" link styling which relies on our label font styling. Make sure to have all the states (currently missing them)
- [x] (6) center align the external svg icon and the text. Icon should be 12px, which is the same line height as the label text. 
- [x] (7) Need to align last updated text with design. Make sure it's follows the "styling/last-updated" style we have defined and in the correct location (fixed to the right hand side of the card)
- [x] (8) All text should be our dark-black #16212D, except for some the h6 headers, last updated date,  and links. 
- [x] (9) These h6's should be our dark-grey/enabled #707075, letter-spacing: 1%
- [x] (10) Can't figure out the flex box settings, but when the viewport is at 800px width, these columns should be able to hold the max number of characters without going onto two rows. (probably the "P1000 Single-Channel GEN2"). Not sure if it's because 'last updated' isn't tucked to the right? 
- [x] (11) The opened menu should be 4px below the menu overflow icon
- [x] (12) Menu overflow icon behavior [Loom video explaining](https://www.loom.com/share/3c49f4c275874210ae6dd2048a712d54)(please contact me if you have questions)
- [x] (14) Update size of the spinner
- [x] (15) Update colour of the 'loading data...'
- [x] (16) Update to our h1 style, keeping it mind the colour should also be our 'dark-black'
- [x] (17) Update to our p style, make sure it's 'dark-black' colour
- [x] (18) Update to our primary button style 
- [x] (19) Update 'file_drop_zone' to our updated component in the design system 
- [x] (20) This entire section should be centered within the inner frame (see the original design to the left in Figma)
- [x] (21) should be the same amount of margin we have after the protocol cards when there's content (40px)

# Changelog
- The following list above has been completed with the exception of task 13.
- Styling of icons has been modified
- Styling of text colors
- Icon behaviors has been revised

# Review requests

# Risk assessment
low

### CODE REVIEW

File: app/src/organisms/ProtocolsLanding/EmptyStateLinks.tsx [hunk 1]
```diff
@@ -40,37 +40,48 @@ export function EmptyStateLinks(props: Props): JSX.Element | null {
       <Flex justifyContent={JUSTIFY_START} flexDirection={DIRECTION_ROW}>
         <Link
           fontSize={FONT_SIZE_CAPTION}
-          color={C_MED_GRAY}
+          css={TYPOGRAPHY.darkLinkPSemiBold}
+          color={COLORS.darkBlack}
           href={PROTOCOL_LIBRARY_URL}
           id={'EmptyStateLinks_protocolLibraryButton'}
           marginRight={SPACING.spacing3}
+          opacity="0.7rem"
```
Comment (b-cooper) [inline app/src/organisms/ProtocolsLanding/EmptyStateLinks.tsx]: Opacity takes a unitless value so this `rem` is doing nothing at best.  Also, do we actually need these components to be semi-transparent or do we need the color of the to be updated to something lighter?

File: app/src/organisms/ProtocolsLanding/ProtocolCard.tsx [hunk 2]
```diff
@@ -230,7 +231,7 @@ function AnalysisInfo(props: AnalysisInfoProps): JSX.Element {
                         <ModuleIcon
                           key={index}
                           moduleType={moduleType}
-                          height="1rem"
+                          height="0.01rem"
```
Comment (b-cooper) [inline app/src/organisms/ProtocolsLanding/ProtocolCard.tsx]: This seems wrong, this equals a small fraction of a pixel.

File: components/src/primitives/Btn.tsx [hunk 3]
```diff
@@ -162,6 +162,14 @@ export const NewSecondaryBtn: BtnComponent = styled(SecondaryBtn)`
     box-shadow: 0px 3px 6px 0px rgba(0, 0, 0, 0.23);
   }
 
+  &:pressed,
```
Comment (b-cooper) [inline components/src/primitives/Btn.tsx]: is this a pseudoclass? I don't think this is doing anything

File: app/src/organisms/ProtocolsLanding/EmptyStateLinks.tsx (hunk 1 above)
Comment (aptrons22) [reply app/src/organisms/ProtocolsLanding/EmptyStateLinks.tsx]: I will follow-up with Mel.

File: components/src/primitives/Btn.tsx (hunk 3 above)
Comment (aptrons22) [reply components/src/primitives/Btn.tsx]: The box-shadow code has not been changed.  I only added the pressed state.  I will follow-up with Mel to be sure.  Thanks

File: app/src/atoms/MenuList/OverflowBtn.tsx [hunk 4]
```diff
@@ -7,20 +7,26 @@ const overflowButtonStyles = css`
...
+    fill: ${COLORS.darkBlack};
   }
 
   &:focus {
-    box-shadow: 0 0 0 3px ${COLORS.warning};
+    box-shadow: 0 0 0 3px ${COLORS.darkGreyPressed};
+  }
+
+  &:enabled,
+  &.enabled {
```
Comment (shlokamin) [inline app/src/atoms/MenuList/OverflowBtn.tsx]: i think you just need the pseudoclass right? do you need the standard class selector too? https://developer.mozilla.org/en-US/docs/Web/CSS/:enabled

File: app/src/organisms/ProtocolSetup/RunSetupCard/LabwareSetup/index.tsx [hunk 5]
```diff
@@ -30,6 +29,7 @@ import {
   FONT_WEIGHT_SEMIBOLD,
   C_NEAR_WHITE,
   SPACING_7,
+  NewSecondaryBtn,
```
Comment (shlokamin) [inline app/src/organisms/ProtocolSetup/RunSetupCard/LabwareSetup/index.tsx]: was this move in import intentional?

File: app/src/organisms/ProtocolsLanding/EmptyStateLinks.tsx (hunk 1 above)
Comment (shlokamin) [reply app/src/organisms/ProtocolsLanding/EmptyStateLinks.tsx]: yeah lets remove the `rem` unit, it is not a unit for opacity. check this out @aptrons22: https://developer.mozilla.org/en-US/docs/Web/CSS/opacity

File: app/src/organisms/ProtocolsLanding/EmptyStateLinks.tsx [hunk 6]
```diff
@@ -40,37 +40,48 @@ export function EmptyStateLinks(props: Props): JSX.Element | null {
...
           external
         >
           {t('browse_protocol_library')}
           <Icon
             name={'open-in-new'}
             marginLeft={SPACING.spacing2}
-            size="10px"
+            size="0.5rem"
+            opacity="0.7rem"
```
Comment (shlokamin) [inline app/src/organisms/ProtocolsLanding/EmptyStateLinks.tsx]: same thing here, `rem` is not a unit for opacity

File: components/src/ui-style-constants/typography.ts [hunk 7]
```diff
@@ -120,3 +120,14 @@ export const linkPSemiBold = css`
...
+export const darkLinkPSemiBold = css`
+  font-size: ${fontSizeP};
+  font-weight: ${fontWeightSemiBold};
+  line-height: ${lineHeight20};
+  color: ${COLORS.darkBlack};
+
+  &:hover {
+    opacity: 70%;
+  }
+`
```
Comment (koji) [inline components/src/ui-style-constants/typography.ts]: As I told you Wednesday, this is opposite to the design. Please check the link I put.

https://www.figma.com/file/l7BAJAGICr10ELsSqQD0Sr?node-id=2186:85155#202247876

File: app/src/organisms/ProtocolsLanding/EmptyStateLinks.tsx [hunk 8]
```diff
@@ -40,37 +40,48 @@ export function EmptyStateLinks(props: Props): JSX.Element | null {
...
         </Link>
         <Link
           fontSize={FONT_SIZE_CAPTION}
-          color={C_MED_GRAY}
+          css={TYPOGRAPHY.darkLinkPSemiBold}
+          color={COLORS.darkBlack}
           marginRight={SPACING.spacing3}
           href={PROTOCOL_DESIGNER_URL}
           id={'EmptyStateLinks_protocolDesignerButton'}
+          opacity="0.7rem"
```
Comment (shlokamin) [inline app/src/organisms/ProtocolsLanding/EmptyStateLinks.tsx]: same thing here

File: app/src/organisms/ProtocolsLanding/EmptyStateLinks.tsx [hunk 9]
```diff
@@ -40,37 +40,48 @@ export function EmptyStateLinks(props: Props): JSX.Element | null {
...
-            size="10px"
-          />
+          <Flex alignItems={ALIGN_CENTER} css={TYPOGRAPHY.darkLinkPSemiBold}>
+            {t('launch_protocol_designer')}
+
+            <Icon
+              name={'open-in-new'}
+              marginLeft={SPACING.spacing2}
+              size="0.5rem"
+              opacity="0.7rem"
```
Comment (shlokamin) [inline app/src/organisms/ProtocolsLanding/EmptyStateLinks.tsx]: same thing here

File: app/src/organisms/ProtocolsLanding/EmptyStateLinks.tsx [hunk 10]
```diff
@@ -79,7 +90,8 @@ export function EmptyStateLinks(props: Props): JSX.Element | null {
           <Icon
             name={'open-in-new'}
             marginLeft={SPACING.spacing2}
-            size="10px"
+            size="0.5rem"
+            opacity="0.7rem"
```
Comment (shlokamin) [inline app/src/organisms/ProtocolsLanding/EmptyStateLinks.tsx]: same thing here

File: app/src/organisms/ProtocolSetup/RunSetupCard/LabwareSetup/index.tsx (hunk 5 above)
Comment (koji) [inline app/src/organisms/ProtocolSetup/RunSetupCard/LabwareSetup/index.tsx]: I think this change won't show up if you move `NewSecondaryBtn` to the line 16

File: app/src/organisms/ProtocolsLanding/ProtocolList.tsx [hunk 11]
```diff
@@ -177,7 +177,7 @@ export function ProtocolList(props: ProtocolListProps): JSX.Element | null {
       <StyledText as="p" paddingBottom={SPACING.spacing4}>
         {t('all_protocols')}
       </StyledText>
-      <Flex flexDirection="column">
+      <Flex flexDirection="column" marginBottom="2.5rem">
```
Comment (shlokamin) [inline app/src/organisms/ProtocolsLanding/ProtocolList.tsx]: when possible we try to use the standard spacings in `components/src/styles/spacing.ts` to try to conform to the same style standards across the codebase. there are definitely edge cases where we'll deviate, but we generally try to keep it consistent

File: components/src/primitives/Btn.tsx (hunk 3 above)
Comment (shlokamin) [reply components/src/primitives/Btn.tsx]: as far as i can tell this is not doing anything. also i dont know if `pressed` is a valid pseudo class. did you mean `active`?  https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes

Comment (shlokamin) [reply components/src/primitives/Btn.tsx]: oh, i think what happened is there is a duplicate `&:pressed` on line 165. but im still not sure this is a valid pseudo class, or at least it doesn't show up in the docs

File: app/src/organisms/ProtocolSetup/RunSetupCard/LabwareSetup/index.tsx (hunk 5 above)
Comment (b-cooper) [reply app/src/organisms/ProtocolSetup/RunSetupCard/LabwareSetup/index.tsx]: Also, this is a legacy file that is slated for deletion in #10385.

Comment (koji) [reply app/src/organisms/ProtocolSetup/RunSetupCard/LabwareSetup/index.tsx]: @shlokamin I think it was accidental since yesterday's CI lint error was caused by the missing of NewSecondaryBtn tag. I guess when she modified the code, mistakenly removed that line.

File: app/src/organisms/ProtocolsLanding/ProtocolCard.tsx (hunk 2 above)
Comment (aptrons22) [reply app/src/organisms/ProtocolsLanding/ProtocolCard.tsx]: Fixed

File: app/src/organisms/ProtocolSetup/RunSetupCard/LabwareSetup/index.tsx (hunk 5 above)
Comment (aptrons22) [reply app/src/organisms/ProtocolSetup/RunSetupCard/LabwareSetup/index.tsx]: Yes.

File: app/src/organisms/ProtocolsLanding/ProtocolCard.tsx (hunk 2 above)
Comment (aptrons22) [reply app/src/organisms/ProtocolsLanding/ProtocolCard.tsx]: Corrected now.

File: components/src/ui-style-constants/typography.ts [hunk 12]
```diff
@@ -128,6 +128,6 @@ export const darkLinkPSemiBold = css`
   color: ${COLORS.darkBlack};
 
   &:hover {
-    opacity: 70%;
+    opacity: 100%;
```
Comment (b-cooper) [inline components/src/ui-style-constants/typography.ts]: the opacity property expects a value from 0 to 1. This should probably be `1` instead of `100%`

Comment (aptrons22) [reply components/src/ui-style-constants/typography.ts]: Corrected now.  Thanks

**Review by b-cooper — APPROVED** [review]
Code changes look good.  Good to merge pending design approval

File: components/src/ui-style-constants/typography.ts [hunk 13]
```diff
@@ -120,3 +120,14 @@ export const linkPSemiBold = css`
...
 `
+
+export const darkLinkPSemiBold = css`
+  font-size: ${fontSizeP};
+  font-weight: ${fontWeightSemiBold};
+  line-height: ${lineHeight20};
+  color: ${COLORS.darkBlack};
+
+  &:hover {
+    opacity: 1%;
```
Comment (koji) [inline components/src/ui-style-constants/typography.ts]: I think this should be 1.0  instead of `1%`

Comment (aptrons22) [reply components/src/ui-style-constants/typography.ts]: Corrected.  Thanks

**Comment by mmencarelli** [comment]
Round 2 feedback for T1 Protocol Page. [Link to annotated frame in figma](https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=11331%3A330817). 

- [x] (1) Missing the enabled state (no fill background), and needs a hover state linked up. 
- [x] (2) Remove the white fill from the button
- [x] (3) When I press on the button, i get the orange outline. The orange outline is only the focus state and should only appear when a user tabs through all the links using 'tab' on their keyboard. So remove this please! (Already Done)
- [x] (4) update 'sort by' text to our `darkGreyEnabled`
- [x] (5) Looks like we're missing the hover state for the protocol cards. Check the design system for info 
- [x] (7) Update this text across all cards to our `darkGreyEnabled`
- [x] (8) The columns should have a min-width of 170px so regardless of what content is in them, the columns will always align. These columns should be responsive when the user shrinks the viewport.
- [x] (9) Update both of these so it's our label text in `darkGreyEnabled`. No uppercase here
- [x] (10) Update text should align to the bottom of the other containers to the left. 
- [x] (11) Update to be our `p-semibold`, currently it's bold 
- [x] (12) Update to our `label-semibold` styling. 
- [x] (13) Double check the colour of the text and the icon. They should be the same
- [x] (14) Update the spacing here between header and text below to .25 rem


Screen Shot 2022-06-06 at 2 02 01 PM

**Comment by aptrons22** [comment]
@mmencarelli I'm working on this.  Thanks
