### PR TITLE
fix(app): See How Robot Calibration Works Modal

### LINKED ISSUE #10406: 6.0 Feedback:  How Robot Calibration works modal takes up 100% of the screen
### Overview

no matter what size your app is, the how robot calibration works modal takes up 100% of the screen. this modal should follow our other modal logic.

### Current Behavior

Screen Shot 2022-05-23 at 4 07 58 PM
Screen Shot 2022-05-23 at 4 07 50 PM

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Operating system

_No response_

### Robot setup or anything else?

_No response_

### PR DESCRIPTION
**Pull request by koji**
# Overview
This will fix #10406

Screen Shot 2022-05-23 at 9 15 52 PM

# Changelog
- Updated components/constants in the component

# Review requests

# Risk assessment
low

### CODE REVIEW

**Comment by mmencarelli** [comment]
Round 1 feedback on modal

* I don't think we had a design in our component library for this modal so there are a few things I've had to change. 

View the annotated frame [on figma](https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=12771%3A272468)

- [x] (1) Update the header to reflect our modal header styling. Font header size should be 14px 
- [x] (2) Update to our 'btn-icon/close' component (including states!)
- [x] (3) Missing the line 
- [x] (4) Update margin to 24px 
- [x] (5) 1rem margin between p and the link 
- [x] (6) 0.125 margin between p heading and p text in all three paragraphs 
- [x] (7) Updated the formatting of this content (sorry that wasn't in the original design, just updated!)
- [x] (8) Missing the scrolly bar when scrolling 
- [x] (9) Update the styling in this button to reflect our primary button component
- [x] (10) Let's give this modal a max-height of 450px
- [x] (11) Use the overflow CTA container (including the white gradient) to hide content

Screen Shot 2022-05-26 at 10 09 19 AM

File: app/src/atoms/Modal/index.tsx [hunk 1]
```diff
@@ -90,7 +90,8 @@ export const Modal = (props: ModalProps): JSX.Element => {
 
   return (
     <BaseModal
-      width={'31.25rem'}
+      width="31.25rem"
+      maxHeight="28.125rem"
```
Comment (jerader) [inline app/src/atoms/Modal/index.tsx]: I feel a bit weird giving the `Modal` component a max height because this will affect all modals. Can you add this max height only to this Robot Calibration modal?

File: app/src/atoms/Modal/index.tsx [hunk 2]
```diff
@@ -26,6 +26,7 @@ export interface ModalProps extends BaseModalProps {
   title?: React.ReactNode
   children?: React.ReactNode
   icon?: IconProps
+  maxHeight?: string
```
Comment (koji) [inline app/src/atoms/Modal/index.tsx]: Add this to keep the space between the `Close` button and the Modal's bottom.

Comment (b-cooper) [reply app/src/atoms/Modal/index.tsx]: You shouldn't need to add this to the type interface explicitly.  Because this interface extends `BaseModalProps` and the `BaseModalProps` extends `StyleProps` which should include `maxHeight`

**Review by b-cooper — APPROVED** [review]
🦒
