### PR TITLE
fix(app): protocol run page design qa

### LINKED ISSUE #10908: 6.0 Feedback: [Design QA] T3 Protocol Run Page
### Overview

**This is not a full design QA for T3 Protocol Run page. Due to time constraints, I'm only including what needs to be done for 6.0**

### Current Behavior

_No response_

### Expected Behavior

[Link to annotated figma frame ](https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=14699%3A293844)

- [x] (1) I believe we changed all instances of "run ID" to 'run'? Might want to double check with @b-cooper 
- [x] (2) Left align "protocol end" column with the column above "status" 
- [x] (3) Few things here—remove the white bg on this button. Also the hover state is displaying the non-error version. Aka, it should not turn blue on hover 
- [x] (4) Needs hover state on these tabs. I've put this in 2 other PR's in the past few days so maybe see if someone has already done this and link it up with their work? 
- [x] (5) Can we set a max-width for the deck map in both labware and module setup to be 740px? Responsive otherwise as the user scales the viewport down. If we set a max-width, then just make sure it stays centered within the frame. Same thing on labware setup
- [x] (6) Update size of icon to be 1rem
- [x] (7) Update font styling to be h3 semibold 
- [x] (8) Update this tertiary button to reflect our design system. (update text to be label-semibold, remove box shadow, include various states incl hover and focusVisible) 
- [x] (9) Make sure it's 1.5rem margin below. Looks like there's extra margin on the button 
- [x] (10) Make sure there's 40px margin between content and button
- [x] (11) remove the ability for these buttons to text wrap
- [x] (12) has this copy changed? If so, please let me know as I'll need to update designs 
- [x] (13) Update styling, make sure the hover state is in there 

Screen Shot 2022-06-24 at 1 18 24 PM
Screen Shot 2022-06-24 at 1 20 26 PM
Screen Shot 2022-06-24 at 1 20 32 PM
Screen Shot 2022-06-24 at 1 20 37 PM

### Steps To Reproduce

_No response_

### Operating system

_No response_

### Robot setup or anything else?

_No response_

### PR DESCRIPTION
**Pull request by vabruzzo**
# Overview
Fixes various styling on protocol run page.
Closes #10908

# Changelog
- small pixel pushing and color chang4es to make page consistent with degisn
- switch to `display:"grid"` in protocol run header to align columns

# Review requests
- browse protocol run page to confirm style changes  address ticket

# Risk assessment
Low

### CODE REVIEW

File: app/src/organisms/Devices/ProtocolRun/ProtocolRunHeader.tsx [hunk 1]
```diff
@@ -398,59 +399,64 @@ export function ProtocolRunHeader({
 
   const protocolRunningContent: JSX.Element | null =
     runStatus != null ? (
-      <Flex
+      <Box
         backgroundColor={COLORS.lightGrey}
-        justifyContent={JUSTIFY_SPACE_BETWEEN}
+        display="grid"
```
Comment (vabruzzo) [inline app/src/organisms/Devices/ProtocolRun/ProtocolRunHeader.tsx:395]: We currently use `display="grid"` in one other component and haven't abstracted it out yet to its own component. The one prop it will usually receive is `gridTemplateColumns` and the value for that is not very easy to turn into a variable as each situation will likely require its own value. I.e. I'm not sure it would make sense to have a variable for something like `3fr` or `4fr` unless we use a universal grid system with 12 columns or something.

File: app/src/organisms/Devices/ProtocolRun/ProtocolRunHeader.tsx [hunk 2]
```diff
@@ -592,12 +598,7 @@ export function ProtocolRunHeader({
             startRun={play}
           />
         )}
-        <Flex
-          justifyContent={'flex-end'}
-          flexDirection={DIRECTION_ROW}
-          gridGap={SPACING.spacingSM}
-          width={SIZE_5}
```
Comment (vabruzzo) [inline app/src/organisms/Devices/ProtocolRun/ProtocolRunHeader.tsx:599]: Using grid here lets us avoid these hardcoded `width`s and `min-width`s.

File: app/src/organisms/ProtocolSetup/RunSetupCard/ModuleSetup/Banner/Banner.tsx [hunk 3]
```diff
@@ -93,17 +97,15 @@ export const BannerItem = (props: BannerItemProps): JSX.Element => {
...
         </Text>
-        <NewPrimaryBtn
-          backgroundColor={COLORS.blue}
-          borderRadius={SPACING.spacingM}
-          textTransform={TEXT_TRANSFORM_NONE}
-          css={TYPOGRAPHY.labelRegular}
-          marginBottom={SPACING.spacingXL}
+        <TertiaryButton
+          alignSelf={ALIGN_FLEX_START}
+          paddingY={SPACING.spacing3}
```
Comment (vabruzzo) [inline app/src/organisms/ProtocolSetup/RunSetupCard/ModuleSetup/Banner/Banner.tsx]: Other buttons have this padding in the component itself, but `TertiaryButton` has a different padding: `adding: 0.375rem 0.75rem;`, does anyone know if we need that different padding or if I can change the button itself?

**Review by jerader — COMMENTED** [review]
I don't think this was introduced by this PR but just noticed that the background color of the `Cancel Run` button is undefined or transparent. We probably want it to be white

Screen Shot 2022-07-06 at 2 30 27 PM

**Review by brenthagen — APPROVED** [review]

File: app/src/organisms/Devices/ProtocolRun/ProtocolRunHeader.tsx [hunk 4]
```diff
@@ -398,59 +395,64 @@ export function ProtocolRunHeader({
...
-        {showCancelButton ? (
-          <SecondaryButton
-            color={COLORS.errorText}
-            padding={`${SPACING.spacingSM} ${SPACING.spacing4}`}
-            onClick={handleCancelClick}
-            id="ProtocolRunHeader_cancelRunButton"
-            disabled={isClosingCurrentRun}
+        <Box>
+          <StyledText
+            textTransform={TEXT_TRANSFORM_UPPERCASE}
```
Comment (koji) [inline app/src/organisms/Devices/ProtocolRun/ProtocolRunHeader.tsx]: Let's use `{TYPOGRAPHY.textTransformUppercase}` instead `{TEXT_TRANSFORM_UPPERCASE}`

File: app/src/organisms/Devices/ProtocolRun/ProtocolRunHeader.tsx [hunk 5]
```diff
@@ -398,59 +395,64 @@ export function ProtocolRunHeader({
...
           >
-            {t('cancel_run')}
-          </SecondaryButton>
-        ) : null}
-      </Flex>
+            {t('protocol_start')}
+          </StyledText>
+          <StyledText
+            css={TYPOGRAPHY.pRegular}
+            color={COLORS.darkBlack}
```
Comment (koji) [inline app/src/organisms/Devices/ProtocolRun/ProtocolRunHeader.tsx]: We can remove this line since default text color is `darkBlack`

File: app/src/organisms/Devices/ProtocolRun/ProtocolRunHeader.tsx [hunk 6]
```diff
@@ -398,59 +395,64 @@ export function ProtocolRunHeader({
...
+            id="ProtocolRunHeader_protocolStart"
+          >
+            {startedAtTimestamp}
+          </StyledText>
+        </Box>
+        <Box>
+          <StyledText
+            textTransform={TEXT_TRANSFORM_UPPERCASE}
```
Comment (koji) [inline app/src/organisms/Devices/ProtocolRun/ProtocolRunHeader.tsx]: same as above

```suggestion
            textTransform={TYPOGRAPHY.textTransformUppercase}
```

File: app/src/organisms/Devices/ProtocolRun/ProtocolRunHeader.tsx [hunk 7]
```diff
@@ -398,59 +395,64 @@ export function ProtocolRunHeader({
...
+            color={COLORS.darkGreyEnabled}
+            css={TYPOGRAPHY.h6Default}
+            paddingBottom={SPACING.spacing2}
+          >
+            {t('protocol_end')}
+          </StyledText>
+          <StyledText
+            css={TYPOGRAPHY.pRegular}
+            color={COLORS.darkBlack}
```
Comment (koji) [inline app/src/organisms/Devices/ProtocolRun/ProtocolRunHeader.tsx]: same as above

File: app/src/organisms/ProtocolSetup/RunSetupCard/ModuleSetup/Banner/Banner.tsx (hunk 3 above)
Comment (koji) [reply app/src/organisms/ProtocolSetup/RunSetupCard/ModuleSetup/Banner/Banner.tsx]: @mmencarelli thought?

File: components/src/hardware-sim/Deck/RobotWorkSpace.tsx [hunk 8]
```diff
@@ -64,6 +64,7 @@ export function RobotWorkSpace(props: RobotWorkSpaceProps): JSX.Element | null {
       className={cx(styles.robot_work_space, props.className)}
       viewBox={viewBox || wholeDeckViewBox}
       ref={wrapperRef}
+      style={{ margin: '0 auto', maxWidth: '740px' }}
```
Comment (koji) [inline components/src/hardware-sim/Deck/RobotWorkSpace.tsx]: for consistency maybe `rem`?    `46.25rem`

**Review by koji — APPROVED** [review]
Looks good to me.
I just left a couple of comments.

File: app/src/organisms/Devices/ProtocolRun/ProtocolRunHeader.tsx (hunk 4 above)
Comment (vabruzzo) [reply app/src/organisms/Devices/ProtocolRun/ProtocolRunHeader.tsx]: > I don't think this was introduced by this PR but just noticed that the background color of the `Cancel Run` button is undefined or transparent. We probably want it to be white
> 
> Screen Shot 2022-07-06 at 2 30 27 PM

one of the items in the ticket is to remove the white background, ill double check

File: app/src/organisms/Devices/ProtocolRun/ProtocolRunHeader.tsx (hunk 1 above)
Comment (mmencarelli) [reply app/src/organisms/Devices/ProtocolRun/ProtocolRunHeader.tsx:395]: We currently use a system of 8 columns in the designs. I haven't been super strict with it, so if dev's want to start implementing this I'd need some time to make sure it's properly utilized across all pages. Let me know if this is something the dev team would like to proceed in!
Screen Shot 2022-07-07 at 8 21 15 AM

File: app/src/organisms/ProtocolSetup/RunSetupCard/ModuleSetup/Banner/Banner.tsx (hunk 3 above)
Comment (mmencarelli) [reply app/src/organisms/ProtocolSetup/RunSetupCard/ModuleSetup/Banner/Banner.tsx]: I think I've found the padding you're seeing in the app on this button. It should have a padding of .5rem top and bottom, and then 1rem left/right. Let me know if this doesn't answer your q!

**Comment by mmencarelli** [comment]
> I don't think this was introduced by this PR but just noticed that the background color of the `Cancel Run` button is undefined or transparent. We probably want it to be white
> 
> Screen Shot 2022-07-06 at 2 30 27 PM

negatory! The outlined buttons do not have a fill

**Comment by mmencarelli** [comment]
Looks great! If i could....I missed this one, could I add 1 thing: 

- Bump the size of these +/- icons to be 24px, and also make sure to add the hover states! 

Other than that, solid.

File: app/src/organisms/Devices/ProtocolRun/ProtocolRunHeader.tsx (hunk 1 above)
Comment (koji) [reply app/src/organisms/Devices/ProtocolRun/ProtocolRunHeader.tsx:395]: @mmencarelli 
the dev team has been talking about bringing `grid` to the code base. I think for the team, 12 columns is good.
popular open-source UI components are based on a 12-column such as MUI, Bootstrap, Shopify/Polaris, etc.
