### PR TITLE
fix(app): rm analyzing state in run header for historical runs

### LINKED ISSUE #10740: 6.0 Feedback:  When navigating to run log of a protocol "analyzing on robot" spinner is shown
### Overview

https://user-images.githubusercontent.com/502770/173441680-62d7a731-ddb4-4f90-908f-9217c50ed2ad.mp4

FIX: currently we are displaying the loading "analyzing on robot" CTA copy if the protocol data from the robot is `null`. We should be able to further differentiate between a protocol record that has a "pending" analysis, and a protocol record that hasn't loaded yet.  This will likely require adjusting or skirting the `useProtocolDetailsForRun` hook where we fetch the analysis from the robot.

### Current Behavior

_No response_

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Operating system

_No response_

### Robot setup or anything else?

_No response_

### PR DESCRIPTION
**Pull request by vabruzzo**
# Overview
Remove the analyzing state for historical runs in header. Change X icon to spinner in run header banner after clicked.
Closes #10740, #10904.

# Changelog
- adds `isProtocolAnalyzing` to `useProtocolDetailsForRun` to use for rendering analyzing state on new runs in header
- adds `isCloseActionLoading` to `Banner` component so we can render loading spinner instead of X icon after an async close action has been fired via banner

# Review requests
- confirm that historical run detail page does not render analyzing on robot state in button
- confirm that when a protocol is analyzing for new runs that state is reflected
- confirm that after clicking X on banner for completed or failed run on details page the banner renders spinner until action is complete

# Risk assessment
Low

### CODE REVIEW

File: app/src/atoms/Banner/index.tsx [hunk 1]
```diff
@@ -31,6 +32,8 @@ export interface BannerProps extends StyleProps {
   onCloseClick?: (() => unknown) | React.MouseEventHandler<HTMLButtonElement>
   /** Override the default Alert Icon */
   icon?: IconProps
+  /** some banner onCloseClicks fire events, this allows a spinner after click but before event finishes */
```
Comment (b-cooper) [inline app/src/atoms/Banner/index.tsx:35]: good idea 💡

**Review by b-cooper — APPROVED** [review]
Code changes look good. If the `protocolData` is undefined (for instance when a historical run page is loading), this will disable the button, will the button text just correspond to whatever the action would be after the loading completes?

**Review by brenthagen — APPROVED** [review]
makes sense to me!

**Comment by vabruzzo** [comment]
> Code changes look good. If the `protocolData` is undefined (for instance when a historical run page is loading), this will disable the button, will the button text just correspond to whatever the action would be after the loading completes?

yeah, so long as the data is as we expect it, which is the case in my testing. i.e. a historical run will say 'Run again'
