### PR TITLE
fix(app): Ensure cal check exit button on the title modal only displays if there is no primary exit

### LINKED ISSUE #5990: bug: calibration check: exit button should not display in the per-step error screen
Screen Shot 2020-06-23 at 4 39 28 PM
In the above step, because there's a primary button exit, we should not display an exit button in the top left.

### PR DESCRIPTION
**Pull request by Laura-Danielle**
# Overview

Closes #5990. For the 'bad calibration' displays on the height and the XY check modals, there were two exit button options being displayed. We generate a results report when a user presses the primary exit button so we want to make sure they cannot exit the modal using the back exit button.

# Changelog

- Set `shouldDisplayTitleBarExit` to false if a value on a check exceeds the threshold 

# Review requests

Test on your robot.

1. Force calibration check to fail for both a height and an XY check.
     a. You should see that no exit button exists in the top left corner.
2. Force calibration check to pass for both a height and an XY check.
     a. You should see that the exit button in the top left corner is still there.

# Risk assessment

Low, just removing an extraneous exit button for cal check.

### CODE REVIEW

File: app/src/components/CheckCalibration/index.js [hunk 1]
```diff
@@ -248,6 +248,9 @@ export function CheckCalibration(props: CheckCalibrationProps): React.Node {
         hasTwoPipettes
       )
       const comparison = comparisonsByStep[currentStep]
+      if (comparison?.exceedsThreshold) {
```
Comment (sfoster1) [inline app/src/components/CheckCalibration/index.js:251]: This doesn't quite feel like the right way to do this. Looks like the problem you're facing is that the child component is what decides whether to pop the exit screen - maybe those child components that can short-circuit the flow can take callbacks? Like make `CheckXYPoint` and `CheckHeight`s props take a `setDisplayExit: (bool) => null` or something and pass them `displayExit => { shouldDisplayTitleBarExit = displayExit }`?

**Review by sfoster1 — CHANGES_REQUESTED** [review]

**Review by sfoster1 — APPROVED** [review]
Further conversation convinced me!
