### PR TITLE
fix(app): prevent white screen when restarting and closing protocols

### LINKED ISSUE #9082: bug: beta3- App goes blank when Run Again button is clicked
# Overview

Follow up of https://github.com/Opentrons/opentrons/issues/9013 

After starting a protocol and canceling, if a user tries to run again then the app becomes blank intermittantly.

when this occurs, a request in the network logs: `http://192.168.0.24:31950/runs/undefined` can be found, which indicates that after we `un-current` a run, we're not properly transitioning states.

# Steps to reproduce

Upload the attached protocol
Start a run
Cancel the run

Note: this occurs intermittently and is not always reproducible
[simple_transfer_proto.py.zip](https://github.com/Opentrons/opentrons/files/7705629/simple_transfer_proto.py.zip)

### PR DESCRIPTION
**Pull request by shlokamin**
# Overview
This PR adds a null check inside of components that are receiving stale data.

It seems as though we're experiencing a [Zombie Children](https://github.com/reduxjs/react-redux/issues/1556) esque problem, where children are not being unmounted when they should be, and as a result are receiving stale data and erroring out. 

I'm not sure what's causing this, but this quick fix should make the problem go away. There is certainly more work on our end to do in terms of optimizing state updates/network requests, but until we figure out why this is happening this fix shoul do.

closes #9082 and #9083

# Changelog

- Rrevent white screen when restarting and closing protocols

# Review requests

Note — before testing, you'll need to actually build the app locally. This is because the white screen issues only occur on actual builds (not when building on a dev server). Follow the instructions in the `app-shell` `README` (i.e. run `make package` from inside `app-shell`) and open the build that gets generated in `./dist/mac/Opentrons.app/Contents/MacOS/Opentrons`.

Go through the repro steps in the tickets above, you should no longer see whitescreens.
# Risk assessment
Low

### CODE REVIEW

File: app/src/organisms/RunDetails/CommandText.tsx [hunk 1]
```diff
@@ -13,18 +13,17 @@ import { useProtocolDetails } from './hooks'
 
 import { getLabwareLocation } from '../ProtocolSetup/utils/getLabwareLocation'
 import { useLabwareRenderInfoById } from '../ProtocolSetup/hooks'
+import protocolData from '../../../../notify-server/.mypy_cache/3.7/opentrons/protocols/context/protocol.data.json'
```
Comment (shlokamin) [inline app/src/organisms/RunDetails/CommandText.tsx]: oops this somehow snuck in

**Comment by sakibh** [comment]
Just tested this on my robot. I was able to reproduce the bugs in both tickets. Then I rebuilt this branch locally and the white screen behavior on both tickets disappeared. 🚀

**Review by brenthagen — APPROVED** [review]
built and tested locally, both bugs appear to have been resolved
