### PR TITLE
fix(app): disable protocol runs when robot update available

### LINKED ISSUE #10935: Block protocol run when a robot and app are not on the same SW version
When the Opentrons App and an OT-2 are not on the same SW version, disable running a protocol in the following places:

1. Device landing page: on a robot card, disable `Run a protocol` from the overflow menu
2. Device detail page: disable `Run a protocol` on the upper right corner
3. Device detail page: disable `Rerun protocol now` from the overflow menu
4. Run detail page: disable `Run again` on the upper right corner

In all of these scenarios, display a tooltip that says 
> "A software update is available for this robot. Update to run protocols."

### PR DESCRIPTION
**Pull request by vabruzzo**
# Overview
When robot update is available disable run protocol buttons.
Closes #10935.

# Changelog
- disables device landing page robot card run a protocol in the overflow menu
- disables device detail page run a protocol button
- disables device detail page rerun protocol now from the overflow menu
- disables run detail page run again button
- adds tooltip to each of these

# Review requests
Confirm that these items are disabled when robot software update is available

# Risk assessment
Medium, this affects potentially blocking runs, need to ensure logic is sound

### CODE REVIEW

File: app/src/organisms/Devices/HistoricalProtocolRunOverflowMenu.tsx [hunk 1]
```diff
@@ -153,12 +164,18 @@ function MenuDropdown(props: MenuDropdownProps): JSX.Element {
...
+        {...targetProps}
         onClick={handleResetClick}
-        disabled={robotIsBusy}
+        disabled={robotIsBusy || isRobotOnWrongVersionOfSoftware}
         data-testid={`RecentProtocolRun_OverflowMenu_rerunNow`}
       >
         {t('rerun_now')}
       </MenuItem>
+      {isRobotOnWrongVersionOfSoftware && (
+        <Tooltip {...tooltipProps}>
```
Comment (jerader) [inline app/src/organisms/Devices/HistoricalProtocolRunOverflowMenu.tsx]: `Tooltip` in the App folder is the one with the correct styling

**Review by jerader — APPROVED** [review]
lgtm, tested on robot and works as expected
