### PR TITLE
fix(app): pipette card banners and historical protocol run protocolNames render fix

### LINKED ISSUE #10658: 6.0 Feedback: device detail page loading process
### Overview

Much of the information on the device detail page changes as it is loaded for the first time (or when reloading the page). It flashes warnings that can be distracting or concerning to users. Some information remains inaccurate even after everything is loaded.

### Current Behavior

These sections show incorrect information as they load:

1. Pipettes
     - [ ] Pipette images do not show initially (going be addressed in a follow up ticket: https://github.com/Opentrons/opentrons/issues/10847) 
     - [x] "Pipette Offset calibration missing. Calibrate deck first." warning shows very briefly
     - [x] "Pipette Offset calibration needed. Calibrate now" shows slightly longer
2. Protocol runs
    - [x] Entries in the Protocol column initially appear as hex identifiers, and only later update to display names.

These sections show incorrect information even after load:
- [ ] Protocol run status shows as "Canceled" for all runs prior to 6.0.0-alpha1
- [ ] Protocol run duration shows as time between protocol timestamp and present time, instead of between protocol start and end (this will be addressed in this ticket: https://github.com/Opentrons/opentrons/issues/10738) 

https://user-images.githubusercontent.com/1958332/172464999-46c2bf77-3cd4-4817-86d1-04f94f5a19d5.mov

### Expected Behavior

- Pipette images should display at same time as pipette names
- Pipette warnings should never show in a state when they are not needed
- Protocol hex identifiers should never be shown instead of names
- Run durations should be accurate

### Steps To Reproduce

Connect to a robot and navigate to its page under Devices. The above behavior happens on first load or when manually triggering a reload from the View menu.

### Operating system

Mac

### Robot setup or anything else?

_No response_

### PR DESCRIPTION
**Pull request by jerader**
partially fixes #10658

# Overview

This PR fixes the rendering issue when you open the Robot Overview page for the first time. The Banners on the pipette cards shouldn't be there unless you haven't completed a calibration. The historical protocol runs should display either null or the protocol name

# Changelog

- add `useDispatchApiRequest` to `PipetteCard` so the banners render null until the state is no longer pending
- add `useDispatchApiRequest` and `useEffect` to `RecentProtocolRuns` to fetch the protocols. when the protocol name from the protocol metadata is not fetched it, the `protocolName` will be an empty string

# Review requests

- make sure your pipettes have been calibrated and deck calibration is complete. Click on the robot card to go to the robot overview, the pipette cards should not render the banners
- run a few protocols so your historical protocol run has a history. then refresh the page, the historical protocol run protocolNames should be either null or render the protocol name

# Risk assessment

low

### CODE REVIEW

File: app/src/organisms/Devices/PipetteCard/index.tsx [hunk 1]
```diff
@@ -78,6 +84,12 @@ export const PipetteCard = (props: PipetteCardProps): JSX.Element => {
     pipetteId,
     mount
   )
+  const latestRequestId = last(requestIds)
+  const isFetching = useSelector<State, boolean>(state =>
+    latestRequestId
+      ? getRequestById(state, latestRequestId)?.status === 'pending'
+      : false
```
Comment (koji) [inline app/src/organisms/Devices/PipetteCard/index.tsx]:
```suggestion
    (latestRequestId != null)
      ? getRequestById(state, latestRequestId)?.status === 'pending'
      : false
```

**Review by koji — APPROVED** [review]
Works as expected and the changes look good to me!

Maybe you want to switch `import { last } from lodash'` to `import last from 'lodash/last'`

- app/src/organisms/Devices/ModuleCard/index.tsx
- app/src/organisms/Devices/PipetteCard/PipetteSettingsSlideout.tsx

File: app/src/organisms/Devices/ModuleCard/index.tsx [hunk 2]
```diff
@@ -1,7 +1,7 @@
 import * as React from 'react'
 import { Trans, useTranslation } from 'react-i18next'
 import { useDispatch, useSelector } from 'react-redux'
-import { last } from 'lodash'
+import last from 'lodash/last'
```
Comment (koji) [inline app/src/organisms/Devices/ModuleCard/index.tsx:4]: 👍
