### PR TITLE
fix(app): titlebar cancel run button behavior and styling

### LINKED ISSUE #9049: add a new case for users who close an in progress protocol from the protocols page
For users who have a protocol in progress and navigate to the protocol tab and close the protocol, we should show a modal that says

"Protocol run in progress. Cancel run and close protocol?
Buttons: 
no, go back
Yes, cancel and close protocol"

> dev-speak: add new conditional text to the confirm close modal when you launch it from the protocol tab to account for a situation when the user has started the protocol. and render the upload empty state as soon as either a stop or dismiss request is in progress. 

This should also include a CPX ticket to allow dismiss an unstated protocol cc @shlokamin can you add some color to this part

### PR DESCRIPTION
**Pull request by b-cooper**
# Overview

- Ensure button styling for the title bar cancel button on the Protocol and Run pages matches the design by using the `NewAlertSecondaryBtn`.  

- Make sure that closing a run via `useCloseCurrentRun` will never lead to a stop/cancel action. 

- Remove `useCloseCurrentRun`'s error handling ability to delete a run record.

Closes #9049

# Review requests

- [ ] Cancel a protocol run from the protocol and/or the run tab.  Make sure the active and hover state of the button is red.  
- [ ] ensure that closing a cancelled protocol doesn't send another cancel command (this would home the robot as well)

# Risk assessment

med, this removes the client's ability to unblock itself if the "uncurrent" run request fails.

### CODE REVIEW

File: app/src/organisms/ProtocolUpload/index.tsx [hunk 1]
```diff
@@ -137,17 +135,16 @@ export function ProtocolUpload(): JSX.Element {
...
   const cancelRunButton = (
-    <NewSecondaryBtn
+    <NewAlertSecondaryBtn
       onClick={confirmCancelModalExit}
-      lineHeight={LINE_HEIGHT_SOLID}
       marginX={SPACING_3}
-      paddingRight={SPACING_2}
-      paddingLeft={SPACING_2}
-      color={C_ERROR_DARK}
+      paddingX={SPACING_2}
```
Comment (shlokamin) [inline app/src/organisms/ProtocolUpload/index.tsx:144]: do we need both of these?

**Review by shlokamin — APPROVED** [review]
LGTM!

File: app/src/organisms/ProtocolUpload/index.tsx (hunk 1 above)
Comment (b-cooper) [reply app/src/organisms/ProtocolUpload/index.tsx:144]: Yeah we need the padding to overwrite the default padding to make the button small, and we need the margin in order to back off the button from the edge of the titlebar.
