### PR TITLE
fix(app): module cards and slideouts various bug fixes

### LINKED ISSUE #10839: 6.0 Feedback: Heater-Shaker Module controls (card, slide-out, modal)
### Overview

A variety of unexpected behaviors when controlling a module connected to an OT-2 from the Device Detail page.

### Current Behavior

1. Incorrect statuses when turning on module:
	1. Heater listed as "Cooling" (persists until temperature set). Relatedly, first item in overflow menu starts as "Deactivate". Should begin as "Set target temperature" and change to "Deactivate heater".
	2. Shaker listed as "Holding At Target" (changes to "Idle")

https://user-images.githubusercontent.com/1958332/174400383-8b6815b6-090f-41ca-9529-5708245128fd.mov

2. Target speed shown in card can be different than input target. Specifically, it's always rounded down to a multiple of 6. This is most noticeable when setting the shake speed to 200, which is rounded down and reported as 198, which is below the minimum target allowed.
4. Slide-outs: hitting enter does not submit the target temperature or speed.
5. Slide-outs: input value is persisted *across* temperature and shake slide-outs. This is not useful, since the two acceptable ranges don't overlap.

https://user-images.githubusercontent.com/1958332/174400546-2dc95384-a477-4baf-bc1f-713285ff72a4.mov

5. Slide-outs: `-`, `--`, and `--` + an in-range value are all accepted inputs but result in no module action.
6. Confirm attachment modal: background dim is misaligned

https://user-images.githubusercontent.com/1958332/174401044-5e0357a9-0927-4d60-bad9-8ffc1a9e10f9.mp4

Screen Shot 2022-06-17 at 4 35 24 PM

7. Copy: no space between numbers and "°C", e.g. "37°C"

### Expected Behavior

1. Module should be reported as "Idle" for both heater and shaker when powered on.
2. Target speed should be exact value entered by user (or rounded to nearest 1 rpm).
3. Hitting enter in the text field should have the same effect as clicking the "Confirm" button.
4. Input values should be persisted separately for the temperature and shake slide-outs.
5. Values beginning with `-` should be rejected.
6. Dimming rectangle should be aligned to window edge.
7. Should be a space between number and "°C", e.g. "37 °C".

### Steps To Reproduce

_No response_

### Operating system

Mac

### Robot setup or anything else?

App on `release_6.0.0` branch commit [0e8888d](https://github.com/Opentrons/opentrons/commit/0e8888d2eb066a1432b56799796701f41c17890e).

Heater-Shaker on firmware v0.4.4-0b068f7

### LINKED ISSUE #10854: 6.0 Feedback: module controls not available after a successful run
### Overview

Module controls (at least for the Heater-Shaker) do not become available after a successful run until it is uncurrented. Since a protocol can leave the module heating or shaking, users might want to be able to stop it right after a run.

### Current Behavior

The "Some robot controls are not available when run is in progress" status persists even once the run status becomes Completed.

### Expected Behavior

When a run is Completed, it should not be considered "in progress" for the purpose of blocking module controls.

### Steps To Reproduce

1. Run a protocol with modules (see attached for a protocol that runs the Heater-Shaker and leaves it shaking at protocol completion).
[hs.py.zip](https://github.com/Opentrons/opentrons/files/8952587/hs.py.zip)

2. Return to the robot details page.
3. Open the module overflow menu.

The module controls are disabled.
Screen Shot 2022-06-21 at 4 12 25 PM

### Operating system

Mac

### Robot setup or anything else?

Tested on [`edge` on June 21](https://github.com/Opentrons/opentrons/tree/431a53528a3536afce386cfb3f8614fd182824f6) (app and robot server) to enable H-S support.

### PR DESCRIPTION
**Pull request by jerader**
partially closes #10839 and fully closes #10854 and #10856

# Overview

This PR addresses various small fixes within the module cards and module slideouts:

1. fix some spacings
2. slideout buttons are clickable via the enter button on keyboard
3. confirm attachment modal is now rendered above breadcrumbs
4. input field no longer accepts decimal points or negative/positive symbols
5. module commands are accessible via the robot overview module cards when the run is in terminal state (failed, succeeded, stopped)
6. module commands are accessible via the module controls by changing module card logic (this is a temp fix https://opentrons.slack.com/archives/C033PPVEC76/p1656000780091279) 
7. the Run a Protocol button when a run is terminal on RobotOverview is no longer disabled and neither is the "Rerun a protocol" in the Historical protocol run overflow menu

# Changelog

- changed all module slideouts and module card logic by creating new hook `useRunStatues` which returns `isRunstill`, `isRunTerminal`, and `isLegacySessionsInProgress`
- created new button `SubmitPrimaryButton` that uses an input tag and type `submit` so you can submit your command via the enter button
- modified slideout `inputFields` so they don't allow decimal points or plus and minus signs using `valueAsNumber` and `math.Round`
- added logic for sending module commands via the module cards on module controls

# Review requests

- complete a run, the module slideouts should be accessible via the Robot Overview module cards + the commands should send properly
- complete a run, the module slideouts + commands should send properly via the Module Controls module cards
- the input fields should no longer allow decimal points or plus or minus signs and once you input a value, the enter button on the keyboard should send and close the slideout
- complete a run, the Run a protocol button should be clickable in the Robot Overview and the ReRun a protocol option in the historical protocol run overflow menu should be clickable as well

# Risk assessment

low

### CODE REVIEW

**Comment by ecormany** [comment]
> * turn on H-S, status label should say idle instead of cooling

Text says idle, but status indicator is still blue and flashing as if active. 
Screen Shot 2022-06-22 at 1 29 17 PM

> * complete a run, the module slideouts should be accessible

Menu items are active, but "Deactivate" and "Stop Shaking" do not control the module.

> * the input fields should no longer allow decimal points and once you input a value, the enter button on the keyboard should send and close the slideout

🟡 Validation rejects inputs of the form `\d+\.\d+` but the message still just says "Input out of range". For example, `40.3` is rejected, but it _is_ in the acceptable range.
🟡 Values with a trailing decimal, e.g. `40.` are accepted and set the correct temperature.
✅ Pressing enter submits valid values in the slide-out.

I had expected that pressing `.` would not enter text into the field, as is the current behavior for other non-numeric characters.

**Comment by ecormany** [comment]
🐛 First load: if you press enter to submit a shake value and it triggers the Confirm Attachment modal, the whole page reloads and the command isn't sent. After the reload, the same steps will still show the modal but you can click through it and the command works as expected.

https://user-images.githubusercontent.com/1958332/175104728-389e2b97-3d38-4ac9-9e00-f0db6420c73b.mov

**Comment by jerader** [comment]
> 🐛 First load: if you press enter to submit a shake value and it triggers the Confirm Attachment modal, the whole page reloads and the command isn't sent. After the reload, the same steps will still show the modal but you can click through it and the command works as expected.
> 

this issue will be addressed in a follow up ticket: https://github.com/Opentrons/opentrons/issues/10881

File: app/src/organisms/ModuleCard/index.tsx [hunk 1]
```diff
@@ -411,7 +424,7 @@ export const ModuleCard = (props: ModuleCardProps): JSX.Element | null => {
             }}
           />
           {isOverflowBtnDisabled && (
-            <Tooltip {...tooltipProps}>
+            <Tooltip tooltipProps={tooltipProps}>
```
Comment (jerader) [inline app/src/organisms/ModuleCard/index.tsx:409]: changed tooltip to use the `tooltip` in the app folder

File: app/src/atoms/InputField/index.tsx [hunk 2]
```diff
@@ -29,9 +29,9 @@ export interface InputFieldProps {
   /** placeholder text */
   placeholder?: string
   /** optional suffix component, appears to the right of input text */
-  units?: React.ReactNode // TODO: Ian 2018-10-30 rename to 'suffix'
+  units?: React.ReactNode
   /** current value of text in box, defaults to '' */
-  value?: string | null | undefined
+  value?: string | number | null | undefined
```
Comment (vabruzzo) [inline app/src/atoms/InputField/index.tsx]: side note, not required for this PR but if a property is optional, typescript will infer that it is possibly undefined, so there's no need for `| undefined` on any optional property type. there might be some other reason to include this but ive never come across it

File: app/src/atoms/buttons/index.tsx [hunk 3]
```diff
@@ -140,3 +140,46 @@ export const ToggleButton = (props: ToggleBtnProps): JSX.Element => {
...
+export const SubmitPrimaryButton = (
+  props: SubmitPrimaryButtonProps
+): JSX.Element => {
+  const SUBMIT_INPUT_STYLE = css`
+    background-color: ${COLORS.blue};
+    border-radius: ${BORDERS.radiusSoftCorners};
+    padding: ${SPACING.spacing3} ${SPACING.spacing4};
+    color: ${COLORS.white};
+    line-height: ${TYPOGRAPHY.lineHeight20};
+    text-transform: ${TYPOGRAPHY.textTransformNone};
```
Comment (vabruzzo) [inline app/src/atoms/buttons/index.tsx]: why does this need text transform none? thats usually the default. i assume we are overriding something?

File: app/src/organisms/Devices/PipettesAndModules.tsx [hunk 4]
```diff
@@ -40,6 +46,11 @@ export function PipettesAndModules({
   })?.data ?? { left: undefined, right: undefined }
   const isRobotViewable = useIsRobotViewable(robotName)
   const currentRunId = useCurrentRunId()
+  const runStatus = useRunStatus(currentRunId)
+  const isRunTerminal =
```
Comment (vabruzzo) [inline app/src/organisms/Devices/PipettesAndModules.tsx]: down below you have a hook that provides this, perhaps we can use that here?

Comment (vabruzzo) [reply app/src/organisms/Devices/PipettesAndModules.tsx]: oh i see, that provides something slightly different

File: app/src/organisms/Devices/hooks/useRunIncompleteOrLegacySessionInProgress.ts [hunk 5]
```diff
@@ -0,0 +1,24 @@
+import {
+  RUN_STATUS_FAILED,
+  RUN_STATUS_STOPPED,
+  RUN_STATUS_SUCCEEDED,
+} from '@opentrons/api-client'
+import { useAllSessionsQuery } from '@opentrons/react-api-client'
+import { useCurrentRunId } from '../../ProtocolUpload/hooks'
+import { useRunStatus } from '../../RunTimeControl/hooks'
+
+export function useRunIncompleteOrLegacySessionInProgress(): boolean {
```
Comment (vabruzzo) [inline app/src/organisms/Devices/hooks/useRunIncompleteOrLegacySessionInProgress.ts]: on the one hand, im not a fan of hooks like this with "or" in their name, that just indicates to me that they should be two separate hooks for when you need to derive one of these states but not the other.
on the other hand, it's very small and kinda makes sense as one hook. i wonder what others think @b-cooper , @koji

File: app/src/organisms/ModuleCard/ModuleOverflowMenu.tsx [hunk 6]
```diff
@@ -41,7 +51,23 @@ export const ModuleOverflowMenu = (
     handleWizardClick,
     handleSlideoutClick
   )
-  const isBusy = useIsRobotBusy() && runId == null
+  const runStatus = useRunStatus(runId != null ? runId : null)
+  const currentRunId = useCurrentRunId()
+
+  const isIncompleteOrBusy = useRunIncompleteOrLegacySessionInProgress()
+  const isRunStill =
+    runStatus === RUN_STATUS_SUCCEEDED ||
```
Comment (vabruzzo) [inline app/src/organisms/ModuleCard/ModuleOverflowMenu.tsx]: the newly created hook relies on this same status state. One idea to simplify a lot of what we do in this pr regarding `runStatus` logic might be to encapsulate all this stuff in `useRunStatus` itself. something like:

```
const { runStatus, isRunStill, isRunTerminal, isLegacyRunInSession } = runStatus(runId)
```

this way we can still use the raw `runStatus` where we need it but we can also pluck out this derived data.

this might be a bigger change than what we want to do here, but, i quite like this approach as a follow-up refactor

File: app/src/organisms/Devices/ProtocolRun/__tests__/ProtocolRunModuleControls.test.tsx [hunk 7]
```diff
@@ -111,6 +111,7 @@ describe('ProtocolRunModuleControls', () => {
           robotName: 'otie',
           module: mockMagneticModuleGen2,
           runId: 'test123',
+          isModuleControl: true,
```
Comment (koji) [inline app/src/organisms/Devices/ProtocolRun/__tests__/ProtocolRunModuleControls.test.tsx]: Seems that we are missing `isModuleControl: false` case.
I think if you leave a comment on that, it will be helpful for us and one of us will add the case later.

File: app/src/organisms/Devices/hooks/useRunIncompleteOrLegacySessionInProgress.ts (hunk 5 above)
Comment (vabruzzo) [reply app/src/organisms/Devices/hooks/useRunIncompleteOrLegacySessionInProgress.ts]: see my comment below for a possible refactor to provide this derived data from `useRunStatus` itself

File: app/src/atoms/buttons/index.tsx (hunk 3 above)
Comment (jerader) [reply app/src/atoms/buttons/index.tsx]: oh good question, i was just copying and pasting the `primaryButton` but I'll see if it actually does anything. thanks!

File: app/src/organisms/ModuleCard/ModuleOverflowMenu.tsx (hunk 6 above)
Comment (jerader) [reply app/src/organisms/ModuleCard/ModuleOverflowMenu.tsx]: I agree that this would be a great follow up refactor. The logic in this PR got kind of hairy.

~The module cards in Module Controls require a runId while the module cards in Robot Overview do not. Mike mentioned on slack that allowing you to send a command via the Module controls would require a large refactor from the backend. So I had to use some logic to use the module cards in Robot Overview in place of the Module Controls. Admittedly, I was just adding logic to make sure that everything worked properly and didn't really take time to clean it up, given that we want this feature to be in the next beta.~

I did some refactoring. I created a `useRunStatuses` hook and it returns `isRunStill`, `isRunTerminal`, and `isLegacyRunInSession`

File: app/src/atoms/InputField/index.tsx (hunk 2 above)
Comment (koji) [inline app/src/atoms/InputField/index.tsx]: `value?` is optional so I think we can remove `| undefined`.
L36, L38, L40, and L53 are the same.
But this should be optional.

File: app/src/atoms/buttons/index.tsx (hunk 3 above)
Comment (jerader) [reply app/src/atoms/buttons/index.tsx]: you're right. it does nothing. Removing it now 😃

File: app/src/organisms/ModuleCard/HeaterShakerSlideout.tsx [hunk 8]
```diff
@@ -164,14 +166,13 @@ export const HeaterShakerSlideout = (
         onCloseClick={onCloseClick}
         isExpanded={isExpanded}
         footer={
-          <PrimaryButton
+          <SubmitPrimaryButton
+            form={'HeaterShakerSlideout_submitValue'}
```
Comment (koji) [inline app/src/organisms/ModuleCard/HeaterShakerSlideout.tsx]: maybe 
```suggestion
            form="HeaterShakerSlideout_submitValue"
```

File: app/src/organisms/ModuleCard/ModuleOverflowMenu.tsx [hunk 9]
```diff
@@ -52,13 +78,13 @@ export const ModuleOverflowMenu = (
             ] as MenuItemsByModuleType[ModuleType]).map(
               (item: any, index: number) => {
                 return (
-                  <>
+                  <React.Fragment key={`${index}_${module.moduleType}`}>
```
Comment (koji) [inline app/src/organisms/ModuleCard/ModuleOverflowMenu.tsx:72]: just my preference 😂 so completely optional

```suggestion
                  <React.Fragment key={`${module.moduleType}_${index}`}>
```

File: app/src/organisms/ModuleCard/index.tsx [hunk 10]
```diff
@@ -76,13 +82,14 @@ import type { RequestState } from '../../redux/robot-api/types'
...
   robotName: string
+  isModuleControl: boolean
   runId?: string
   slotName?: string
 }
 
 export const ModuleCard = (props: ModuleCardProps): JSX.Element | null => {
   const { t } = useTranslation('device_details')
-  const { module, robotName, runId, slotName } = props
+  const { module, robotName, runId, slotName, isModuleControl } = props
```
Comment (koji) [inline app/src/organisms/ModuleCard/index.tsx]: This should be optional.
aligning the order with `ModuleCardProps` would be more readable.

File: app/src/organisms/ModuleCard/index.tsx [hunk 11]
```diff
@@ -212,6 +219,12 @@ export const ModuleCard = (props: ModuleCardProps): JSX.Element | null => {
...
   }
 
+  //  TODO(jr, 6/23/22): delete this boolean + logic when you can send commands with runId known re: https://opentrons.slack.com/archives/C033PPVEC76/p1656000780091279
+  const isRunTerminal =
+    runStatus === RUN_STATUS_SUCCEEDED ||
+    runStatus === RUN_STATUS_STOPPED ||
+    runStatus === RUN_STATUS_FAILED
+
   return (
     <React.Fragment>
```
Comment (koji) [inline app/src/organisms/ModuleCard/index.tsx]: optional
```suggestion
    <>
```

File: app/src/atoms/buttons/index.tsx (hunk 3 above)
Comment (koji) [reply app/src/atoms/buttons/index.tsx]: I just noticed that we set `text-transform` prop value from `@opentrons/components` in some components.
We should use `${TYPOGRAPHY.`. I will add this to my refactoring to-do list.
Thanks, Vincent and Jethary!

File: app/src/organisms/Devices/hooks/useRunIncompleteOrLegacySessionInProgress.ts (hunk 5 above)
Comment (koji) [reply app/src/organisms/Devices/hooks/useRunIncompleteOrLegacySessionInProgress.ts]: For naming, it would be okay right now.
I guess we can discuss hooks(functionality, naming, etc) when Brent comes back.

File: app/src/organisms/Devices/hooks/__tests__/useRunStatuses.test.tsx [hunk 12]
```diff
@@ -0,0 +1,128 @@
...
+  typeof useRunStatus
+>
+const mockUseCurrentRunId = useCurrentRunId as jest.MockedFunction<
+  typeof useCurrentRunId
+>
+const mockUseAllSessionsQuery = useAllSessionsQuery as jest.MockedFunction<
+  typeof useAllSessionsQuery
+>
+
+describe(' useRunStatuses ', () => {
```
Comment (koji) [inline app/src/organisms/Devices/hooks/__tests__/useRunStatuses.test.tsx:30]: space is on purpose?

**Review by koji — APPROVED** [review]
The changes make sense to me but I would like to get one more reviewer for safety.

File: app/src/atoms/InputField/index.tsx (hunk 2 above)
Comment (jerader) [reply app/src/atoms/InputField/index.tsx]: Whoops, thanks for catching this. There are a bunch of unnecessary `| undefined` in this component

**Review by vabruzzo — COMMENTED** [review]
looks good so far lmk if you find a fix for the current issue and i will approve

File: app/src/organisms/ModuleCard/HeaterShakerSlideout.tsx [hunk 13]
```diff
@@ -42,43 +44,62 @@ interface HeaterShakerSlideoutProps {
   onCloseClick: () => unknown
   isExpanded: boolean
   isSetShake: boolean
-  runId?: string
+  isLoadedInRun: boolean
+  currentRunId?: string
```
Comment (jerader) [inline app/src/organisms/ModuleCard/HeaterShakerSlideout.tsx:48]: i renamed all the slideout `runId` props to `currentRunId` to make it more explicit what the `runId` is

**Review by vabruzzo — APPROVED** [review]
