### PR TITLE
fix(app): Add null check to avoid white screen

### LINKED ISSUE #10490: 6.0 Feedback:  App goes blank while choosing a different tip rack option during tip length calibration
### Overview

https://user-images.githubusercontent.com/39049853/170590280-47b7a93d-9c8a-4238-aeda-b93da5cf05b9.mov

### Current Behavior

Screen Shot 2022-05-26 at 6 28 24 PM

There are no network errors

### Expected Behavior

app should not white screen

### Steps To Reproduce

1. Goto devices page
2. click on the robot
3. Goto robot settings
4. Goto Tip length calibrations -> click on the overflow menu
5. click on Recalibrate Tip length and Pipette Offset option
6. Click on "Use a different Tip Rack"
Screen Shot 2022-05-26 at 6 28 03 PM

### Operating system

_No response_

### Robot setup or anything else?

_No response_

### PR DESCRIPTION
**Pull request by koji**
# Overview
This will close #10490 
The white screen has been caused by getting an id from a null object. 

# Changelog
- Use `usePipettesQuery` to get `pipSerial` (id-serialNumber) instead of `getAttachedPipettes`

# Review requests

# Risk assessment

### CODE REVIEW

File: app/src/organisms/CalibrationPanels/ChooseTipRack.tsx [hunk 1]
```diff
@@ -111,8 +111,9 @@ export function ChooseTipRack(props: ChooseTipRackProps): JSX.Element {
 
   const pipSerial = useSelector(
     (state: State) =>
-      // @ts-expect-error(sa, 2021-05-26): possibly null, can optionally chain. leaving to avoid src code change
-      robotName && getAttachedPipettes(state, robotName)[mount].id
+      robotName != null &&
+      getAttachedPipettes(state, robotName)[mount] != null &&
+      getAttachedPipettes(state, robotName)[mount]?.id
```
Comment (koji) [inline app/src/organisms/CalibrationPanels/ChooseTipRack.tsx]: - [x] Need to use a new function that Sarah made

**Review by b-cooper — APPROVED** [review]
🎣
