### PR TITLE
fix(app): display error and close run if protocol analysis is not-ok

### LINKED ISSUE #8984: bug: If analysis fails outside a Protocol Engine command, the Opentrons App allows proceeding with the run anyway
# Overview

The v5.0.0-beta.0 app doesn't block you from trying to run a protocol that's known to have fatal errors.

# Steps to reproduce

Upload this protocol through the v5.0.0-beta.0 app:

```python
metadata = {
    "apiLevel": "2.11"
}

def run(protocol):
    tip_rack = protocol.load_labware("opentrons_96_tiprack_300ul", 1)
    pipette = protocol.load_instrument("p300_single_gen2", tip_racks=[tip_rack])
    
    raise RuntimeError()

    well_plate = protocol.load_labware("biorad_96_wellplate_200ul_pcr", 2)

    pipette.pick_up_tip()
    pipette.return_tip()
```

# Current behavior

* The server responds with an analysis of `"not-ok"` (that nonetheless has some succeeded commands).
* The app shows a deck map with all the labware that had successfully loaded before the error. In the example above, the tip rack, but not the well plate.
* The app allows proceeding with the run.
* The run eventually hits the error and the app shows a red "run failed" banner, with no further details.

# Expected behavior

* The app should not allow proceeding with the run.
* The app should probably not even show a deck layout?
* The app should explain why the analysis failed. For example, if the user uploaded a Python protocol and had bad Python syntax, they should get to see the Python syntax error.

### PR DESCRIPTION
**Pull request by smb2268**
fix #8984

# Overview
If a protocol analysis result is `not-ok` we should display the error and close the protocol run.

# Changelog

1. Display error if protocol run is not-ok
2. Add `isProtocolRunLoaded` boolean as return value to `useCloseCurrentRun`
3. use `isProtocolRunLoaded` in relevant places

# Review requests

Upload a protocol that will fail analysis and make sure:
- [ ]  error appears as expected
- [ ] you return to the empty protocol state
- [ ] the run tab is still disabled

# Risk assessment

Low

### CODE REVIEW

File: app/src/organisms/ProtocolUpload/index.tsx [hunk 1]
```diff
@@ -36,34 +36,55 @@ import type { ErrorObject } from 'ajv'
...
     setUploadError(null)
   }
 
+  React.useEffect(() => {
+    if (
+      protocolRecord != null &&
+      'result' in protocolRecord?.data?.analyses[0] &&
+      protocolRecord?.data?.analyses[0]?.result === 'not-ok'
+    ) {
+      console.log(protocolRecord?.data.analyses[0].errors[0])
```
Comment (b-cooper) [inline app/src/organisms/ProtocolUpload/index.tsx]:
```suggestion
```

**Review by b-cooper — APPROVED** [review]
Looks good. Could we also include the the `isProtocolRunLoaded` boolean in line 70 of the `RunDetails` index instead of the current condition that is gating the redirect to the upload tab?
