### PR TITLE
fix(app): App fix robot settings design feedback

### LINKED ISSUE #10263: 6.0 Feedback:  [Design QA] Robot Settings Page#10151 & Robot Settings > Advanced > Usage settings styling is off #10106
### Overview

Round 1 design QA for Robot Settings page

### Current Behavior

View the [annotated Figma frame](https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=11756%3A288136)

----
**Calibration**
- [x] (1) Update the font styling here to the updated label font size  (11 font size, 12px line height)
- [x] (2) Update font colour to our 'dark-black'
- [x] (3) Update this link to our 'link/primary/blue/internal' styling. There's a heavier font weight and a hover state
- [x] (4) Update the tertiary button styling. Need correct hover/pressed/potentially disabled state (cant activate disabled using devtools)
- [x] (5) Are we nixing the rest of the content on this page? If so, let's nix that last line beneath content. Also, let me know so I can update designs.

**Networking**
- [x] (1) Update all text to our 'dark-black' on this page
- [x] (2) Should be semi-bold
- [x] (3) Update to our 'input/field-with-label' component. The label should be our label styling, currently our p styling
- [x] (4) Missing 24px margin
- [x] (5) Double the size of the icon, should be 12x12
- [x] (6) Missing hover state on the primary link styling
- [x] (7) 1rem spacing between link and "looking for
- [x] (8) Need to update these icons

**Advanced**
- [x] (1) Bit too much spacing here, should be 1rem from the edge of the container
- [x] (2) Update all text to our 'dark-black' on this page
- [x] (3) Should be 1 rem beneath each section header (about, usage settings, trouble shooting, legacy settings). Also, making a last-minute decision to update the headers from h3's to h2's and semibold to help add some distinction.
- [x] (4) Update tertiary button style
- [x] (5) Needs our link styling (semibold, hover states)
- [ ] (6) Missing the 'update now' button? This displays when the toast saying there's an update available. 
- [x] (7) Upping the margin to 40px between each section (sorry, this is new!)
- [x] (8) Update these to our toggle component
- [x] (9) Update size of font, size of icon and add the states in
- [x] (10) Looks like a margin-bottom of 1rem snuck in there

Screen Shot 2022-05-10 at 3 14 21 PM
Screen Shot 2022-05-10 at 3 14 27 PM
Screen Shot 2022-05-10 at 3 14 34 PM
Screen Shot 2022-05-10 at 3 14 38 PM

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Operating system

_No response_

### Robot setup or anything else?

_No response_

### PR DESCRIPTION
**Pull request by koji**
# Overview
This will fix #10263 
Reflected the feedback on `RobotSettings`.

# Changelog
- Updated RobotSettingsCalibration styling
- Updated RobotSettingsNetworking styling
- Updated RobotSettingsAdvanced styling
- Update linkPsemiBold line-height
- Change `GlobalStyle` color to `darkBlack`

# Review requests

# Risk assessment
low

### CODE REVIEW

File: app/src/atoms/Link/ExternalLink.tsx [hunk 1]
```diff
@@ -15,13 +17,15 @@ export interface ExternalLinkProps extends LinkProps {
...
-    ></Icon>
+  <Link external {...props}>
+    <Flex alignItems={ALIGN_CENTER} css={TYPOGRAPHY.linkPSemiBold}>
+      {props.children}
+      <Icon
+        width={SPACING.spacing3}
+        height={SPACING.spacing3}
+        marginLeft=".4375rem"
+        name="open-in-new"
+      ></Icon>
```
Comment (b-cooper) [inline app/src/atoms/Link/ExternalLink.tsx]:
```suggestion
      />
```

File: app/src/organisms/Devices/RobotSettings/RobotSettingsNetworking.tsx [hunk 2]
```diff
@@ -74,30 +74,29 @@ export function RobotSettingsNetworking({
           <Box height={SPACING.spacing4} width={SPACING.spacing5}></Box>
         )}
         <Icon
-          width={SPACING.spacing4}
-          name="ot-wifi-3"
+          height="1.25rem"
```
Comment (b-cooper) [inline app/src/organisms/Devices/RobotSettings/RobotSettingsNetworking.tsx]: there's a handy `size` prop that can be used here if the height and width are the same

File: app/src/organisms/Devices/RobotSettings/RobotSettingsNetworking.tsx [hunk 3]
```diff
@@ -149,7 +147,8 @@ export function RobotSettingsNetworking({
           <Box height={SPACING.spacing4} width={SPACING.spacing4}></Box>
         )}
         <Icon
-          width={SPACING.spacing4}
+          height="1.25rem"
```
Comment (b-cooper) [inline app/src/organisms/Devices/RobotSettings/RobotSettingsNetworking.tsx]: same comment about `size` prop

**Review by b-cooper — APPROVED** [review]
Code changes look good, just a couple of nits. ⚡
