### PR TITLE
fix(app): Address Labware import slideout design feedback

### LINKED ISSUE #10926: 6.0 Feedback: [Design QA] Labware T1 Slideout
### Overview
The original feedback is in #10618
[To a dev who picks this up]
Please do not close #10618 until finish fixing all slideouts design feedback.
If you have any questions on this feedback, please ask about your questions to Mel.

### Current Behavior

Link to [annotated frame in Figma ](https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=13793%3A416275)

### **Import custom labware def + toast**
- [x] (1) Size of this button should be 24px (currently 20px)
- [x] (2) remove the box-shadow
- [x] (3) Going to sneak this toast edit in here for simplicity sake, but can we add a max-width of these toasts to like 70% of the viewport? This percentage should also work when we shrink down to our min-width size 
- [x] (4) Can we make it a rule that the toasts stay for 8s instead of 4? Noticing that it's a bit quick. 
- [x] (5) Could we have the toast fade in and out like[ this example? ](https://polaris.shopify.com/components/feedback-indicators/toast#navigation)
- [x] (6) Center this text
- [x] (7) needs 2rem margin-top

Screen Shot 2022-06-03 at 10 12 25 AM
Screen Shot 2022-06-03 at 10 07 04 AM

### PR DESCRIPTION
**Pull request by koji**
# Overview
This will address labware slideout design feedback and update Toast functionality
fix #10926

* In terms of Toast, got confirmation from Mel
- use slideup animation for our Toast
- use 5 sec as the default duration

sample: https://polaris.shopify.com/components/toast#navigation

# Changelog
- address design feedback
- add `duration` to Toast and set the default duration 5s 
- add a new test case for `duration`

# Review requests
- design feedback is addressed
- Would like to get feedback on `duration`. I set 5 sec as the default since the UI components Mel cited uses 5 sec as the default duration. Actually, Mel asked about changing the duration to 8 sec. However, I think that's kind of long because the current duration is 3 sec. Any suggestions are appreciated.

# Risk assessment
low

### CODE REVIEW

File: app/src/atoms/Toast/index.tsx [hunk 1]
```diff
@@ -78,15 +81,17 @@ export function Toast(props: ToastProps): JSX.Element {
     closeButton,
     onClose,
     disableTimeout = false,
+    duration = 5000,
```
Comment (brenthagen) [inline app/src/atoms/Toast/index.tsx:84]: i think an 8 second timeout makes sense because some of these toasts have a lot of info/error content

File: app/src/atoms/Toast/index.tsx [hunk 2]
```diff
@@ -24,19 +24,22 @@ export interface ToastProps {
...
 }
 
 const EXPANDED_STYLE = css`
   animation-duration: 300ms;
-  animation-name: slidein;
+  animation-name: slideup;
   overflow: hidden;
 
-  @keyframes slidein {
+  @keyframes slideup {
```
Comment (brenthagen) [inline app/src/atoms/Toast/index.tsx:35]: should we slide down also on close or timeout?

**Review by jerader — APPROVED** [review]
I agree that we should add a slide down animation at some point. But otherwise this LGTM

**Review by vabruzzo — APPROVED** [review]

File: app/src/atoms/Toast/index.tsx (hunk 1 above)
Comment (koji) [reply app/src/atoms/Toast/index.tsx:84]: @brenthagen @jerader @vabruzzo 

https://user-images.githubusercontent.com/474225/177624427-2a93f50f-7222-45c0-aa31-5b8482d5937a.mov


https://user-images.githubusercontent.com/474225/177624453-3813ee78-d6ea-4408-9788-f55ae3f12e3a.mov

File: app/src/atoms/Toast/index.tsx (hunk 2 above)
Comment (mmencarelli) [reply app/src/atoms/Toast/index.tsx:35]: oooh, could we add a slide down?

File: app/src/atoms/Toast/index.tsx (hunk 1 above)
Comment (mmencarelli) [reply app/src/atoms/Toast/index.tsx:84]: i'm down for 8s!

Comment (koji) [reply app/src/atoms/Toast/index.tsx:84]: Updated the default to `8 sec`
